//! The answer is constrained by the assessment schema the contracts generate,
//! rather than by one this crate wrote.
//!
//! Proven by identity and drift together, and then over three scripted answers.
//! A byte comparison is deliberately not what establishes it: a crate that
//! copied the generated bytes into a schema file of its own would pass one,
//! while defeating the very thing this is about.
//!
//! **The drift half writes to the checked-in artifact itself**, which is the
//! only file the identity half will accept the port naming, and puts it back.
//! `printobserver-supervisor-api`'s suite reads that same file on every gate run, and
//! `nx run-many` drives it while this project's tests are still going, so both
//! sides take the lock [`schema_lock`] describes and neither ever sees the
//! other's half-done tree. This journey is the one holder of the exclusive
//! form, and it holds it from its first read to its last: the artifact it
//! drives against before changing anything is the same file every other
//! journey reads, so a shared hold dropped and an exclusive one taken later
//! would leave those first reads racing the same change. The artifact is
//! restored by a guard rather than by the last line of a journey, so the tree
//! comes back even from a panic, and this journey reads it back afterwards to
//! say so.

use std::fs;
use std::path::{Path, PathBuf};
use std::sync::Arc;

use printobserver_supervisor_api::Confidence;
use printobserver_supervisor_api::{SupervisorError, SupervisorPort};
use printobserver_types::{EventBody, PrintId, serde_json};

use crate::support::{
    Exclusive, Fixture, HARNESS, SchemaHold, Watch, always, assessment, block_on, config, event,
    generated_assessment_schema, port, schema_lock, turn, unreadable,
};

/// An event to hang a turn off.
fn payload() -> EventBody {
    unreadable("the body was not JSON")
}

/// Drive one turn under one scripted answer, and answer what the port made of
/// it, having also handed back the run requests it built.
///
/// The schema is read under this journey's own exclusive hold, so a drive
/// before the artifact is changed and one after it read the same tree nobody
/// else is touching.
fn drive(
    held: &SchemaHold<Exclusive>,
    fixture: &Fixture,
    schema: &std::path::Path,
    answer: &str,
) -> (
    Result<printobserver_supervisor_api::TurnOutcome, SupervisorError>,
    Vec<oneharness_core::io::run::RunRequest>,
) {
    let watch = Arc::new(Watch::default());
    let supervisor = port(
        config(held, fixture, HARNESS, schema, always("SID-SCHEMA", answer)),
        &watch,
    );
    let print_id = PrintId::new();
    let outcome = block_on(supervisor.run_turn(turn(print_id, event(print_id, payload()), None)));
    (outcome, watch.requests())
}

/// The generated artifact is what the run request names, it is what constrains
/// the answer, and changing it changes what is accepted.
#[test]
fn the_answer_is_constrained_by_the_generated_assessment_schema() {
    // The one exclusive hold on the checked-in schema tree, for the whole of
    // this journey: the artifact is changed on disk further down, and every
    // read here — before the change, under it and after the restore — is of
    // the tree this hold keeps every other suite out of.
    let schemas = schema_lock();
    let fixture = Fixture::new("schema");
    let generated = generated_assessment_schema();
    let conforming = assessment("the first layer is down", "high");

    // The schema on the run request is the generated assessment schema's own
    // checked-in artifact, not a file this crate carries.
    let (accepted, requests) = drive(&schemas, &fixture, &generated, &conforming);
    let named = requests
        .first()
        .expect("the port built a run request")
        .schema
        .clone()
        .expect("the run request names a schema");
    assert_eq!(
        fs::canonicalize(&named).expect("the named schema exists"),
        fs::canonicalize(&generated).expect("the generated artifact exists"),
        "the run request names {} rather than the generated artifact",
        named.display()
    );
    assert!(
        !fs::canonicalize(&named)
            .expect("the named schema exists")
            .starts_with(fs::canonicalize(env!("CARGO_MANIFEST_DIR")).expect("this crate exists")),
        "the schema the answer is constrained by is a file this crate carries"
    );

    // The first of three scripted answers: one conforming, and it reads back
    // with the fields it carried.
    let outcome = accepted.expect("a conforming answer is accepted");
    assert_eq!(outcome.assessment.summary, "the first layer is down");
    assert_eq!(outcome.assessment.confidence, Confidence::High);
    assert!(outcome.assessment.should_continue);
    assert!(!outcome.assessment.escalating);
    assert_eq!(
        outcome.assessment.did,
        "read the event, the picture and the print's context"
    );
    assert_eq!(
        outcome.assessment.why,
        "the first layer is down and the walls are clean"
    );

    // Two well-formed answers that violate a constraint the schema declares:
    // one leaving out a field the schema requires, one naming a confidence
    // outside the closed vocabulary it declares. A schema constraining nothing
    // would accept both, which is what makes this the case that distinguishes
    // the declared schema from an arbitrary one.
    let missing = serde_json::json!({
        "summary": "the first layer is down",
        "should_continue": true,
        "did": "looked",
        "why": "it is fine",
        "escalating": false,
    })
    .to_string();
    let outside = assessment("the first layer is down", "certain");
    for (label, answer) in [
        ("a missing field", &missing),
        ("a bad confidence", &outside),
    ] {
        let (refused, _) = drive(&schemas, &fixture, &generated, answer);
        assert!(
            matches!(refused, Err(SupervisorError::InvalidAnswer { .. })),
            "{label} was accepted: {refused:?}"
        );
    }

    // And one that is not well-formed at all.
    let (refused, _) = drive(&schemas, &fixture, &generated, "the print looks fine to me");
    assert!(
        matches!(refused, Err(SupervisorError::InvalidAnswer { .. })),
        "an answer that is not JSON was accepted: {refused:?}"
    );

    // What the port validates against is the artifact on disk rather than a
    // copy of its bytes, which is what changing that artifact tells apart. The
    // artifact is changed under the exclusive hold every other suite that
    // reads the schema tree waits on, and restored by a guard rather than by
    // the last line of this journey — so the tree comes back even from a panic
    // here.
    let held = HeldArtifact::hold(&generated, &schemas);
    let (before, _) = drive(&schemas, &fixture, &generated, &conforming);
    before.expect("the conforming answer is accepted against the artifact");

    // One field constrained more strictly, and the port built again.
    let mut stricter: serde_json::Value =
        serde_json::from_slice(&held.original).expect("the artifact is JSON");
    stricter["properties"]["summary"]["minLength"] = serde_json::json!(500);
    held.replace(&serde_json::to_vec_pretty(&stricter).expect("the variant serializes"));

    let (after, _) = drive(&schemas, &fixture, &generated, &conforming);
    assert!(
        matches!(after, Err(SupervisorError::InvalidAnswer { .. })),
        "the answer accepted before is still accepted after the artifact changed, \
         so the port is not reading it: {after:?}"
    );

    // Restored, byte for byte, and accepted again.
    let original = held.original.clone();
    drop(held);
    assert_eq!(
        fs::read(&generated).expect("the artifact is readable"),
        original,
        "the artifact was not put back as the tree carries it"
    );
    let (restored, _) = drive(&schemas, &fixture, &generated, &conforming);
    restored.expect("the conforming answer is accepted once the artifact is restored");
}

/// The checked-in artifact, remembered while this journey changes it.
///
/// It borrows the journey's exclusive hold on the schema tree, so it can only
/// be made by a journey holding one and cannot outlive it: the artifact's own
/// bytes are put back while every other suite is still kept out. Putting them
/// back is [`Drop`]'s doing rather than a line at the end of the journey,
/// because an assertion that fails in between must still leave the tree as it
/// found it.
struct HeldArtifact<'hold> {
    /// Where the artifact is.
    path: PathBuf,
    /// Its bytes as the tree carries them.
    original: Vec<u8>,
    /// The exclusive hold this guard lives under.
    _held: &'hold SchemaHold<Exclusive>,
}

impl<'hold> HeldArtifact<'hold> {
    /// Remember what the artifact says, under an exclusive hold.
    fn hold(path: &Path, held: &'hold SchemaHold<Exclusive>) -> Self {
        Self {
            path: path.to_path_buf(),
            original: fs::read(path).expect("the artifact is readable"),
            _held: held,
        }
    }

    /// Put something else there for as long as this is held.
    fn replace(&self, bytes: &[u8]) {
        fs::write(&self.path, bytes).expect("the artifact is writable");
    }
}

impl Drop for HeldArtifact<'_> {
    fn drop(&mut self) {
        // Loud rather than panicking: a panic here during an unwind would abort
        // the process and bury whatever assertion failed first, and the journey
        // reads the artifact back itself to say it was restored.
        if let Err(error) = fs::write(&self.path, &self.original) {
            eprintln!(
                "the checked-in artifact {} could not be put back: {error}",
                self.path.display()
            );
        }
    }
}
