//! The answer is constrained by the assessment schema the contracts generate,
//! rather than by one this crate wrote.
//!
//! Proven by identity and drift together, and then over three scripted answers.
//! A byte comparison is deliberately not what establishes it: a crate that
//! copied the generated bytes into a schema file of its own would pass one,
//! while defeating the very thing this is about.
//!
//! **Where the drift half does its writing.** It writes to a copy of the
//! generated artifact taken byte for byte, and drives the port against that
//! copy — rather than writing to the checked-in artifact itself, which the
//! contracts' own generation target reads to refuse a drifted tree, and which
//! `printobserver-types`'s suite re-checks on every gate run. Those runs are
//! concurrent with this one, so writing to the checked-in file would make this
//! journey fail a sibling project at random. What the half has to establish is
//! that the port reads the artifact **at run time** rather than validating
//! against an embedded or copied schema, and a byte-identical copy at a path
//! the configuration names establishes exactly that: a port carrying the schema
//! inside itself accepts the same answer after the file changes. Which file the
//! port names is the identity half's question, and it asks it of the checked-in
//! artifact.

use std::fs;
use std::sync::Arc;

use printobserver_supervisor_api::{SupervisorError, SupervisorPort};
use printobserver_types::{
    Confidence, EventPayload, MalformedExternalEventPayload, PrintId, serde_json,
};

use crate::support::{
    Fixture, HARNESS, Watch, always, assessment, block_on, config, event,
    generated_assessment_schema, port, turn,
};

/// An event to hang a turn off.
fn payload() -> EventPayload {
    EventPayload::MalformedExternalEvent(MalformedExternalEventPayload {
        detail: "the body was not JSON".to_owned(),
    })
}

/// Drive one turn under one scripted answer, and answer what the port made of
/// it, having also handed back the run requests it built.
fn drive(
    fixture: &Fixture,
    schema: &std::path::Path,
    answer: &str,
) -> (
    Result<printobserver_supervisor_api::TurnOutcome, SupervisorError>,
    Vec<oneharness_core::io::run::RunRequest>,
) {
    let watch = Arc::new(Watch::default());
    let supervisor = port(
        config(fixture, HARNESS, schema, always("SID-SCHEMA", answer)),
        &watch,
    );
    let print_id = PrintId::new();
    let outcome = block_on(supervisor.run_turn(turn(print_id, event(print_id, payload()), None)));
    (outcome, watch.requests())
}

/// The generated artifact is what the run request names, it is what constrains
/// the answer, and changing it changes what is accepted.
#[test]
fn the_answer_is_constrained_by_the_generated_assessment_schema() {
    let fixture = Fixture::new("schema");
    let generated = generated_assessment_schema();
    let conforming = assessment("the first layer is down", "high");

    // --- Identity -----------------------------------------------------------
    // The schema on the run request is the generated assessment schema's own
    // checked-in artifact, not a file this crate carries.
    let (accepted, requests) = drive(&fixture, &generated, &conforming);
    let named = requests
        .first()
        .expect("the port built a run request")
        .schema
        .clone()
        .expect("the run request names a schema");
    assert_eq!(
        fs::canonicalize(&named).expect("the named schema exists"),
        fs::canonicalize(&generated).expect("the generated artifact exists"),
        "the run request names {} rather than the generated artifact",
        named.display()
    );
    assert!(
        !fs::canonicalize(&named)
            .expect("the named schema exists")
            .starts_with(fs::canonicalize(env!("CARGO_MANIFEST_DIR")).expect("this crate exists")),
        "the schema the answer is constrained by is a file this crate carries"
    );

    // --- The three scripted answers ----------------------------------------
    // One conforming, and it reads back with the fields it carried.
    let outcome = accepted.expect("a conforming answer is accepted");
    assert_eq!(outcome.assessment.summary, "the first layer is down");
    assert_eq!(outcome.assessment.confidence, Confidence::High);
    assert!(outcome.assessment.should_continue);
    assert!(!outcome.assessment.escalating);
    assert_eq!(
        outcome.assessment.did,
        "read the event, the picture and the print's context"
    );
    assert_eq!(
        outcome.assessment.why,
        "the first layer is down and the walls are clean"
    );

    // Two well-formed answers that violate a constraint the schema declares:
    // one leaving out a field the schema requires, one naming a confidence
    // outside the closed vocabulary it declares. A schema constraining nothing
    // would accept both, which is what makes this the case that distinguishes
    // the declared schema from an arbitrary one.
    let missing = serde_json::json!({
        "summary": "the first layer is down",
        "should_continue": true,
        "did": "looked",
        "why": "it is fine",
        "escalating": false,
    })
    .to_string();
    let outside = assessment("the first layer is down", "certain");
    for (label, answer) in [
        ("a missing field", &missing),
        ("a bad confidence", &outside),
    ] {
        let (refused, _) = drive(&fixture, &generated, answer);
        assert!(
            matches!(refused, Err(SupervisorError::InvalidAnswer { .. })),
            "{label} was accepted: {refused:?}"
        );
    }

    // And one that is not well-formed at all.
    let (refused, _) = drive(&fixture, &generated, "the print looks fine to me");
    assert!(
        matches!(refused, Err(SupervisorError::InvalidAnswer { .. })),
        "an answer that is not JSON was accepted: {refused:?}"
    );

    // --- Drift --------------------------------------------------------------
    // A copy of the artifact, taken byte for byte, so what follows is a change
    // to the generated schema rather than to some schema of this journey's own.
    let copy = fixture.path("AgentAssessment.json");
    fs::copy(&generated, &copy).expect("the artifact is copyable");
    assert_eq!(
        fs::read(&copy).expect("the copy is readable"),
        fs::read(&generated).expect("the artifact is readable"),
        "the copy is not the generated artifact"
    );
    let (before, _) = drive(&fixture, &copy, &conforming);
    before.expect("the conforming answer is accepted against the artifact");

    // One field constrained more strictly, and the port built again.
    let mut stricter: serde_json::Value =
        serde_json::from_slice(&fs::read(&copy).expect("the copy is readable"))
            .expect("the artifact is JSON");
    stricter["properties"]["summary"]["minLength"] = serde_json::json!(500);
    fs::write(
        &copy,
        serde_json::to_string_pretty(&stricter).expect("the variant serializes"),
    )
    .expect("the copy is writable");

    let (after, _) = drive(&fixture, &copy, &conforming);
    assert!(
        matches!(after, Err(SupervisorError::InvalidAnswer { .. })),
        "the answer accepted before is still accepted after the artifact changed, \
         so the port is not reading it: {after:?}"
    );

    // Restored, and accepted again.
    fs::copy(&generated, &copy).expect("the artifact is copyable");
    let (restored, _) = drive(&fixture, &copy, &conforming);
    restored.expect("the conforming answer is accepted once the artifact is restored");
}
