"""Generated by `contract-codegen` from the checked-in contract schemas.

 This file is the Python client's walk over every operation the server declares.

 Do not edit by hand: change the contracts, regenerate with `just
 generate-clients`, and commit what that writes.

Every method this client exposes is driven here against a stub host on a
real socket: what the host received is asserted against what the operation
declares, and what the method answered is asserted to carry, field for
field, exactly the document the host sent. A client that transformed a
value on the way out fails that equality rather than needing a probe that
guesses how it transformed it.
"""

from __future__ import annotations

import json
from typing import cast

from host import Host
from printobserver_sdk import Client, NoReasonError, RejectedError
from printobserver_sdk.contract import (
    AcknowledgementDisposition,
    Actor,
    EventId,
    FileName,
    JobManifest,
)
from repo_checks.expect import equal, truth

#: The actor every client of this walk acts as.
ACTOR = cast(
    Actor, json.loads('{"agent": {"session_name": "0198f0a1-2b3c-7d4e-8f90-123456789abc"}}')
)


def test_status_sends_what_it_declares_and_answers_what_was_sent() -> None:
    """`status` sends what it declares and answers what the server sent."""
    answer = json.loads(
        '{"interventions": [{"action_id": "0198f0a1-2b3c-7d4e-8f90-12'
        '3456789abc", "adjustable": "0198f0a1-2b3c-7d4e-8f90-12345678'
        '9abc", "applied_at": "0198f0a1-2b3c-7d4e-8f90-123456789abc",'
        ' "applied_value": 1.5, "expires_at": "0198f0a1-2b3c-7d4e-8f9'
        '0-123456789abc", "id": "0198f0a1-2b3c-7d4e-8f90-123456789abc'
        '", "outcome": "still_active", "print_id": "0198f0a1-2b3c-7d4'
        'e-8f90-123456789abc", "prior_value": 1.5, "restored_at": "01'
        '98f0a1-2b3c-7d4e-8f90-123456789abc"}], "job": {"completion":'
        ' {"out_of_range": true, "value": 1.5}, "error": "0198f0a1-2b'
        '3c-7d4e-8f90-123456789abc", "estimated_print_time_s": 7, "fi'
        'le_name": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "file_orig'
        'in": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "print_time_lef'
        't_s": 7, "print_time_s": 7, "size_bytes": 7, "state": "opera'
        'tional"}, "print": {"end_reason": "0198f0a1-2b3c-7d4e-8f90-1'
        '23456789abc", "ended_at": "0198f0a1-2b3c-7d4e-8f90-123456789'
        'abc", "file_name": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "'
        'id": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "narrowings": ['
        '{"adjustable": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "appl'
        'ied": {"max": 1.5, "min": 1.5}, "requested": {"max": 1.5, "m'
        'in": 1.5}}], "obico_print_id": 7, "opened_at": "0198f0a1-2b3'
        'c-7d4e-8f90-123456789abc", "state": "operational"}, "printer'
        '": {"bed": {"actual_c": {"out_of_range": true, "value": 1.5}'
        ', "offset_c": {"out_of_range": true, "value": 1.5}, "target_'
        'c": {"out_of_range": true, "value": 1.5}}, "chamber": {"actu'
        'al_c": {"out_of_range": true, "value": 1.5}, "offset_c": {"o'
        'ut_of_range": true, "value": 1.5}, "target_c": {"out_of_rang'
        'e": true, "value": 1.5}}, "connection": "operational", "fan_'
        'percent": {"out_of_range": true, "value": 1.5}, "feedrate_fa'
        'ctor": {"out_of_range": true, "value": 1.5}, "flowrate_facto'
        'r": {"out_of_range": true, "value": 1.5}, "observed_at": "01'
        '98f0a1-2b3c-7d4e-8f90-123456789abc", "tools": [{"actual_c": '
        '{"out_of_range": true, "value": 1.5}, "offset_c": {"out_of_r'
        'ange": true, "value": 1.5}, "target_c": {"out_of_range": tru'
        'e, "value": 1.5}}]}, "session": {"close_reason": "0198f0a1-2'
        'b3c-7d4e-8f90-123456789abc", "closed_at": "0198f0a1-2b3c-7d4'
        'e-8f90-123456789abc", "created_at": "0198f0a1-2b3c-7d4e-8f90'
        '-123456789abc", "harness_identity": "0198f0a1-2b3c-7d4e-8f90'
        '-123456789abc", "last_turn_at": "0198f0a1-2b3c-7d4e-8f90-123'
        '456789abc", "print_id": "0198f0a1-2b3c-7d4e-8f90-123456789ab'
        'c", "session_name": "0198f0a1-2b3c-7d4e-8f90-123456789abc"}}'
    )

    with Host(200, answer) as host:
        client = Client(host.address, ACTOR)
        answered = client.status("0198f0a1-2b3c-7d4e-8f90-123456789abc")
        received = host.received()

    equal(received.method, "GET")
    equal(received.target, "/v1/prints/0198f0a1-2b3c-7d4e-8f90-123456789abc/status")
    equal(received.body, "")
    equal(answered, answer, describing="what this call answered")


def test_context_sends_what_it_declares_and_answers_what_was_sent() -> None:
    """`context` sends what it declares and answers what the server sent."""
    answer = json.loads(
        '{"context": {"bounds": {"allowed": {"feedrate": {"max": 1.5,'
        ' "min": 1.5}}}, "interventions": [{"action_id": "0198f0a1-2b'
        '3c-7d4e-8f90-123456789abc", "adjustable": "0198f0a1-2b3c-7d4'
        'e-8f90-123456789abc", "applied_at": "0198f0a1-2b3c-7d4e-8f90'
        '-123456789abc", "applied_value": 1.5, "expires_at": "0198f0a'
        '1-2b3c-7d4e-8f90-123456789abc", "id": "0198f0a1-2b3c-7d4e-8f'
        '90-123456789abc", "outcome": "still_active", "print_id": "01'
        '98f0a1-2b3c-7d4e-8f90-123456789abc", "prior_value": 1.5, "re'
        'stored_at": "0198f0a1-2b3c-7d4e-8f90-123456789abc"}], "job":'
        ' {"completion": {"out_of_range": true, "value": 1.5}, "error'
        '": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "estimated_print_'
        'time_s": 7, "file_name": "0198f0a1-2b3c-7d4e-8f90-123456789a'
        'bc", "file_origin": "0198f0a1-2b3c-7d4e-8f90-123456789abc", '
        '"print_time_left_s": 7, "print_time_s": 7, "size_bytes": 7, '
        '"state": "operational"}, "latest_image": {"id": "0198f0a1-2b'
        '3c-7d4e-8f90-123456789abc", "sha256": "0198f0a1-2b3c-7d4e-8f'
        '90-123456789abc"}, "manifest": {"allowed": {"feedrate": {"ma'
        'x": 1.5, "min": 1.5}}, "file_name": "0198f0a1-2b3c-7d4e-8f90'
        '-123456789abc", "material": "0198f0a1-2b3c-7d4e-8f90-1234567'
        '89abc", "metadata": {"feedrate": "0198f0a1-2b3c-7d4e-8f90-12'
        '3456789abc"}, "nozzle_diameter_mm": 1.5, "slicer_profile": "'
        '0198f0a1-2b3c-7d4e-8f90-123456789abc"}, "print": {"end_reaso'
        'n": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "ended_at": "019'
        '8f0a1-2b3c-7d4e-8f90-123456789abc", "file_name": "0198f0a1-2'
        'b3c-7d4e-8f90-123456789abc", "id": "0198f0a1-2b3c-7d4e-8f90-'
        '123456789abc", "narrowings": [{"adjustable": "0198f0a1-2b3c-'
        '7d4e-8f90-123456789abc", "applied": {"max": 1.5, "min": 1.5}'
        ', "requested": {"max": 1.5, "min": 1.5}}], "obico_print_id":'
        ' 7, "opened_at": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "st'
        'ate": "operational"}, "printer": {"bed": {"actual_c": {"out_'
        'of_range": true, "value": 1.5}, "offset_c": {"out_of_range":'
        ' true, "value": 1.5}, "target_c": {"out_of_range": true, "va'
        'lue": 1.5}}, "chamber": {"actual_c": {"out_of_range": true, '
        '"value": 1.5}, "offset_c": {"out_of_range": true, "value": 1'
        '.5}, "target_c": {"out_of_range": true, "value": 1.5}}, "con'
        'nection": "operational", "fan_percent": {"out_of_range": tru'
        'e, "value": 1.5}, "feedrate_factor": {"out_of_range": true, '
        '"value": 1.5}, "flowrate_factor": {"out_of_range": true, "va'
        'lue": 1.5}, "observed_at": "0198f0a1-2b3c-7d4e-8f90-12345678'
        '9abc", "tools": [{"actual_c": {"out_of_range": true, "value"'
        ': 1.5}, "offset_c": {"out_of_range": true, "value": 1.5}, "t'
        'arget_c": {"out_of_range": true, "value": 1.5}}]}, "recent_e'
        'vents": [{"id": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "ima'
        'ge": {"id": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "sha256"'
        ': "0198f0a1-2b3c-7d4e-8f90-123456789abc"}, "kind": "obico_fa'
        'ilure_alert", "payload": {"ended_at": "0198f0a1-2b3c-7d4e-8f'
        '90-123456789abc", "file_name": "0198f0a1-2b3c-7d4e-8f90-1234'
        '56789abc", "is_warning": true, "obico_print_id": 7, "print_p'
        'aused": true, "started_at": "0198f0a1-2b3c-7d4e-8f90-1234567'
        '89abc"}, "print_id": "0198f0a1-2b3c-7d4e-8f90-123456789abc",'
        ' "raw": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "received_at'
        '": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "source": "obico"'
        '}]}, "image_path": "0198f0a1-2b3c-7d4e-8f90-123456789abc"}'
    )

    with Host(200, answer) as host:
        client = Client(host.address, ACTOR)
        answered = client.context("0198f0a1-2b3c-7d4e-8f90-123456789abc")
        received = host.received()

    equal(received.method, "GET")
    equal(received.target, "/v1/prints/0198f0a1-2b3c-7d4e-8f90-123456789abc/context")
    equal(received.body, "")
    equal(answered, answer, describing="what this call answered")


def test_image_sends_what_it_declares_and_answers_what_was_sent() -> None:
    """`image` sends what it declares and answers what the server sent."""
    answer = json.loads(
        '{"path": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "record": {'
        '"byte_len": 7, "content_type": "0198f0a1-2b3c-7d4e-8f90-1234'
        '56789abc", "event_id": "0198f0a1-2b3c-7d4e-8f90-123456789abc'
        '", "fetched_at": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "id'
        '": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "print_id": "0198'
        'f0a1-2b3c-7d4e-8f90-123456789abc", "relative_path": "0198f0a'
        '1-2b3c-7d4e-8f90-123456789abc", "sha256": "0198f0a1-2b3c-7d4'
        'e-8f90-123456789abc", "source_url": "0198f0a1-2b3c-7d4e-8f90'
        '-123456789abc"}}'
    )

    with Host(200, answer) as host:
        client = Client(host.address, ACTOR)
        answered = client.image("0198f0a1-2b3c-7d4e-8f90-123456789abc")
        received = host.received()

    equal(received.method, "GET")
    equal(received.target, "/v1/images/0198f0a1-2b3c-7d4e-8f90-123456789abc")
    equal(received.body, "")
    equal(answered, answer, describing="what this call answered")


def test_history_sends_what_it_declares_and_answers_what_was_sent() -> None:
    """`history` sends what it declares and answers what the server sent."""
    answer = json.loads(
        '{"events": [{"id": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "'
        'image": {"id": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "sha2'
        '56": "0198f0a1-2b3c-7d4e-8f90-123456789abc"}, "kind": "obico'
        '_failure_alert", "payload": {"ended_at": "0198f0a1-2b3c-7d4e'
        '-8f90-123456789abc", "file_name": "0198f0a1-2b3c-7d4e-8f90-1'
        '23456789abc", "is_warning": true, "obico_print_id": 7, "prin'
        't_paused": true, "started_at": "0198f0a1-2b3c-7d4e-8f90-1234'
        '56789abc"}, "print_id": "0198f0a1-2b3c-7d4e-8f90-123456789ab'
        'c", "raw": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "received'
        '_at": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "source": "obi'
        'co"}]}'
    )

    with Host(200, answer) as host:
        client = Client(host.address, ACTOR)
        answered = client.history("0198f0a1-2b3c-7d4e-8f90-123456789abc", 7)
        received = host.received()

    equal(received.method, "GET")
    equal(received.target, "/v1/prints/0198f0a1-2b3c-7d4e-8f90-123456789abc/history?limit=7")
    equal(received.body, "")
    equal(answered, answer, describing="what this call answered")


def test_manifest_get_sends_what_it_declares_and_answers_what_was_sent() -> None:
    """`manifest_get` sends what it declares and answers what the server sent."""
    answer = json.loads(
        '{"manifest": {"allowed": {"feedrate": {"max": 1.5, "min": 1.'
        '5}}, "file_name": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "m'
        'aterial": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "metadata"'
        ': {"feedrate": "0198f0a1-2b3c-7d4e-8f90-123456789abc"}, "noz'
        'zle_diameter_mm": 1.5, "slicer_profile": "0198f0a1-2b3c-7d4e'
        '-8f90-123456789abc"}, "narrowings": [{"adjustable": "0198f0a'
        '1-2b3c-7d4e-8f90-123456789abc", "applied": {"max": 1.5, "min'
        '": 1.5}, "requested": {"max": 1.5, "min": 1.5}}]}'
    )

    with Host(200, answer) as host:
        client = Client(host.address, ACTOR)
        answered = client.manifest_get("0198f0a1-2b3c-7d4e-8f90-123456789abc")
        received = host.received()

    equal(received.method, "GET")
    equal(received.target, "/v1/prints/0198f0a1-2b3c-7d4e-8f90-123456789abc/manifest")
    equal(received.body, "")
    equal(answered, answer, describing="what this call answered")


def test_manifest_set_sends_what_it_declares_and_answers_what_was_sent() -> None:
    """`manifest_set` sends what it declares and answers what the server sent."""
    answer = json.loads(
        '{"manifest": {"allowed": {"feedrate": {"max": 1.5, "min": 1.'
        '5}}, "file_name": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "m'
        'aterial": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "metadata"'
        ': {"feedrate": "0198f0a1-2b3c-7d4e-8f90-123456789abc"}, "noz'
        'zle_diameter_mm": 1.5, "slicer_profile": "0198f0a1-2b3c-7d4e'
        '-8f90-123456789abc"}, "narrowings": [{"adjustable": "0198f0a'
        '1-2b3c-7d4e-8f90-123456789abc", "applied": {"max": 1.5, "min'
        '": 1.5}, "requested": {"max": 1.5, "min": 1.5}}]}'
    )

    with Host(200, answer) as host:
        client = Client(host.address, ACTOR)
        answered = client.manifest_set(
            "0198f0a1-2b3c-7d4e-8f90-123456789abc",
            "a generated walk is asking",
            cast(
                JobManifest,
                json.loads(
                    '{"allowed": {"feedrate": {"max": 1.5, "min": 1.5}}, "file_na'
                    'me": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "material": "01'
                    '98f0a1-2b3c-7d4e-8f90-123456789abc", "metadata": {"feedrate"'
                    ': "0198f0a1-2b3c-7d4e-8f90-123456789abc"}, "nozzle_diameter_'
                    'mm": 1.5, "slicer_profile": "0198f0a1-2b3c-7d4e-8f90-1234567'
                    '89abc"}'
                ),
            ),
        )
        received = host.received()

    equal(received.method, "PUT")
    equal(received.target, "/v1/prints/0198f0a1-2b3c-7d4e-8f90-123456789abc/manifest")
    equal(
        json.loads(received.body),
        json.loads(
            '{"manifest": {"allowed": {"feedrate": {"max": 1.5, "min": 1.'
            '5}}, "file_name": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "m'
            'aterial": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "metadata"'
            ': {"feedrate": "0198f0a1-2b3c-7d4e-8f90-123456789abc"}, "noz'
            'zle_diameter_mm": 1.5, "slicer_profile": "0198f0a1-2b3c-7d4e'
            '-8f90-123456789abc"}, "reason": "a generated walk is asking"'
            "}"
        ),
        describing="what this call sent",
    )
    equal(answered, answer, describing="what this call answered")


def test_manifest_set_makes_no_request_when_the_reason_is_empty() -> None:
    """`manifest_set` refuses a call with no reason before it is made."""
    with Host(200, {}) as host:
        client = Client(host.address, ACTOR)
        try:
            client.manifest_set(
                "0198f0a1-2b3c-7d4e-8f90-123456789abc",
                "",
                cast(
                    JobManifest,
                    json.loads(
                        '{"allowed": {"feedrate": {"max": 1.5, "min": 1.5}}, "file_na'
                        'me": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "material": "01'
                        '98f0a1-2b3c-7d4e-8f90-123456789abc", "metadata": {"feedrate"'
                        ': "0198f0a1-2b3c-7d4e-8f90-123456789abc"}, "nozzle_diameter_'
                        'mm": 1.5, "slicer_profile": "0198f0a1-2b3c-7d4e-8f90-1234567'
                        '89abc"}'
                    ),
                ),
            )
        except NoReasonError:
            pass
        else:
            truth(False, describing="an absent reason to be refused")

        equal(host.requests(), 0, describing="what an absent reason sent")
    with Host(200, {}) as host:
        client = Client(host.address, ACTOR)
        try:
            client.manifest_set(
                "0198f0a1-2b3c-7d4e-8f90-123456789abc",
                "   ",
                cast(
                    JobManifest,
                    json.loads(
                        '{"allowed": {"feedrate": {"max": 1.5, "min": 1.5}}, "file_na'
                        'me": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "material": "01'
                        '98f0a1-2b3c-7d4e-8f90-123456789abc", "metadata": {"feedrate"'
                        ': "0198f0a1-2b3c-7d4e-8f90-123456789abc"}, "nozzle_diameter_'
                        'mm": 1.5, "slicer_profile": "0198f0a1-2b3c-7d4e-8f90-1234567'
                        '89abc"}'
                    ),
                ),
            )
        except NoReasonError:
            pass
        else:
            truth(False, describing="a blank reason to be refused")

        equal(host.requests(), 0, describing="what a blank reason sent")


def test_pause_sends_what_it_declares_and_answers_what_was_sent() -> None:
    """`pause` sends what it declares and answers what the server sent."""
    answer = json.loads(
        '{"intervention": {"action_id": "0198f0a1-2b3c-7d4e-8f90-1234'
        '56789abc", "adjustable": "0198f0a1-2b3c-7d4e-8f90-123456789a'
        'bc", "applied_at": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "'
        'applied_value": 1.5, "expires_at": "0198f0a1-2b3c-7d4e-8f90-'
        '123456789abc", "id": "0198f0a1-2b3c-7d4e-8f90-123456789abc",'
        ' "outcome": "still_active", "print_id": "0198f0a1-2b3c-7d4e-'
        '8f90-123456789abc", "prior_value": 1.5, "restored_at": "0198'
        'f0a1-2b3c-7d4e-8f90-123456789abc"}, "printer_refusal": "0198'
        'f0a1-2b3c-7d4e-8f90-123456789abc", "record": {"decision": "a'
        'ccepted", "executed_at": "0198f0a1-2b3c-7d4e-8f90-123456789a'
        'bc", "id": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "outcome"'
        ': "succeeded", "print_id": "0198f0a1-2b3c-7d4e-8f90-12345678'
        '9abc", "request": {"action": {"action": "pause", "actor": {"'
        'agent": {"session_name": "0198f0a1-2b3c-7d4e-8f90-123456789a'
        'bc"}}, "reason": "0198f0a1-2b3c-7d4e-8f90-123456789abc"}, "a'
        'ctor": {"agent": {"session_name": "0198f0a1-2b3c-7d4e-8f90-1'
        '23456789abc"}}, "requested_at": "0198f0a1-2b3c-7d4e-8f90-123'
        '456789abc"}}}'
    )

    with Host(200, answer) as host:
        client = Client(host.address, ACTOR)
        answered = client.pause(
            "0198f0a1-2b3c-7d4e-8f90-123456789abc", "a generated walk is asking"
        )
        received = host.received()

    equal(received.method, "POST")
    equal(received.target, "/v1/prints/0198f0a1-2b3c-7d4e-8f90-123456789abc/actions/pause")
    equal(
        json.loads(received.body),
        json.loads(
            '{"actor": {"agent": {"session_name": "0198f0a1-2b3c-7d4e-8f9'
            '0-123456789abc"}}, "reason": "a generated walk is asking"}'
        ),
        describing="what this call sent",
    )
    equal(answered, answer, describing="what this call answered")


def test_pause_surfaces_the_policys_own_refusal() -> None:
    """`pause` surfaces the policy's own refusal, typed."""
    refusal = json.loads(
        '{"intervention": {"action_id": "0198f0a1-2b3c-7d4e-8f90-1234'
        '56789abc", "adjustable": "0198f0a1-2b3c-7d4e-8f90-123456789a'
        'bc", "applied_at": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "'
        'applied_value": 1.5, "expires_at": "0198f0a1-2b3c-7d4e-8f90-'
        '123456789abc", "id": "0198f0a1-2b3c-7d4e-8f90-123456789abc",'
        ' "outcome": "still_active", "print_id": "0198f0a1-2b3c-7d4e-'
        '8f90-123456789abc", "prior_value": 1.5, "restored_at": "0198'
        'f0a1-2b3c-7d4e-8f90-123456789abc"}, "printer_refusal": "0198'
        'f0a1-2b3c-7d4e-8f90-123456789abc", "record": {"decision": {"'
        'rejected": {"out_of_bounds": {"adjustable": "0198f0a1-2b3c-7'
        'd4e-8f90-123456789abc", "allowed": {"max": 1.25, "min": 0.5}'
        ', "requested": 1.5}}}, "executed_at": "0198f0a1-2b3c-7d4e-8f'
        '90-123456789abc", "id": "0198f0a1-2b3c-7d4e-8f90-123456789ab'
        'c", "outcome": "succeeded", "print_id": "0198f0a1-2b3c-7d4e-'
        '8f90-123456789abc", "request": {"action": {"action": "pause"'
        ', "actor": {"agent": {"session_name": "0198f0a1-2b3c-7d4e-8f'
        '90-123456789abc"}}, "reason": "0198f0a1-2b3c-7d4e-8f90-12345'
        '6789abc"}, "actor": {"agent": {"session_name": "0198f0a1-2b3'
        'c-7d4e-8f90-123456789abc"}}, "requested_at": "0198f0a1-2b3c-'
        '7d4e-8f90-123456789abc"}}}'
    )

    with Host(409, refusal) as host:
        client = Client(host.address, ACTOR)
        try:
            client.pause("0198f0a1-2b3c-7d4e-8f90-123456789abc", "a generated walk is asking")
        except RejectedError as refused:
            equal(refused.requested, 1.5)
            equal(refused.allowed, {"min": 0.5, "max": 1.25})
            truth(
                isinstance(refused.reason, dict) and "out_of_bounds" in refused.reason,
                describing="the refusal itself to be carried",
            )
        else:
            truth(False, describing="the policy's refusal to arrive as one")


def test_pause_makes_no_request_when_the_reason_is_empty() -> None:
    """`pause` refuses a call with no reason before it is made."""
    with Host(200, {}) as host:
        client = Client(host.address, ACTOR)
        try:
            client.pause("0198f0a1-2b3c-7d4e-8f90-123456789abc", "")
        except NoReasonError:
            pass
        else:
            truth(False, describing="an absent reason to be refused")

        equal(host.requests(), 0, describing="what an absent reason sent")
    with Host(200, {}) as host:
        client = Client(host.address, ACTOR)
        try:
            client.pause("0198f0a1-2b3c-7d4e-8f90-123456789abc", "   ")
        except NoReasonError:
            pass
        else:
            truth(False, describing="a blank reason to be refused")

        equal(host.requests(), 0, describing="what a blank reason sent")


def test_resume_sends_what_it_declares_and_answers_what_was_sent() -> None:
    """`resume` sends what it declares and answers what the server sent."""
    answer = json.loads(
        '{"intervention": {"action_id": "0198f0a1-2b3c-7d4e-8f90-1234'
        '56789abc", "adjustable": "0198f0a1-2b3c-7d4e-8f90-123456789a'
        'bc", "applied_at": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "'
        'applied_value": 1.5, "expires_at": "0198f0a1-2b3c-7d4e-8f90-'
        '123456789abc", "id": "0198f0a1-2b3c-7d4e-8f90-123456789abc",'
        ' "outcome": "still_active", "print_id": "0198f0a1-2b3c-7d4e-'
        '8f90-123456789abc", "prior_value": 1.5, "restored_at": "0198'
        'f0a1-2b3c-7d4e-8f90-123456789abc"}, "printer_refusal": "0198'
        'f0a1-2b3c-7d4e-8f90-123456789abc", "record": {"decision": "a'
        'ccepted", "executed_at": "0198f0a1-2b3c-7d4e-8f90-123456789a'
        'bc", "id": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "outcome"'
        ': "succeeded", "print_id": "0198f0a1-2b3c-7d4e-8f90-12345678'
        '9abc", "request": {"action": {"action": "pause", "actor": {"'
        'agent": {"session_name": "0198f0a1-2b3c-7d4e-8f90-123456789a'
        'bc"}}, "reason": "0198f0a1-2b3c-7d4e-8f90-123456789abc"}, "a'
        'ctor": {"agent": {"session_name": "0198f0a1-2b3c-7d4e-8f90-1'
        '23456789abc"}}, "requested_at": "0198f0a1-2b3c-7d4e-8f90-123'
        '456789abc"}}}'
    )

    with Host(200, answer) as host:
        client = Client(host.address, ACTOR)
        answered = client.resume(
            "0198f0a1-2b3c-7d4e-8f90-123456789abc", "a generated walk is asking"
        )
        received = host.received()

    equal(received.method, "POST")
    equal(received.target, "/v1/prints/0198f0a1-2b3c-7d4e-8f90-123456789abc/actions/resume")
    equal(
        json.loads(received.body),
        json.loads(
            '{"actor": {"agent": {"session_name": "0198f0a1-2b3c-7d4e-8f9'
            '0-123456789abc"}}, "reason": "a generated walk is asking"}'
        ),
        describing="what this call sent",
    )
    equal(answered, answer, describing="what this call answered")


def test_resume_surfaces_the_policys_own_refusal() -> None:
    """`resume` surfaces the policy's own refusal, typed."""
    refusal = json.loads(
        '{"intervention": {"action_id": "0198f0a1-2b3c-7d4e-8f90-1234'
        '56789abc", "adjustable": "0198f0a1-2b3c-7d4e-8f90-123456789a'
        'bc", "applied_at": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "'
        'applied_value": 1.5, "expires_at": "0198f0a1-2b3c-7d4e-8f90-'
        '123456789abc", "id": "0198f0a1-2b3c-7d4e-8f90-123456789abc",'
        ' "outcome": "still_active", "print_id": "0198f0a1-2b3c-7d4e-'
        '8f90-123456789abc", "prior_value": 1.5, "restored_at": "0198'
        'f0a1-2b3c-7d4e-8f90-123456789abc"}, "printer_refusal": "0198'
        'f0a1-2b3c-7d4e-8f90-123456789abc", "record": {"decision": {"'
        'rejected": {"out_of_bounds": {"adjustable": "0198f0a1-2b3c-7'
        'd4e-8f90-123456789abc", "allowed": {"max": 1.25, "min": 0.5}'
        ', "requested": 1.5}}}, "executed_at": "0198f0a1-2b3c-7d4e-8f'
        '90-123456789abc", "id": "0198f0a1-2b3c-7d4e-8f90-123456789ab'
        'c", "outcome": "succeeded", "print_id": "0198f0a1-2b3c-7d4e-'
        '8f90-123456789abc", "request": {"action": {"action": "pause"'
        ', "actor": {"agent": {"session_name": "0198f0a1-2b3c-7d4e-8f'
        '90-123456789abc"}}, "reason": "0198f0a1-2b3c-7d4e-8f90-12345'
        '6789abc"}, "actor": {"agent": {"session_name": "0198f0a1-2b3'
        'c-7d4e-8f90-123456789abc"}}, "requested_at": "0198f0a1-2b3c-'
        '7d4e-8f90-123456789abc"}}}'
    )

    with Host(409, refusal) as host:
        client = Client(host.address, ACTOR)
        try:
            client.resume("0198f0a1-2b3c-7d4e-8f90-123456789abc", "a generated walk is asking")
        except RejectedError as refused:
            equal(refused.requested, 1.5)
            equal(refused.allowed, {"min": 0.5, "max": 1.25})
            truth(
                isinstance(refused.reason, dict) and "out_of_bounds" in refused.reason,
                describing="the refusal itself to be carried",
            )
        else:
            truth(False, describing="the policy's refusal to arrive as one")


def test_resume_makes_no_request_when_the_reason_is_empty() -> None:
    """`resume` refuses a call with no reason before it is made."""
    with Host(200, {}) as host:
        client = Client(host.address, ACTOR)
        try:
            client.resume("0198f0a1-2b3c-7d4e-8f90-123456789abc", "")
        except NoReasonError:
            pass
        else:
            truth(False, describing="an absent reason to be refused")

        equal(host.requests(), 0, describing="what an absent reason sent")
    with Host(200, {}) as host:
        client = Client(host.address, ACTOR)
        try:
            client.resume("0198f0a1-2b3c-7d4e-8f90-123456789abc", "   ")
        except NoReasonError:
            pass
        else:
            truth(False, describing="a blank reason to be refused")

        equal(host.requests(), 0, describing="what a blank reason sent")


def test_cancel_sends_what_it_declares_and_answers_what_was_sent() -> None:
    """`cancel` sends what it declares and answers what the server sent."""
    answer = json.loads(
        '{"intervention": {"action_id": "0198f0a1-2b3c-7d4e-8f90-1234'
        '56789abc", "adjustable": "0198f0a1-2b3c-7d4e-8f90-123456789a'
        'bc", "applied_at": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "'
        'applied_value": 1.5, "expires_at": "0198f0a1-2b3c-7d4e-8f90-'
        '123456789abc", "id": "0198f0a1-2b3c-7d4e-8f90-123456789abc",'
        ' "outcome": "still_active", "print_id": "0198f0a1-2b3c-7d4e-'
        '8f90-123456789abc", "prior_value": 1.5, "restored_at": "0198'
        'f0a1-2b3c-7d4e-8f90-123456789abc"}, "printer_refusal": "0198'
        'f0a1-2b3c-7d4e-8f90-123456789abc", "record": {"decision": "a'
        'ccepted", "executed_at": "0198f0a1-2b3c-7d4e-8f90-123456789a'
        'bc", "id": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "outcome"'
        ': "succeeded", "print_id": "0198f0a1-2b3c-7d4e-8f90-12345678'
        '9abc", "request": {"action": {"action": "pause", "actor": {"'
        'agent": {"session_name": "0198f0a1-2b3c-7d4e-8f90-123456789a'
        'bc"}}, "reason": "0198f0a1-2b3c-7d4e-8f90-123456789abc"}, "a'
        'ctor": {"agent": {"session_name": "0198f0a1-2b3c-7d4e-8f90-1'
        '23456789abc"}}, "requested_at": "0198f0a1-2b3c-7d4e-8f90-123'
        '456789abc"}}}'
    )

    with Host(200, answer) as host:
        client = Client(host.address, ACTOR)
        answered = client.cancel(
            "0198f0a1-2b3c-7d4e-8f90-123456789abc", "a generated walk is asking"
        )
        received = host.received()

    equal(received.method, "POST")
    equal(received.target, "/v1/prints/0198f0a1-2b3c-7d4e-8f90-123456789abc/actions/cancel")
    equal(
        json.loads(received.body),
        json.loads(
            '{"actor": {"agent": {"session_name": "0198f0a1-2b3c-7d4e-8f9'
            '0-123456789abc"}}, "reason": "a generated walk is asking"}'
        ),
        describing="what this call sent",
    )
    equal(answered, answer, describing="what this call answered")


def test_cancel_surfaces_the_policys_own_refusal() -> None:
    """`cancel` surfaces the policy's own refusal, typed."""
    refusal = json.loads(
        '{"intervention": {"action_id": "0198f0a1-2b3c-7d4e-8f90-1234'
        '56789abc", "adjustable": "0198f0a1-2b3c-7d4e-8f90-123456789a'
        'bc", "applied_at": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "'
        'applied_value": 1.5, "expires_at": "0198f0a1-2b3c-7d4e-8f90-'
        '123456789abc", "id": "0198f0a1-2b3c-7d4e-8f90-123456789abc",'
        ' "outcome": "still_active", "print_id": "0198f0a1-2b3c-7d4e-'
        '8f90-123456789abc", "prior_value": 1.5, "restored_at": "0198'
        'f0a1-2b3c-7d4e-8f90-123456789abc"}, "printer_refusal": "0198'
        'f0a1-2b3c-7d4e-8f90-123456789abc", "record": {"decision": {"'
        'rejected": {"out_of_bounds": {"adjustable": "0198f0a1-2b3c-7'
        'd4e-8f90-123456789abc", "allowed": {"max": 1.25, "min": 0.5}'
        ', "requested": 1.5}}}, "executed_at": "0198f0a1-2b3c-7d4e-8f'
        '90-123456789abc", "id": "0198f0a1-2b3c-7d4e-8f90-123456789ab'
        'c", "outcome": "succeeded", "print_id": "0198f0a1-2b3c-7d4e-'
        '8f90-123456789abc", "request": {"action": {"action": "pause"'
        ', "actor": {"agent": {"session_name": "0198f0a1-2b3c-7d4e-8f'
        '90-123456789abc"}}, "reason": "0198f0a1-2b3c-7d4e-8f90-12345'
        '6789abc"}, "actor": {"agent": {"session_name": "0198f0a1-2b3'
        'c-7d4e-8f90-123456789abc"}}, "requested_at": "0198f0a1-2b3c-'
        '7d4e-8f90-123456789abc"}}}'
    )

    with Host(409, refusal) as host:
        client = Client(host.address, ACTOR)
        try:
            client.cancel("0198f0a1-2b3c-7d4e-8f90-123456789abc", "a generated walk is asking")
        except RejectedError as refused:
            equal(refused.requested, 1.5)
            equal(refused.allowed, {"min": 0.5, "max": 1.25})
            truth(
                isinstance(refused.reason, dict) and "out_of_bounds" in refused.reason,
                describing="the refusal itself to be carried",
            )
        else:
            truth(False, describing="the policy's refusal to arrive as one")


def test_cancel_makes_no_request_when_the_reason_is_empty() -> None:
    """`cancel` refuses a call with no reason before it is made."""
    with Host(200, {}) as host:
        client = Client(host.address, ACTOR)
        try:
            client.cancel("0198f0a1-2b3c-7d4e-8f90-123456789abc", "")
        except NoReasonError:
            pass
        else:
            truth(False, describing="an absent reason to be refused")

        equal(host.requests(), 0, describing="what an absent reason sent")
    with Host(200, {}) as host:
        client = Client(host.address, ACTOR)
        try:
            client.cancel("0198f0a1-2b3c-7d4e-8f90-123456789abc", "   ")
        except NoReasonError:
            pass
        else:
            truth(False, describing="a blank reason to be refused")

        equal(host.requests(), 0, describing="what a blank reason sent")


def test_start_print_sends_what_it_declares_and_answers_what_was_sent() -> None:
    """`start_print` sends what it declares and answers what the server sent."""
    answer = json.loads(
        '{"intervention": {"action_id": "0198f0a1-2b3c-7d4e-8f90-1234'
        '56789abc", "adjustable": "0198f0a1-2b3c-7d4e-8f90-123456789a'
        'bc", "applied_at": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "'
        'applied_value": 1.5, "expires_at": "0198f0a1-2b3c-7d4e-8f90-'
        '123456789abc", "id": "0198f0a1-2b3c-7d4e-8f90-123456789abc",'
        ' "outcome": "still_active", "print_id": "0198f0a1-2b3c-7d4e-'
        '8f90-123456789abc", "prior_value": 1.5, "restored_at": "0198'
        'f0a1-2b3c-7d4e-8f90-123456789abc"}, "printer_refusal": "0198'
        'f0a1-2b3c-7d4e-8f90-123456789abc", "record": {"decision": "a'
        'ccepted", "executed_at": "0198f0a1-2b3c-7d4e-8f90-123456789a'
        'bc", "id": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "outcome"'
        ': "succeeded", "print_id": "0198f0a1-2b3c-7d4e-8f90-12345678'
        '9abc", "request": {"action": {"action": "pause", "actor": {"'
        'agent": {"session_name": "0198f0a1-2b3c-7d4e-8f90-123456789a'
        'bc"}}, "reason": "0198f0a1-2b3c-7d4e-8f90-123456789abc"}, "a'
        'ctor": {"agent": {"session_name": "0198f0a1-2b3c-7d4e-8f90-1'
        '23456789abc"}}, "requested_at": "0198f0a1-2b3c-7d4e-8f90-123'
        '456789abc"}}}'
    )

    with Host(200, answer) as host:
        client = Client(host.address, ACTOR)
        answered = client.start_print(
            "0198f0a1-2b3c-7d4e-8f90-123456789abc",
            cast(FileName, json.loads('"0198f0a1-2b3c-7d4e-8f90-123456789abc"')),
            cast(
                JobManifest,
                json.loads(
                    '{"allowed": {"feedrate": {"max": 1.5, "min": 1.5}}, "file_na'
                    'me": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "material": "01'
                    '98f0a1-2b3c-7d4e-8f90-123456789abc", "metadata": {"feedrate"'
                    ': "0198f0a1-2b3c-7d4e-8f90-123456789abc"}, "nozzle_diameter_'
                    'mm": 1.5, "slicer_profile": "0198f0a1-2b3c-7d4e-8f90-1234567'
                    '89abc"}'
                ),
            ),
            "a generated walk is asking",
        )
        received = host.received()

    equal(received.method, "POST")
    equal(received.target, "/v1/prints/0198f0a1-2b3c-7d4e-8f90-123456789abc/actions/start_print")
    equal(
        json.loads(received.body),
        json.loads(
            '{"actor": {"agent": {"session_name": "0198f0a1-2b3c-7d4e-8f9'
            '0-123456789abc"}}, "file_name": "0198f0a1-2b3c-7d4e-8f90-123'
            '456789abc", "manifest": {"allowed": {"feedrate": {"max": 1.5'
            ', "min": 1.5}}, "file_name": "0198f0a1-2b3c-7d4e-8f90-123456'
            '789abc", "material": "0198f0a1-2b3c-7d4e-8f90-123456789abc",'
            ' "metadata": {"feedrate": "0198f0a1-2b3c-7d4e-8f90-123456789'
            'abc"}, "nozzle_diameter_mm": 1.5, "slicer_profile": "0198f0a'
            '1-2b3c-7d4e-8f90-123456789abc"}, "reason": "a generated walk'
            ' is asking"}'
        ),
        describing="what this call sent",
    )
    equal(answered, answer, describing="what this call answered")


def test_start_print_surfaces_the_policys_own_refusal() -> None:
    """`start_print` surfaces the policy's own refusal, typed."""
    refusal = json.loads(
        '{"intervention": {"action_id": "0198f0a1-2b3c-7d4e-8f90-1234'
        '56789abc", "adjustable": "0198f0a1-2b3c-7d4e-8f90-123456789a'
        'bc", "applied_at": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "'
        'applied_value": 1.5, "expires_at": "0198f0a1-2b3c-7d4e-8f90-'
        '123456789abc", "id": "0198f0a1-2b3c-7d4e-8f90-123456789abc",'
        ' "outcome": "still_active", "print_id": "0198f0a1-2b3c-7d4e-'
        '8f90-123456789abc", "prior_value": 1.5, "restored_at": "0198'
        'f0a1-2b3c-7d4e-8f90-123456789abc"}, "printer_refusal": "0198'
        'f0a1-2b3c-7d4e-8f90-123456789abc", "record": {"decision": {"'
        'rejected": {"out_of_bounds": {"adjustable": "0198f0a1-2b3c-7'
        'd4e-8f90-123456789abc", "allowed": {"max": 1.25, "min": 0.5}'
        ', "requested": 1.5}}}, "executed_at": "0198f0a1-2b3c-7d4e-8f'
        '90-123456789abc", "id": "0198f0a1-2b3c-7d4e-8f90-123456789ab'
        'c", "outcome": "succeeded", "print_id": "0198f0a1-2b3c-7d4e-'
        '8f90-123456789abc", "request": {"action": {"action": "pause"'
        ', "actor": {"agent": {"session_name": "0198f0a1-2b3c-7d4e-8f'
        '90-123456789abc"}}, "reason": "0198f0a1-2b3c-7d4e-8f90-12345'
        '6789abc"}, "actor": {"agent": {"session_name": "0198f0a1-2b3'
        'c-7d4e-8f90-123456789abc"}}, "requested_at": "0198f0a1-2b3c-'
        '7d4e-8f90-123456789abc"}}}'
    )

    with Host(409, refusal) as host:
        client = Client(host.address, ACTOR)
        try:
            client.start_print(
                "0198f0a1-2b3c-7d4e-8f90-123456789abc",
                cast(FileName, json.loads('"0198f0a1-2b3c-7d4e-8f90-123456789abc"')),
                cast(
                    JobManifest,
                    json.loads(
                        '{"allowed": {"feedrate": {"max": 1.5, "min": 1.5}}, "file_na'
                        'me": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "material": "01'
                        '98f0a1-2b3c-7d4e-8f90-123456789abc", "metadata": {"feedrate"'
                        ': "0198f0a1-2b3c-7d4e-8f90-123456789abc"}, "nozzle_diameter_'
                        'mm": 1.5, "slicer_profile": "0198f0a1-2b3c-7d4e-8f90-1234567'
                        '89abc"}'
                    ),
                ),
                "a generated walk is asking",
            )
        except RejectedError as refused:
            equal(refused.requested, 1.5)
            equal(refused.allowed, {"min": 0.5, "max": 1.25})
            truth(
                isinstance(refused.reason, dict) and "out_of_bounds" in refused.reason,
                describing="the refusal itself to be carried",
            )
        else:
            truth(False, describing="the policy's refusal to arrive as one")


def test_start_print_makes_no_request_when_the_reason_is_empty() -> None:
    """`start_print` refuses a call with no reason before it is made."""
    with Host(200, {}) as host:
        client = Client(host.address, ACTOR)
        try:
            client.start_print(
                "0198f0a1-2b3c-7d4e-8f90-123456789abc",
                cast(FileName, json.loads('"0198f0a1-2b3c-7d4e-8f90-123456789abc"')),
                cast(
                    JobManifest,
                    json.loads(
                        '{"allowed": {"feedrate": {"max": 1.5, "min": 1.5}}, "file_na'
                        'me": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "material": "01'
                        '98f0a1-2b3c-7d4e-8f90-123456789abc", "metadata": {"feedrate"'
                        ': "0198f0a1-2b3c-7d4e-8f90-123456789abc"}, "nozzle_diameter_'
                        'mm": 1.5, "slicer_profile": "0198f0a1-2b3c-7d4e-8f90-1234567'
                        '89abc"}'
                    ),
                ),
                "",
            )
        except NoReasonError:
            pass
        else:
            truth(False, describing="an absent reason to be refused")

        equal(host.requests(), 0, describing="what an absent reason sent")
    with Host(200, {}) as host:
        client = Client(host.address, ACTOR)
        try:
            client.start_print(
                "0198f0a1-2b3c-7d4e-8f90-123456789abc",
                cast(FileName, json.loads('"0198f0a1-2b3c-7d4e-8f90-123456789abc"')),
                cast(
                    JobManifest,
                    json.loads(
                        '{"allowed": {"feedrate": {"max": 1.5, "min": 1.5}}, "file_na'
                        'me": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "material": "01'
                        '98f0a1-2b3c-7d4e-8f90-123456789abc", "metadata": {"feedrate"'
                        ': "0198f0a1-2b3c-7d4e-8f90-123456789abc"}, "nozzle_diameter_'
                        'mm": 1.5, "slicer_profile": "0198f0a1-2b3c-7d4e-8f90-1234567'
                        '89abc"}'
                    ),
                ),
                "   ",
            )
        except NoReasonError:
            pass
        else:
            truth(False, describing="a blank reason to be refused")

        equal(host.requests(), 0, describing="what a blank reason sent")


def test_set_feedrate_factor_sends_what_it_declares_and_answers_what_was_sent() -> None:
    """`set_feedrate_factor` sends what it declares and answers what the server sent."""
    answer = json.loads(
        '{"intervention": {"action_id": "0198f0a1-2b3c-7d4e-8f90-1234'
        '56789abc", "adjustable": "0198f0a1-2b3c-7d4e-8f90-123456789a'
        'bc", "applied_at": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "'
        'applied_value": 1.5, "expires_at": "0198f0a1-2b3c-7d4e-8f90-'
        '123456789abc", "id": "0198f0a1-2b3c-7d4e-8f90-123456789abc",'
        ' "outcome": "still_active", "print_id": "0198f0a1-2b3c-7d4e-'
        '8f90-123456789abc", "prior_value": 1.5, "restored_at": "0198'
        'f0a1-2b3c-7d4e-8f90-123456789abc"}, "printer_refusal": "0198'
        'f0a1-2b3c-7d4e-8f90-123456789abc", "record": {"decision": "a'
        'ccepted", "executed_at": "0198f0a1-2b3c-7d4e-8f90-123456789a'
        'bc", "id": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "outcome"'
        ': "succeeded", "print_id": "0198f0a1-2b3c-7d4e-8f90-12345678'
        '9abc", "request": {"action": {"action": "pause", "actor": {"'
        'agent": {"session_name": "0198f0a1-2b3c-7d4e-8f90-123456789a'
        'bc"}}, "reason": "0198f0a1-2b3c-7d4e-8f90-123456789abc"}, "a'
        'ctor": {"agent": {"session_name": "0198f0a1-2b3c-7d4e-8f90-1'
        '23456789abc"}}, "requested_at": "0198f0a1-2b3c-7d4e-8f90-123'
        '456789abc"}}}'
    )

    with Host(200, answer) as host:
        client = Client(host.address, ACTOR)
        answered = client.set_feedrate_factor(
            "0198f0a1-2b3c-7d4e-8f90-123456789abc", 1.5, "a generated walk is asking", 7
        )
        received = host.received()

    equal(received.method, "POST")
    equal(
        received.target,
        "/v1/prints/0198f0a1-2b3c-7d4e-8f90-123456789abc/actions/set_feedrate_factor",
    )
    equal(
        json.loads(received.body),
        json.loads(
            '{"actor": {"agent": {"session_name": "0198f0a1-2b3c-7d4e-8f9'
            '0-123456789abc"}}, "duration_s": 7, "factor": 1.5, "reason":'
            ' "a generated walk is asking"}'
        ),
        describing="what this call sent",
    )
    equal(answered, answer, describing="what this call answered")


def test_set_feedrate_factor_surfaces_the_policys_own_refusal() -> None:
    """`set_feedrate_factor` surfaces the policy's own refusal, typed."""
    refusal = json.loads(
        '{"intervention": {"action_id": "0198f0a1-2b3c-7d4e-8f90-1234'
        '56789abc", "adjustable": "0198f0a1-2b3c-7d4e-8f90-123456789a'
        'bc", "applied_at": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "'
        'applied_value": 1.5, "expires_at": "0198f0a1-2b3c-7d4e-8f90-'
        '123456789abc", "id": "0198f0a1-2b3c-7d4e-8f90-123456789abc",'
        ' "outcome": "still_active", "print_id": "0198f0a1-2b3c-7d4e-'
        '8f90-123456789abc", "prior_value": 1.5, "restored_at": "0198'
        'f0a1-2b3c-7d4e-8f90-123456789abc"}, "printer_refusal": "0198'
        'f0a1-2b3c-7d4e-8f90-123456789abc", "record": {"decision": {"'
        'rejected": {"out_of_bounds": {"adjustable": "0198f0a1-2b3c-7'
        'd4e-8f90-123456789abc", "allowed": {"max": 1.25, "min": 0.5}'
        ', "requested": 1.5}}}, "executed_at": "0198f0a1-2b3c-7d4e-8f'
        '90-123456789abc", "id": "0198f0a1-2b3c-7d4e-8f90-123456789ab'
        'c", "outcome": "succeeded", "print_id": "0198f0a1-2b3c-7d4e-'
        '8f90-123456789abc", "request": {"action": {"action": "pause"'
        ', "actor": {"agent": {"session_name": "0198f0a1-2b3c-7d4e-8f'
        '90-123456789abc"}}, "reason": "0198f0a1-2b3c-7d4e-8f90-12345'
        '6789abc"}, "actor": {"agent": {"session_name": "0198f0a1-2b3'
        'c-7d4e-8f90-123456789abc"}}, "requested_at": "0198f0a1-2b3c-'
        '7d4e-8f90-123456789abc"}}}'
    )

    with Host(409, refusal) as host:
        client = Client(host.address, ACTOR)
        try:
            client.set_feedrate_factor(
                "0198f0a1-2b3c-7d4e-8f90-123456789abc", 1.5, "a generated walk is asking", 7
            )
        except RejectedError as refused:
            equal(refused.requested, 1.5)
            equal(refused.allowed, {"min": 0.5, "max": 1.25})
            truth(
                isinstance(refused.reason, dict) and "out_of_bounds" in refused.reason,
                describing="the refusal itself to be carried",
            )
        else:
            truth(False, describing="the policy's refusal to arrive as one")


def test_set_feedrate_factor_makes_no_request_when_the_reason_is_empty() -> None:
    """`set_feedrate_factor` refuses a call with no reason before it is made."""
    with Host(200, {}) as host:
        client = Client(host.address, ACTOR)
        try:
            client.set_feedrate_factor("0198f0a1-2b3c-7d4e-8f90-123456789abc", 1.5, "", 7)
        except NoReasonError:
            pass
        else:
            truth(False, describing="an absent reason to be refused")

        equal(host.requests(), 0, describing="what an absent reason sent")
    with Host(200, {}) as host:
        client = Client(host.address, ACTOR)
        try:
            client.set_feedrate_factor("0198f0a1-2b3c-7d4e-8f90-123456789abc", 1.5, "   ", 7)
        except NoReasonError:
            pass
        else:
            truth(False, describing="a blank reason to be refused")

        equal(host.requests(), 0, describing="what a blank reason sent")


def test_set_flowrate_factor_sends_what_it_declares_and_answers_what_was_sent() -> None:
    """`set_flowrate_factor` sends what it declares and answers what the server sent."""
    answer = json.loads(
        '{"intervention": {"action_id": "0198f0a1-2b3c-7d4e-8f90-1234'
        '56789abc", "adjustable": "0198f0a1-2b3c-7d4e-8f90-123456789a'
        'bc", "applied_at": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "'
        'applied_value": 1.5, "expires_at": "0198f0a1-2b3c-7d4e-8f90-'
        '123456789abc", "id": "0198f0a1-2b3c-7d4e-8f90-123456789abc",'
        ' "outcome": "still_active", "print_id": "0198f0a1-2b3c-7d4e-'
        '8f90-123456789abc", "prior_value": 1.5, "restored_at": "0198'
        'f0a1-2b3c-7d4e-8f90-123456789abc"}, "printer_refusal": "0198'
        'f0a1-2b3c-7d4e-8f90-123456789abc", "record": {"decision": "a'
        'ccepted", "executed_at": "0198f0a1-2b3c-7d4e-8f90-123456789a'
        'bc", "id": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "outcome"'
        ': "succeeded", "print_id": "0198f0a1-2b3c-7d4e-8f90-12345678'
        '9abc", "request": {"action": {"action": "pause", "actor": {"'
        'agent": {"session_name": "0198f0a1-2b3c-7d4e-8f90-123456789a'
        'bc"}}, "reason": "0198f0a1-2b3c-7d4e-8f90-123456789abc"}, "a'
        'ctor": {"agent": {"session_name": "0198f0a1-2b3c-7d4e-8f90-1'
        '23456789abc"}}, "requested_at": "0198f0a1-2b3c-7d4e-8f90-123'
        '456789abc"}}}'
    )

    with Host(200, answer) as host:
        client = Client(host.address, ACTOR)
        answered = client.set_flowrate_factor(
            "0198f0a1-2b3c-7d4e-8f90-123456789abc", 1.5, "a generated walk is asking", 7
        )
        received = host.received()

    equal(received.method, "POST")
    equal(
        received.target,
        "/v1/prints/0198f0a1-2b3c-7d4e-8f90-123456789abc/actions/set_flowrate_factor",
    )
    equal(
        json.loads(received.body),
        json.loads(
            '{"actor": {"agent": {"session_name": "0198f0a1-2b3c-7d4e-8f9'
            '0-123456789abc"}}, "duration_s": 7, "factor": 1.5, "reason":'
            ' "a generated walk is asking"}'
        ),
        describing="what this call sent",
    )
    equal(answered, answer, describing="what this call answered")


def test_set_flowrate_factor_surfaces_the_policys_own_refusal() -> None:
    """`set_flowrate_factor` surfaces the policy's own refusal, typed."""
    refusal = json.loads(
        '{"intervention": {"action_id": "0198f0a1-2b3c-7d4e-8f90-1234'
        '56789abc", "adjustable": "0198f0a1-2b3c-7d4e-8f90-123456789a'
        'bc", "applied_at": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "'
        'applied_value": 1.5, "expires_at": "0198f0a1-2b3c-7d4e-8f90-'
        '123456789abc", "id": "0198f0a1-2b3c-7d4e-8f90-123456789abc",'
        ' "outcome": "still_active", "print_id": "0198f0a1-2b3c-7d4e-'
        '8f90-123456789abc", "prior_value": 1.5, "restored_at": "0198'
        'f0a1-2b3c-7d4e-8f90-123456789abc"}, "printer_refusal": "0198'
        'f0a1-2b3c-7d4e-8f90-123456789abc", "record": {"decision": {"'
        'rejected": {"out_of_bounds": {"adjustable": "0198f0a1-2b3c-7'
        'd4e-8f90-123456789abc", "allowed": {"max": 1.25, "min": 0.5}'
        ', "requested": 1.5}}}, "executed_at": "0198f0a1-2b3c-7d4e-8f'
        '90-123456789abc", "id": "0198f0a1-2b3c-7d4e-8f90-123456789ab'
        'c", "outcome": "succeeded", "print_id": "0198f0a1-2b3c-7d4e-'
        '8f90-123456789abc", "request": {"action": {"action": "pause"'
        ', "actor": {"agent": {"session_name": "0198f0a1-2b3c-7d4e-8f'
        '90-123456789abc"}}, "reason": "0198f0a1-2b3c-7d4e-8f90-12345'
        '6789abc"}, "actor": {"agent": {"session_name": "0198f0a1-2b3'
        'c-7d4e-8f90-123456789abc"}}, "requested_at": "0198f0a1-2b3c-'
        '7d4e-8f90-123456789abc"}}}'
    )

    with Host(409, refusal) as host:
        client = Client(host.address, ACTOR)
        try:
            client.set_flowrate_factor(
                "0198f0a1-2b3c-7d4e-8f90-123456789abc", 1.5, "a generated walk is asking", 7
            )
        except RejectedError as refused:
            equal(refused.requested, 1.5)
            equal(refused.allowed, {"min": 0.5, "max": 1.25})
            truth(
                isinstance(refused.reason, dict) and "out_of_bounds" in refused.reason,
                describing="the refusal itself to be carried",
            )
        else:
            truth(False, describing="the policy's refusal to arrive as one")


def test_set_flowrate_factor_makes_no_request_when_the_reason_is_empty() -> None:
    """`set_flowrate_factor` refuses a call with no reason before it is made."""
    with Host(200, {}) as host:
        client = Client(host.address, ACTOR)
        try:
            client.set_flowrate_factor("0198f0a1-2b3c-7d4e-8f90-123456789abc", 1.5, "", 7)
        except NoReasonError:
            pass
        else:
            truth(False, describing="an absent reason to be refused")

        equal(host.requests(), 0, describing="what an absent reason sent")
    with Host(200, {}) as host:
        client = Client(host.address, ACTOR)
        try:
            client.set_flowrate_factor("0198f0a1-2b3c-7d4e-8f90-123456789abc", 1.5, "   ", 7)
        except NoReasonError:
            pass
        else:
            truth(False, describing="a blank reason to be refused")

        equal(host.requests(), 0, describing="what a blank reason sent")


def test_set_tool_target_c_sends_what_it_declares_and_answers_what_was_sent() -> None:
    """`set_tool_target_c` sends what it declares and answers what the server sent."""
    answer = json.loads(
        '{"intervention": {"action_id": "0198f0a1-2b3c-7d4e-8f90-1234'
        '56789abc", "adjustable": "0198f0a1-2b3c-7d4e-8f90-123456789a'
        'bc", "applied_at": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "'
        'applied_value": 1.5, "expires_at": "0198f0a1-2b3c-7d4e-8f90-'
        '123456789abc", "id": "0198f0a1-2b3c-7d4e-8f90-123456789abc",'
        ' "outcome": "still_active", "print_id": "0198f0a1-2b3c-7d4e-'
        '8f90-123456789abc", "prior_value": 1.5, "restored_at": "0198'
        'f0a1-2b3c-7d4e-8f90-123456789abc"}, "printer_refusal": "0198'
        'f0a1-2b3c-7d4e-8f90-123456789abc", "record": {"decision": "a'
        'ccepted", "executed_at": "0198f0a1-2b3c-7d4e-8f90-123456789a'
        'bc", "id": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "outcome"'
        ': "succeeded", "print_id": "0198f0a1-2b3c-7d4e-8f90-12345678'
        '9abc", "request": {"action": {"action": "pause", "actor": {"'
        'agent": {"session_name": "0198f0a1-2b3c-7d4e-8f90-123456789a'
        'bc"}}, "reason": "0198f0a1-2b3c-7d4e-8f90-123456789abc"}, "a'
        'ctor": {"agent": {"session_name": "0198f0a1-2b3c-7d4e-8f90-1'
        '23456789abc"}}, "requested_at": "0198f0a1-2b3c-7d4e-8f90-123'
        '456789abc"}}}'
    )

    with Host(200, answer) as host:
        client = Client(host.address, ACTOR)
        answered = client.set_tool_target_c(
            "0198f0a1-2b3c-7d4e-8f90-123456789abc", "a generated walk is asking", 1.5, 7, 7
        )
        received = host.received()

    equal(received.method, "POST")
    equal(
        received.target, "/v1/prints/0198f0a1-2b3c-7d4e-8f90-123456789abc/actions/set_tool_target_c"
    )
    equal(
        json.loads(received.body),
        json.loads(
            '{"actor": {"agent": {"session_name": "0198f0a1-2b3c-7d4e-8f9'
            '0-123456789abc"}}, "duration_s": 7, "reason": "a generated w'
            'alk is asking", "target_c": 1.5, "tool": 7}'
        ),
        describing="what this call sent",
    )
    equal(answered, answer, describing="what this call answered")


def test_set_tool_target_c_surfaces_the_policys_own_refusal() -> None:
    """`set_tool_target_c` surfaces the policy's own refusal, typed."""
    refusal = json.loads(
        '{"intervention": {"action_id": "0198f0a1-2b3c-7d4e-8f90-1234'
        '56789abc", "adjustable": "0198f0a1-2b3c-7d4e-8f90-123456789a'
        'bc", "applied_at": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "'
        'applied_value": 1.5, "expires_at": "0198f0a1-2b3c-7d4e-8f90-'
        '123456789abc", "id": "0198f0a1-2b3c-7d4e-8f90-123456789abc",'
        ' "outcome": "still_active", "print_id": "0198f0a1-2b3c-7d4e-'
        '8f90-123456789abc", "prior_value": 1.5, "restored_at": "0198'
        'f0a1-2b3c-7d4e-8f90-123456789abc"}, "printer_refusal": "0198'
        'f0a1-2b3c-7d4e-8f90-123456789abc", "record": {"decision": {"'
        'rejected": {"out_of_bounds": {"adjustable": "0198f0a1-2b3c-7'
        'd4e-8f90-123456789abc", "allowed": {"max": 1.25, "min": 0.5}'
        ', "requested": 1.5}}}, "executed_at": "0198f0a1-2b3c-7d4e-8f'
        '90-123456789abc", "id": "0198f0a1-2b3c-7d4e-8f90-123456789ab'
        'c", "outcome": "succeeded", "print_id": "0198f0a1-2b3c-7d4e-'
        '8f90-123456789abc", "request": {"action": {"action": "pause"'
        ', "actor": {"agent": {"session_name": "0198f0a1-2b3c-7d4e-8f'
        '90-123456789abc"}}, "reason": "0198f0a1-2b3c-7d4e-8f90-12345'
        '6789abc"}, "actor": {"agent": {"session_name": "0198f0a1-2b3'
        'c-7d4e-8f90-123456789abc"}}, "requested_at": "0198f0a1-2b3c-'
        '7d4e-8f90-123456789abc"}}}'
    )

    with Host(409, refusal) as host:
        client = Client(host.address, ACTOR)
        try:
            client.set_tool_target_c(
                "0198f0a1-2b3c-7d4e-8f90-123456789abc", "a generated walk is asking", 1.5, 7, 7
            )
        except RejectedError as refused:
            equal(refused.requested, 1.5)
            equal(refused.allowed, {"min": 0.5, "max": 1.25})
            truth(
                isinstance(refused.reason, dict) and "out_of_bounds" in refused.reason,
                describing="the refusal itself to be carried",
            )
        else:
            truth(False, describing="the policy's refusal to arrive as one")


def test_set_tool_target_c_makes_no_request_when_the_reason_is_empty() -> None:
    """`set_tool_target_c` refuses a call with no reason before it is made."""
    with Host(200, {}) as host:
        client = Client(host.address, ACTOR)
        try:
            client.set_tool_target_c("0198f0a1-2b3c-7d4e-8f90-123456789abc", "", 1.5, 7, 7)
        except NoReasonError:
            pass
        else:
            truth(False, describing="an absent reason to be refused")

        equal(host.requests(), 0, describing="what an absent reason sent")
    with Host(200, {}) as host:
        client = Client(host.address, ACTOR)
        try:
            client.set_tool_target_c("0198f0a1-2b3c-7d4e-8f90-123456789abc", "   ", 1.5, 7, 7)
        except NoReasonError:
            pass
        else:
            truth(False, describing="a blank reason to be refused")

        equal(host.requests(), 0, describing="what a blank reason sent")


def test_set_bed_target_c_sends_what_it_declares_and_answers_what_was_sent() -> None:
    """`set_bed_target_c` sends what it declares and answers what the server sent."""
    answer = json.loads(
        '{"intervention": {"action_id": "0198f0a1-2b3c-7d4e-8f90-1234'
        '56789abc", "adjustable": "0198f0a1-2b3c-7d4e-8f90-123456789a'
        'bc", "applied_at": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "'
        'applied_value": 1.5, "expires_at": "0198f0a1-2b3c-7d4e-8f90-'
        '123456789abc", "id": "0198f0a1-2b3c-7d4e-8f90-123456789abc",'
        ' "outcome": "still_active", "print_id": "0198f0a1-2b3c-7d4e-'
        '8f90-123456789abc", "prior_value": 1.5, "restored_at": "0198'
        'f0a1-2b3c-7d4e-8f90-123456789abc"}, "printer_refusal": "0198'
        'f0a1-2b3c-7d4e-8f90-123456789abc", "record": {"decision": "a'
        'ccepted", "executed_at": "0198f0a1-2b3c-7d4e-8f90-123456789a'
        'bc", "id": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "outcome"'
        ': "succeeded", "print_id": "0198f0a1-2b3c-7d4e-8f90-12345678'
        '9abc", "request": {"action": {"action": "pause", "actor": {"'
        'agent": {"session_name": "0198f0a1-2b3c-7d4e-8f90-123456789a'
        'bc"}}, "reason": "0198f0a1-2b3c-7d4e-8f90-123456789abc"}, "a'
        'ctor": {"agent": {"session_name": "0198f0a1-2b3c-7d4e-8f90-1'
        '23456789abc"}}, "requested_at": "0198f0a1-2b3c-7d4e-8f90-123'
        '456789abc"}}}'
    )

    with Host(200, answer) as host:
        client = Client(host.address, ACTOR)
        answered = client.set_bed_target_c(
            "0198f0a1-2b3c-7d4e-8f90-123456789abc", "a generated walk is asking", 1.5, 7
        )
        received = host.received()

    equal(received.method, "POST")
    equal(
        received.target, "/v1/prints/0198f0a1-2b3c-7d4e-8f90-123456789abc/actions/set_bed_target_c"
    )
    equal(
        json.loads(received.body),
        json.loads(
            '{"actor": {"agent": {"session_name": "0198f0a1-2b3c-7d4e-8f9'
            '0-123456789abc"}}, "duration_s": 7, "reason": "a generated w'
            'alk is asking", "target_c": 1.5}'
        ),
        describing="what this call sent",
    )
    equal(answered, answer, describing="what this call answered")


def test_set_bed_target_c_surfaces_the_policys_own_refusal() -> None:
    """`set_bed_target_c` surfaces the policy's own refusal, typed."""
    refusal = json.loads(
        '{"intervention": {"action_id": "0198f0a1-2b3c-7d4e-8f90-1234'
        '56789abc", "adjustable": "0198f0a1-2b3c-7d4e-8f90-123456789a'
        'bc", "applied_at": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "'
        'applied_value": 1.5, "expires_at": "0198f0a1-2b3c-7d4e-8f90-'
        '123456789abc", "id": "0198f0a1-2b3c-7d4e-8f90-123456789abc",'
        ' "outcome": "still_active", "print_id": "0198f0a1-2b3c-7d4e-'
        '8f90-123456789abc", "prior_value": 1.5, "restored_at": "0198'
        'f0a1-2b3c-7d4e-8f90-123456789abc"}, "printer_refusal": "0198'
        'f0a1-2b3c-7d4e-8f90-123456789abc", "record": {"decision": {"'
        'rejected": {"out_of_bounds": {"adjustable": "0198f0a1-2b3c-7'
        'd4e-8f90-123456789abc", "allowed": {"max": 1.25, "min": 0.5}'
        ', "requested": 1.5}}}, "executed_at": "0198f0a1-2b3c-7d4e-8f'
        '90-123456789abc", "id": "0198f0a1-2b3c-7d4e-8f90-123456789ab'
        'c", "outcome": "succeeded", "print_id": "0198f0a1-2b3c-7d4e-'
        '8f90-123456789abc", "request": {"action": {"action": "pause"'
        ', "actor": {"agent": {"session_name": "0198f0a1-2b3c-7d4e-8f'
        '90-123456789abc"}}, "reason": "0198f0a1-2b3c-7d4e-8f90-12345'
        '6789abc"}, "actor": {"agent": {"session_name": "0198f0a1-2b3'
        'c-7d4e-8f90-123456789abc"}}, "requested_at": "0198f0a1-2b3c-'
        '7d4e-8f90-123456789abc"}}}'
    )

    with Host(409, refusal) as host:
        client = Client(host.address, ACTOR)
        try:
            client.set_bed_target_c(
                "0198f0a1-2b3c-7d4e-8f90-123456789abc", "a generated walk is asking", 1.5, 7
            )
        except RejectedError as refused:
            equal(refused.requested, 1.5)
            equal(refused.allowed, {"min": 0.5, "max": 1.25})
            truth(
                isinstance(refused.reason, dict) and "out_of_bounds" in refused.reason,
                describing="the refusal itself to be carried",
            )
        else:
            truth(False, describing="the policy's refusal to arrive as one")


def test_set_bed_target_c_makes_no_request_when_the_reason_is_empty() -> None:
    """`set_bed_target_c` refuses a call with no reason before it is made."""
    with Host(200, {}) as host:
        client = Client(host.address, ACTOR)
        try:
            client.set_bed_target_c("0198f0a1-2b3c-7d4e-8f90-123456789abc", "", 1.5, 7)
        except NoReasonError:
            pass
        else:
            truth(False, describing="an absent reason to be refused")

        equal(host.requests(), 0, describing="what an absent reason sent")
    with Host(200, {}) as host:
        client = Client(host.address, ACTOR)
        try:
            client.set_bed_target_c("0198f0a1-2b3c-7d4e-8f90-123456789abc", "   ", 1.5, 7)
        except NoReasonError:
            pass
        else:
            truth(False, describing="a blank reason to be refused")

        equal(host.requests(), 0, describing="what a blank reason sent")


def test_set_fan_percent_sends_what_it_declares_and_answers_what_was_sent() -> None:
    """`set_fan_percent` sends what it declares and answers what the server sent."""
    answer = json.loads(
        '{"intervention": {"action_id": "0198f0a1-2b3c-7d4e-8f90-1234'
        '56789abc", "adjustable": "0198f0a1-2b3c-7d4e-8f90-123456789a'
        'bc", "applied_at": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "'
        'applied_value": 1.5, "expires_at": "0198f0a1-2b3c-7d4e-8f90-'
        '123456789abc", "id": "0198f0a1-2b3c-7d4e-8f90-123456789abc",'
        ' "outcome": "still_active", "print_id": "0198f0a1-2b3c-7d4e-'
        '8f90-123456789abc", "prior_value": 1.5, "restored_at": "0198'
        'f0a1-2b3c-7d4e-8f90-123456789abc"}, "printer_refusal": "0198'
        'f0a1-2b3c-7d4e-8f90-123456789abc", "record": {"decision": "a'
        'ccepted", "executed_at": "0198f0a1-2b3c-7d4e-8f90-123456789a'
        'bc", "id": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "outcome"'
        ': "succeeded", "print_id": "0198f0a1-2b3c-7d4e-8f90-12345678'
        '9abc", "request": {"action": {"action": "pause", "actor": {"'
        'agent": {"session_name": "0198f0a1-2b3c-7d4e-8f90-123456789a'
        'bc"}}, "reason": "0198f0a1-2b3c-7d4e-8f90-123456789abc"}, "a'
        'ctor": {"agent": {"session_name": "0198f0a1-2b3c-7d4e-8f90-1'
        '23456789abc"}}, "requested_at": "0198f0a1-2b3c-7d4e-8f90-123'
        '456789abc"}}}'
    )

    with Host(200, answer) as host:
        client = Client(host.address, ACTOR)
        answered = client.set_fan_percent(
            "0198f0a1-2b3c-7d4e-8f90-123456789abc", 1.5, "a generated walk is asking", 7
        )
        received = host.received()

    equal(received.method, "POST")
    equal(
        received.target, "/v1/prints/0198f0a1-2b3c-7d4e-8f90-123456789abc/actions/set_fan_percent"
    )
    equal(
        json.loads(received.body),
        json.loads(
            '{"actor": {"agent": {"session_name": "0198f0a1-2b3c-7d4e-8f9'
            '0-123456789abc"}}, "duration_s": 7, "percent": 1.5, "reason"'
            ': "a generated walk is asking"}'
        ),
        describing="what this call sent",
    )
    equal(answered, answer, describing="what this call answered")


def test_set_fan_percent_surfaces_the_policys_own_refusal() -> None:
    """`set_fan_percent` surfaces the policy's own refusal, typed."""
    refusal = json.loads(
        '{"intervention": {"action_id": "0198f0a1-2b3c-7d4e-8f90-1234'
        '56789abc", "adjustable": "0198f0a1-2b3c-7d4e-8f90-123456789a'
        'bc", "applied_at": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "'
        'applied_value": 1.5, "expires_at": "0198f0a1-2b3c-7d4e-8f90-'
        '123456789abc", "id": "0198f0a1-2b3c-7d4e-8f90-123456789abc",'
        ' "outcome": "still_active", "print_id": "0198f0a1-2b3c-7d4e-'
        '8f90-123456789abc", "prior_value": 1.5, "restored_at": "0198'
        'f0a1-2b3c-7d4e-8f90-123456789abc"}, "printer_refusal": "0198'
        'f0a1-2b3c-7d4e-8f90-123456789abc", "record": {"decision": {"'
        'rejected": {"out_of_bounds": {"adjustable": "0198f0a1-2b3c-7'
        'd4e-8f90-123456789abc", "allowed": {"max": 1.25, "min": 0.5}'
        ', "requested": 1.5}}}, "executed_at": "0198f0a1-2b3c-7d4e-8f'
        '90-123456789abc", "id": "0198f0a1-2b3c-7d4e-8f90-123456789ab'
        'c", "outcome": "succeeded", "print_id": "0198f0a1-2b3c-7d4e-'
        '8f90-123456789abc", "request": {"action": {"action": "pause"'
        ', "actor": {"agent": {"session_name": "0198f0a1-2b3c-7d4e-8f'
        '90-123456789abc"}}, "reason": "0198f0a1-2b3c-7d4e-8f90-12345'
        '6789abc"}, "actor": {"agent": {"session_name": "0198f0a1-2b3'
        'c-7d4e-8f90-123456789abc"}}, "requested_at": "0198f0a1-2b3c-'
        '7d4e-8f90-123456789abc"}}}'
    )

    with Host(409, refusal) as host:
        client = Client(host.address, ACTOR)
        try:
            client.set_fan_percent(
                "0198f0a1-2b3c-7d4e-8f90-123456789abc", 1.5, "a generated walk is asking", 7
            )
        except RejectedError as refused:
            equal(refused.requested, 1.5)
            equal(refused.allowed, {"min": 0.5, "max": 1.25})
            truth(
                isinstance(refused.reason, dict) and "out_of_bounds" in refused.reason,
                describing="the refusal itself to be carried",
            )
        else:
            truth(False, describing="the policy's refusal to arrive as one")


def test_set_fan_percent_makes_no_request_when_the_reason_is_empty() -> None:
    """`set_fan_percent` refuses a call with no reason before it is made."""
    with Host(200, {}) as host:
        client = Client(host.address, ACTOR)
        try:
            client.set_fan_percent("0198f0a1-2b3c-7d4e-8f90-123456789abc", 1.5, "", 7)
        except NoReasonError:
            pass
        else:
            truth(False, describing="an absent reason to be refused")

        equal(host.requests(), 0, describing="what an absent reason sent")
    with Host(200, {}) as host:
        client = Client(host.address, ACTOR)
        try:
            client.set_fan_percent("0198f0a1-2b3c-7d4e-8f90-123456789abc", 1.5, "   ", 7)
        except NoReasonError:
            pass
        else:
            truth(False, describing="a blank reason to be refused")

        equal(host.requests(), 0, describing="what a blank reason sent")


def test_acknowledge_failure_sends_what_it_declares_and_answers_what_was_sent() -> None:
    """`acknowledge_failure` sends what it declares and answers what the server sent."""
    answer = json.loads(
        '{"intervention": {"action_id": "0198f0a1-2b3c-7d4e-8f90-1234'
        '56789abc", "adjustable": "0198f0a1-2b3c-7d4e-8f90-123456789a'
        'bc", "applied_at": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "'
        'applied_value": 1.5, "expires_at": "0198f0a1-2b3c-7d4e-8f90-'
        '123456789abc", "id": "0198f0a1-2b3c-7d4e-8f90-123456789abc",'
        ' "outcome": "still_active", "print_id": "0198f0a1-2b3c-7d4e-'
        '8f90-123456789abc", "prior_value": 1.5, "restored_at": "0198'
        'f0a1-2b3c-7d4e-8f90-123456789abc"}, "printer_refusal": "0198'
        'f0a1-2b3c-7d4e-8f90-123456789abc", "record": {"decision": "a'
        'ccepted", "executed_at": "0198f0a1-2b3c-7d4e-8f90-123456789a'
        'bc", "id": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "outcome"'
        ': "succeeded", "print_id": "0198f0a1-2b3c-7d4e-8f90-12345678'
        '9abc", "request": {"action": {"action": "pause", "actor": {"'
        'agent": {"session_name": "0198f0a1-2b3c-7d4e-8f90-123456789a'
        'bc"}}, "reason": "0198f0a1-2b3c-7d4e-8f90-123456789abc"}, "a'
        'ctor": {"agent": {"session_name": "0198f0a1-2b3c-7d4e-8f90-1'
        '23456789abc"}}, "requested_at": "0198f0a1-2b3c-7d4e-8f90-123'
        '456789abc"}}}'
    )

    with Host(200, answer) as host:
        client = Client(host.address, ACTOR)
        answered = client.acknowledge_failure(
            "0198f0a1-2b3c-7d4e-8f90-123456789abc",
            cast(AcknowledgementDisposition, json.loads('"continue"')),
            cast(EventId, json.loads('"0198f0a1-2b3c-7d4e-8f90-123456789abc"')),
            "a generated walk is asking",
        )
        received = host.received()

    equal(received.method, "POST")
    equal(
        received.target,
        "/v1/prints/0198f0a1-2b3c-7d4e-8f90-123456789abc/actions/acknowledge_failure",
    )
    equal(
        json.loads(received.body),
        json.loads(
            '{"actor": {"agent": {"session_name": "0198f0a1-2b3c-7d4e-8f9'
            '0-123456789abc"}}, "disposition": "continue", "event_id": "0'
            '198f0a1-2b3c-7d4e-8f90-123456789abc", "reason": "a generated'
            ' walk is asking"}'
        ),
        describing="what this call sent",
    )
    equal(answered, answer, describing="what this call answered")


def test_acknowledge_failure_surfaces_the_policys_own_refusal() -> None:
    """`acknowledge_failure` surfaces the policy's own refusal, typed."""
    refusal = json.loads(
        '{"intervention": {"action_id": "0198f0a1-2b3c-7d4e-8f90-1234'
        '56789abc", "adjustable": "0198f0a1-2b3c-7d4e-8f90-123456789a'
        'bc", "applied_at": "0198f0a1-2b3c-7d4e-8f90-123456789abc", "'
        'applied_value": 1.5, "expires_at": "0198f0a1-2b3c-7d4e-8f90-'
        '123456789abc", "id": "0198f0a1-2b3c-7d4e-8f90-123456789abc",'
        ' "outcome": "still_active", "print_id": "0198f0a1-2b3c-7d4e-'
        '8f90-123456789abc", "prior_value": 1.5, "restored_at": "0198'
        'f0a1-2b3c-7d4e-8f90-123456789abc"}, "printer_refusal": "0198'
        'f0a1-2b3c-7d4e-8f90-123456789abc", "record": {"decision": {"'
        'rejected": {"out_of_bounds": {"adjustable": "0198f0a1-2b3c-7'
        'd4e-8f90-123456789abc", "allowed": {"max": 1.25, "min": 0.5}'
        ', "requested": 1.5}}}, "executed_at": "0198f0a1-2b3c-7d4e-8f'
        '90-123456789abc", "id": "0198f0a1-2b3c-7d4e-8f90-123456789ab'
        'c", "outcome": "succeeded", "print_id": "0198f0a1-2b3c-7d4e-'
        '8f90-123456789abc", "request": {"action": {"action": "pause"'
        ', "actor": {"agent": {"session_name": "0198f0a1-2b3c-7d4e-8f'
        '90-123456789abc"}}, "reason": "0198f0a1-2b3c-7d4e-8f90-12345'
        '6789abc"}, "actor": {"agent": {"session_name": "0198f0a1-2b3'
        'c-7d4e-8f90-123456789abc"}}, "requested_at": "0198f0a1-2b3c-'
        '7d4e-8f90-123456789abc"}}}'
    )

    with Host(409, refusal) as host:
        client = Client(host.address, ACTOR)
        try:
            client.acknowledge_failure(
                "0198f0a1-2b3c-7d4e-8f90-123456789abc",
                cast(AcknowledgementDisposition, json.loads('"continue"')),
                cast(EventId, json.loads('"0198f0a1-2b3c-7d4e-8f90-123456789abc"')),
                "a generated walk is asking",
            )
        except RejectedError as refused:
            equal(refused.requested, 1.5)
            equal(refused.allowed, {"min": 0.5, "max": 1.25})
            truth(
                isinstance(refused.reason, dict) and "out_of_bounds" in refused.reason,
                describing="the refusal itself to be carried",
            )
        else:
            truth(False, describing="the policy's refusal to arrive as one")


def test_acknowledge_failure_makes_no_request_when_the_reason_is_empty() -> None:
    """`acknowledge_failure` refuses a call with no reason before it is made."""
    with Host(200, {}) as host:
        client = Client(host.address, ACTOR)
        try:
            client.acknowledge_failure(
                "0198f0a1-2b3c-7d4e-8f90-123456789abc",
                cast(AcknowledgementDisposition, json.loads('"continue"')),
                cast(EventId, json.loads('"0198f0a1-2b3c-7d4e-8f90-123456789abc"')),
                "",
            )
        except NoReasonError:
            pass
        else:
            truth(False, describing="an absent reason to be refused")

        equal(host.requests(), 0, describing="what an absent reason sent")
    with Host(200, {}) as host:
        client = Client(host.address, ACTOR)
        try:
            client.acknowledge_failure(
                "0198f0a1-2b3c-7d4e-8f90-123456789abc",
                cast(AcknowledgementDisposition, json.loads('"continue"')),
                cast(EventId, json.loads('"0198f0a1-2b3c-7d4e-8f90-123456789abc"')),
                "   ",
            )
        except NoReasonError:
            pass
        else:
            truth(False, describing="a blank reason to be refused")

        equal(host.requests(), 0, describing="what a blank reason sent")
