"""Generated by `contract-codegen` from the checked-in contract schemas.

This file is the Python client's request and response types.

Do not edit by hand: change the contracts, regenerate with `just
generate-clients`, and commit what that writes.
"""

from __future__ import annotations

from typing import Literal, NotRequired, TypedDict, cast

from printobserver_sdk._surface import GeneratedSurface, reason_given

# The version of the server contract these types were generated from, which
# is the version the type crate declares in the tree they came from.
CONTRACT_VERSION = "0.1.0"

# Every operation this client exposes a method for, which is every operation
# the server declares and no other.
OPERATION_NAMES: tuple[str, ...] = (
    "status",
    "context",
    "image",
    "history",
    "manifest_get",
    "manifest_set",
    "pause",
    "resume",
    "cancel",
    "start_print",
    "set_feedrate_factor",
    "set_flowrate_factor",
    "set_tool_target_c",
    "set_bed_target_c",
    "set_fan_percent",
    "acknowledge_failure",
)


# What an operator's acknowledgement of a failure event asks for next.
type AcknowledgementDisposition = Literal["continue", "watch", "stop"]


class ActionAnswer(TypedDict):
    """`ActionAnswer`, as the contracts declare it.

    What one mutating request left behind it.
    """

    # The bounded intervention it opened, when it opened one.
    intervention: NotRequired[Intervention | None]
    # What the printer said, when the request reached it and it refused.
    printer_refusal: NotRequired[str | None]
    # The record of the request and the decision taken on it. A rejected
    # request's rejection is here, carrying its reason, the value asked for
    # and the range allowed, so a caller can ask again inside the range.
    record: ActionRecord


class ActionExecutedPayload(TypedDict):
    """`ActionExecutedPayload`, as the contracts declare it.

    An accepted action reached the printer.
    """

    # The action's identifier.
    action_id: ActionId
    # The bounded intervention it opened, when it opened one.
    intervention_id: NotRequired[InterventionId | None]


# A lowercase hyphenated version 7 UUID identifying one requested action.
type ActionId = str


# One action of the closed vocabulary, named without its payload.
#
# This is what a safety envelope grants and what a policy rejection names;
# the
# payload lives on `PrintAction` itself.
type ActionKind = Literal[
    "pause",
    "resume",
    "cancel",
    "start_print",
    "set_feedrate_factor",
    "set_flowrate_factor",
    "set_tool_target_c",
    "set_bed_target_c",
    "set_fan_percent",
    "acknowledge_failure",
]


class ActionRecord(TypedDict):
    """`ActionRecord`, as the contracts declare it.

    One request, the decision taken on it, and what became of it.

    `executed_at` and `outcome` are both optional and are absent together:
    a
    record is written when the decision is taken, which is before — and,
    for a
    rejected request, instead of — anything reaching the printer.
    """

    # The decision policy took on it.
    decision: PolicyDecision
    # When it reached the printer, if it did.
    executed_at: NotRequired[Timestamp | None]
    # This record's identifier, minted by the store.
    id: ActionId
    # What the printer made of it, if it reached the printer.
    outcome: NotRequired[ExecutionOutcome | None]
    # The print this request was made against.
    print_id: PrintId
    # The request itself.
    request: ActionRequest


class ActionRejectedPayload(TypedDict):
    """`ActionRejectedPayload`, as the contracts declare it.

    Policy refused an action.
    """

    # The action's identifier.
    action_id: ActionId
    # The whole decision, carrying which rejection it was.
    decision: PolicyDecision


class ActionRequest(TypedDict):
    """`ActionRequest`, as the contracts declare it.

    One request an actor made, at the instant it made it.
    """

    # What was asked for.
    action: PrintAction
    # Who asked.
    actor: Actor
    # When they asked.
    requested_at: Timestamp


class ActionRequestedPayload(TypedDict):
    """`ActionRequestedPayload`, as the contracts declare it.

    An actor asked for an action.
    """

    # What was asked for.
    action: PrintAction
    # The action's identifier.
    action_id: ActionId
    # Who asked.
    actor: Actor


class ActorAgentPayload(TypedDict):
    """What the `agent` arm of `Actor` carries.

    The supervising agent, naming its session.
    """

    # The supervision session the agent is acting in.
    session_name: str


class ActorAgent(TypedDict):
    """The `agent` arm of `Actor`.

    The supervising agent, naming its session.
    """

    agent: ActorAgentPayload


# Who asked for something.
type Actor = ActorAgent | Literal["operator", "system"]


# An actor class, which is what a safety envelope grants actions to.
type ActorClass = Literal["agent", "operator", "system"]


# One thing an adjustment may change.
type Adjustable = str


class AgentAssessment(TypedDict):
    """`AgentAssessment`, as the contracts declare it.

    The agent's written record of one supervision turn.

    This is deliberately not how the agent acts: acting is a
    `PrintAction` that policy rules on.
    """

    # How sure the agent is.
    confidence: Confidence
    # What the agent did.
    did: str
    # Whether the agent is escalating to a person.
    escalating: bool
    # Whether the print should carry on.
    should_continue: bool
    # One line saying what is happening.
    summary: str
    # Why it did it.
    why: str


class AgentAssessmentPayload(TypedDict):
    """`AgentAssessmentPayload`, as the contracts declare it.

    The agent wrote down what it made of a turn.
    """

    # What the agent answered with.
    assessment: AgentAssessment
    # The session the turn ran in.
    session_name: str


# How sure the agent is.
#
# A closed vocabulary rather than a number, because a number invites a
# precision the agent does not have.
type Confidence = Literal["low", "medium", "high"]


class ContextAnswer(TypedDict):
    """`ContextAnswer`, as the contracts declare it.

    What a context read answers.

    The latest image is **materialized** here rather than left as the
    handle
    `PrintContext` carries: the one thing a supervision turn does with an
    image is look at it, and a handle is not something anything can open.
    The
    path is absolute on this server's own filesystem, exactly as
    `ImageAnswer`'s is, and is absent when there is no image or when the
    record is intact and the file is not.
    """

    # Everything a supervision turn is given about the print.
    context: PrintContext
    # Where the latest image's bytes are, absolute on this host.
    image_path: NotRequired[str | None]


class EffectiveBounds(TypedDict):
    """`EffectiveBounds`, as the contracts declare it.

    The envelope intersected with the print's manifest.

    This is what context reports, so that the agent can see its own limits
    before it asks. Computing one is the supervision core's; this crate
    declares
    the shape and nothing that produces it.
    """

    # The range each adjustable may be set to, inclusive.
    allowed: dict[str, Range]


class ErrorAnswer(TypedDict):
    """`ErrorAnswer`, as the contracts declare it.

    What this server answers when it will not do what it was asked.
    """

    # One line saying why, in the words of whatever refused it.
    error: str


# A lowercase hyphenated version 7 UUID identifying one event.
type EventId = str


class EventRecordCommon(TypedDict):
    """What every arm of `EventRecord` carries beside its own payload.

    One event, as the store holds it.

    `raw` holds the bytes exactly as received for an externally sourced
    event
    and is absent for an internally raised one — it is what makes the
    history
    auditable when a normalization turns out to be wrong. `print_id` is
    optional, because an externally sourced event may name no print this
    system
    knows.
    """

    # This event's identifier, minted by the store.
    id: EventId
    # The image it arrived with, when it arrived with one.
    image: NotRequired[ImageRef | None]
    # The print it belongs to, when it belongs to one.
    print_id: NotRequired[PrintId | None]
    # The bytes exactly as received, for an externally sourced event.
    raw: NotRequired[RawBytes | None]
    # When it was received.
    received_at: Timestamp
    # Where it came from.
    source: EventSource


class EventRecordObicoFailureAlert(EventRecordCommon):
    """The `obico_failure_alert` arm of `EventRecord`.

    Obico reported a print failure.
    """

    kind: Literal["obico_failure_alert"]
    # One shape of the contracts, which say nothing more about it.
    payload: ObicoFailureAlertPayload


class EventRecordObicoPrinterNotification(EventRecordCommon):
    """The `obico_printer_notification` arm of `EventRecord`.

    Obico sent a printer notification.
    """

    kind: Literal["obico_printer_notification"]
    # One shape of the contracts, which say nothing more about it.
    payload: ObicoPrinterNotificationPayload


class EventRecordMalformedExternalEvent(EventRecordCommon):
    """The `malformed_external_event` arm of `EventRecord`.

    An external body arrived that could not be read.
    """

    kind: Literal["malformed_external_event"]
    # One shape of the contracts, which say nothing more about it.
    payload: MalformedExternalEventPayload


class EventRecordActionRequested(EventRecordCommon):
    """The `action_requested` arm of `EventRecord`.

    An actor asked for an action.
    """

    kind: Literal["action_requested"]
    # One shape of the contracts, which say nothing more about it.
    payload: ActionRequestedPayload


class EventRecordActionExecuted(EventRecordCommon):
    """The `action_executed` arm of `EventRecord`.

    An accepted action reached the printer.
    """

    kind: Literal["action_executed"]
    # One shape of the contracts, which say nothing more about it.
    payload: ActionExecutedPayload


class EventRecordActionRejected(EventRecordCommon):
    """The `action_rejected` arm of `EventRecord`.

    Policy refused an action.
    """

    kind: Literal["action_rejected"]
    # One shape of the contracts, which say nothing more about it.
    payload: ActionRejectedPayload


class EventRecordInterventionExpired(EventRecordCommon):
    """The `intervention_expired` arm of `EventRecord`.

    A bounded intervention expired.
    """

    kind: Literal["intervention_expired"]
    # One shape of the contracts, which say nothing more about it.
    payload: InterventionExpiredPayload


class EventRecordSupervisionSessionOpened(EventRecordCommon):
    """The `supervision_session_opened` arm of `EventRecord`.

    A supervision session was opened.
    """

    kind: Literal["supervision_session_opened"]
    # One shape of the contracts, which say nothing more about it.
    payload: SupervisionSessionOpenedPayload


class EventRecordSupervisionSessionClosed(EventRecordCommon):
    """The `supervision_session_closed` arm of `EventRecord`.

    A supervision session was closed.
    """

    kind: Literal["supervision_session_closed"]
    # One shape of the contracts, which say nothing more about it.
    payload: SupervisionSessionClosedPayload


class EventRecordAgentAssessment(EventRecordCommon):
    """The `agent_assessment` arm of `EventRecord`.

    The agent wrote down what it made of a turn.
    """

    kind: Literal["agent_assessment"]
    # One shape of the contracts, which say nothing more about it.
    payload: AgentAssessmentPayload


class EventRecordOperatorAcknowledgement(EventRecordCommon):
    """The `operator_acknowledgement` arm of `EventRecord`.

    An operator acknowledged an event.
    """

    kind: Literal["operator_acknowledgement"]
    # One shape of the contracts, which say nothing more about it.
    payload: OperatorAcknowledgementPayload


class EventRecordPortFailure(EventRecordCommon):
    """The `port_failure` arm of `EventRecord`.

    A port failed while an event was being handled.
    """

    kind: Literal["port_failure"]
    # One shape of the contracts, which say nothing more about it.
    payload: PortFailurePayload


class EventRecordStartupReconciliation(EventRecordCommon):
    """The `startup_reconciliation` arm of `EventRecord`.

    A supervisor reconciled one thing the store held when it started.
    """

    kind: Literal["startup_reconciliation"]
    # One shape of the contracts, which say nothing more about it.
    payload: StartupReconciliationPayload


# EventRecord, as the contracts declare it.
type EventRecord = (
    EventRecordObicoFailureAlert
    | EventRecordObicoPrinterNotification
    | EventRecordMalformedExternalEvent
    | EventRecordActionRequested
    | EventRecordActionExecuted
    | EventRecordActionRejected
    | EventRecordInterventionExpired
    | EventRecordSupervisionSessionOpened
    | EventRecordSupervisionSessionClosed
    | EventRecordAgentAssessment
    | EventRecordOperatorAcknowledgement
    | EventRecordPortFailure
    | EventRecordStartupReconciliation
)


# Where an event came from.
type EventSource = Literal["obico", "operator", "agent", "system"]


class ExecutionOutcomeFailedPayload(TypedDict):
    """What the `failed` arm of `ExecutionOutcome` carries.

    The printer did not, for this reason.
    """

    # Why it failed.
    reason: str


class ExecutionOutcomeFailed(TypedDict):
    """The `failed` arm of `ExecutionOutcome`.

    The printer did not, for this reason.
    """

    failed: ExecutionOutcomeFailedPayload


# What happened when an accepted action reached the printer.
type ExecutionOutcome = ExecutionOutcomeFailed | Literal["succeeded"]


# A file name a printer's own file API can be asked for: no path separator,
# no NUL byte, no `.` or `..` segment, no drive prefix, and not empty.
type FileName = str


class HeaterSnapshot(TypedDict):
    """`HeaterSnapshot`, as the contracts declare it.

    One heater, as a source reported it.

    Every field is optional, because a source that reports no heater at
    all
    reports none of these; each is a plausibility-ranged reported value in
    degrees Celsius.
    """

    # The temperature the heater is at.
    actual_c: NotRequired[Reported | None]
    # The offset applied to this heater's target.
    offset_c: NotRequired[Reported | None]
    # The temperature the heater is driving towards.
    target_c: NotRequired[Reported | None]


class HistoryAnswer(TypedDict):
    """`HistoryAnswer`, as the contracts declare it.

    What a history read answers.
    """

    # The print's events, newest first.
    events: list[EventRecord]


class ImageAnswer(TypedDict):
    """`ImageAnswer`, as the contracts declare it.

    What an image read answers.

    The path is absolute on this server's own filesystem, and is the whole
    of
    the answer about the bytes: nothing here renders them, encodes them or
    serves them. It is absent when the record is intact and the file is
    not,
    which is a different answer from there being no such image.
    """

    # Where its bytes are, absolute on this host.
    path: NotRequired[str | None]
    # The record.
    record: ImageRecord


# A lowercase hyphenated version 7 UUID identifying one image.
type ImageId = str


class ImageRecord(TypedDict):
    """`ImageRecord`, as the contracts declare it.

    One image, stored beside the event it arrived with.

    `relative_path` is relative to the configured state directory, so that
    the
    store stays portable. Materializing an image resolves that to an
    absolute
    path; nothing in this system renders image bytes into JSON.
    """

    # How many bytes it is.
    byte_len: int
    # The content type it was served as.
    content_type: str
    # The event it arrived with.
    event_id: EventId
    # When it was fetched.
    fetched_at: Timestamp
    # This image's identifier, minted by the store.
    id: ImageId
    # The print it belongs to.
    print_id: PrintId
    # Where it lives, relative to the configured state directory.
    relative_path: str
    # The SHA-256 of its bytes, lowercase hexadecimal.
    sha256: str
    # Where it was fetched from, when it was fetched from somewhere.
    source_url: NotRequired[str | None]


class ImageRef(TypedDict):
    """`ImageRef`, as the contracts declare it.

    The handle an image travels in context under.
    """

    # The image's identifier.
    id: ImageId
    # The SHA-256 of its bytes, lowercase hexadecimal.
    sha256: str


class Intervention(TypedDict):
    """`Intervention`, as the contracts declare it.

    One adjustment made for a bounded time.

    `prior_value` is read from the printer snapshot taken before the
    change, and
    is absent when the printer reported none — in which case expiry
    restores
    nothing and the outcome says so rather than guessing a default.
    """

    # The action that asked for it.
    action_id: ActionId
    # What it changed.
    adjustable: Adjustable
    # When it was applied.
    applied_at: Timestamp
    # What it was changed to.
    applied_value: float
    # When it stops standing.
    expires_at: Timestamp
    # This intervention's identifier, minted by the store.
    id: InterventionId
    # What became of it.
    outcome: InterventionOutcome
    # The print it was made against.
    print_id: PrintId
    # What the printer reported before the change, if it reported anything.
    prior_value: NotRequired[float | None]
    # When the prior value was put back, if it was.
    restored_at: NotRequired[Timestamp | None]


class InterventionExpiredPayload(TypedDict):
    """`InterventionExpiredPayload`, as the contracts declare it.

    A bounded intervention expired.
    """

    # What it had changed.
    adjustable: Adjustable
    # The intervention's identifier.
    intervention_id: InterventionId
    # What became of it.
    outcome: InterventionOutcome


# A lowercase hyphenated version 7 UUID identifying one bounded
# intervention.
type InterventionId = str


class InterventionOutcomeRestoreFailedPayload(TypedDict):
    """What the `restore_failed` arm of `InterventionOutcome` carries.

    Putting the prior value back failed.
    """

    # Why it failed.
    reason: str


class InterventionOutcomeRestoreFailed(TypedDict):
    """The `restore_failed` arm of `InterventionOutcome`.

    Putting the prior value back failed.
    """

    restore_failed: InterventionOutcomeRestoreFailedPayload


class InterventionOutcomeSupersededPayload(TypedDict):
    """What the `superseded` arm of `InterventionOutcome` carries.

    Another intervention replaced it before it expired.
    """

    # The intervention that replaced it.
    by: InterventionId


class InterventionOutcomeSuperseded(TypedDict):
    """The `superseded` arm of `InterventionOutcome`.

    Another intervention replaced it before it expired.
    """

    superseded: InterventionOutcomeSupersededPayload


# What became of a bounded change.
type InterventionOutcome = (
    InterventionOutcomeRestoreFailed
    | InterventionOutcomeSuperseded
    | Literal["still_active", "restored", "restore_unavailable"]
)


class JobManifest(TypedDict):
    """`JobManifest`, as the contracts declare it.

    What a sliced job declares about itself and about what may be
    adjusted.

    An adjustable the manifest does not name takes the envelope's own
    range; a
    manifest range wider than the envelope's is narrowed to the envelope's
    and
    the narrowing is recorded on the print. A manifest may only narrow.
    """

    # The range each named adjustable may take, inclusive.
    allowed: dict[str, Range]
    # The file this manifest is about, as the slicer named it.
    file_name: str
    # The material the job is sliced for.
    material: str
    # Whatever else the slicer recorded.
    metadata: dict[str, str]
    # The nozzle the job is sliced for, in millimetres.
    nozzle_diameter_mm: float
    # The slicer profile the job was sliced with.
    slicer_profile: str


class JobSnapshot(TypedDict):
    """`JobSnapshot`, as the contracts declare it.

    The job a printer reports it is running.

    Every field but `state` is optional: an absent one means the source
    did not
    report it.
    """

    # How far through the print is, as a fraction from zero to one.
    #
    # Normalized to a fraction here regardless of how the source expresses
    # it.
    completion: NotRequired[Reported | None]
    # The error the source reports, when it reports one.
    error: NotRequired[str | None]
    # The whole print's estimated duration, in whole seconds.
    estimated_print_time_s: NotRequired[int | None]
    # The name of the file being printed, as the source reported it.
    file_name: NotRequired[str | None]
    # Where the file lives, in the source's own vocabulary.
    file_origin: NotRequired[str | None]
    # How long the print has left, in whole seconds.
    print_time_left_s: NotRequired[int | None]
    # How long the print has been running, in whole seconds.
    print_time_s: NotRequired[int | None]
    # The file's size in bytes.
    size_bytes: NotRequired[int | None]
    # The state the source reports the job to be in.
    state: PrinterState


class MalformedExternalEventPayload(TypedDict):
    """`MalformedExternalEventPayload`, as the contracts declare it.

    An external body arrived that could not be read.

    This kind always carries its `raw` bytes, and it exists so that an
    alert
    this system cannot read is written down rather than dropped.
    """

    # One line saying why the body could not be read.
    detail: str


class ManifestAnswer(TypedDict):
    """`ManifestAnswer`, as the contracts declare it.

    What a manifest read or write answers.
    """

    # The manifest, when the print has one.
    manifest: NotRequired[JobManifest | None]
    # Every range this manifest asked wider than the envelope allows,
    # narrowed
    # to the envelope's — recorded on the print, so nobody has to wonder
    # later
    # which bound applied.
    narrowings: list[ManifestNarrowing]


class ManifestNarrowing(TypedDict):
    """`ManifestNarrowing`, as the contracts declare it.

    One adjustable whose manifest range was wider than the envelope's.
    """

    # The adjustable that was narrowed.
    adjustable: Adjustable
    # The range that stands.
    applied: Range
    # The range the manifest asked for.
    requested: Range


class ObicoFailureAlertPayload(TypedDict):
    """`ObicoFailureAlertPayload`, as the contracts declare it.

    Obico reported a print failure.

    The two instants are optional because Obico's own field for each is a
    Unix
    timestamp number, an empty string, or absent, and the last two both
    mean the
    producer reported no instant. An absent field here is that, never an
    epoch
    date standing in for it.
    """

    # When the print ended, when Obico reported an instant for it.
    ended_at: NotRequired[Timestamp | None]
    # The file being printed, when Obico named one.
    file_name: NotRequired[str | None]
    # Whether Obico called it a warning rather than a failure.
    is_warning: bool
    # Obico's own identifier for the print, when it named one.
    obico_print_id: NotRequired[int | None]
    # Whether Obico paused the print itself.
    print_paused: bool
    # When the print started, when Obico reported an instant for it.
    started_at: NotRequired[Timestamp | None]


# The kind of printer notification Obico sent, normalized.
type ObicoNotificationType = Literal[
    "started",
    "done",
    "cancelled",
    "paused",
    "resumed",
    "filament_change",
    "heater_cooled",
    "heater_target",
]


class ObicoPrinterNotificationPayload(TypedDict):
    """`ObicoPrinterNotificationPayload`, as the contracts declare it.

    Obico sent a printer notification.

    The two instants are optional for the same reason
    `ObicoFailureAlertPayload`'s are, and are absent along with the rest
    of
    the print's fields when the notification is about no print at all.
    """

    # When the print ended, when Obico reported an instant for it.
    ended_at: NotRequired[Timestamp | None]
    # The file being printed, when the notification is about one.
    file_name: NotRequired[str | None]
    # Which notification it is.
    notification_type: ObicoNotificationType
    # Obico's own identifier for the print, when the notification is about
    # one.
    obico_print_id: NotRequired[int | None]
    # When the print started, when Obico reported an instant for it.
    started_at: NotRequired[Timestamp | None]


class OperatorAcknowledgementPayload(TypedDict):
    """`OperatorAcknowledgementPayload`, as the contracts declare it.

    An operator acknowledged an event.
    """

    # The event being acknowledged.
    acknowledged_event_id: EventId
    # What the operator asked for next.
    disposition: AcknowledgementDisposition


class PolicyDecisionRejected(TypedDict):
    """The `rejected` arm of `PolicyDecision`.

    The request may not, for this reason.
    """

    rejected: RejectionReason


# The decision policy took on one request.
type PolicyDecision = PolicyDecisionRejected | Literal["accepted"]


class PortFailurePayload(TypedDict):
    """`PortFailurePayload`, as the contracts declare it.

    A port failed while one event was being handled.

    The event is named rather than implied, so that a reader holding an
    event's
    identifier reaches every failure recorded while that event was being
    handled. A failure recorded here is one the handling survived: the
    event is
    already in the history by the time any of these sites is reached, and
    the
    loop goes on to handle the next event.
    """

    # What the port said about it, in the port's own words.
    detail: str
    # The event whose handling reached the failing call.
    event_id: EventId
    # Where it failed.
    site: PortFailureSite


# Where a port failed while an event was being handled.
#
# A closed set of exactly the sites at which a failure has nowhere else to
# be
# recorded. The printer's action methods record theirs on the
# `ActionRecord` the request minted, and a restoring
# call records its own on the `Intervention` it was
# expiring; those are not sites here, because a second record of them would
# be
# a second version of one fact.
type PortFailureSite = Literal["printer_snapshot", "printer_job", "image_write", "supervision_turn"]


class PrintActionPause(TypedDict):
    """The `pause` arm of `PrintAction`.

    Pause the print.
    """

    action: Literal["pause"]
    # Who is asking.
    actor: Actor
    # Why the actor is asking for this.
    reason: str


class PrintActionResume(TypedDict):
    """The `resume` arm of `PrintAction`.

    Resume the print.
    """

    action: Literal["resume"]
    # Who is asking.
    actor: Actor
    # Why the actor is asking for this.
    reason: str


class PrintActionCancel(TypedDict):
    """The `cancel` arm of `PrintAction`.

    Cancel the print.
    """

    action: Literal["cancel"]
    # Who is asking.
    actor: Actor
    # Why the actor is asking for this.
    reason: str


class PrintActionStartPrint(TypedDict):
    """The `start_print` arm of `PrintAction`.

    Start a print of a named file, with a manifest.
    """

    action: Literal["start_print"]
    # Who is asking.
    actor: Actor
    # The file to print, validated as a name a file API can be asked for.
    file_name: FileName
    # The manifest this print is bounded by.
    manifest: JobManifest
    # Why the actor is asking for this.
    reason: str


class PrintActionSetFeedrateFactor(TypedDict):
    """The `set_feedrate_factor` arm of `PrintAction`.

    Set the feedrate factor, where one means one hundred percent.
    """

    action: Literal["set_feedrate_factor"]
    # Who is asking.
    actor: Actor
    # How long the change stands for, in whole seconds.
    duration_s: NotRequired[int | None]
    # The multiplier asked for.
    factor: float
    # Why the actor is asking for this.
    reason: str


class PrintActionSetFlowrateFactor(TypedDict):
    """The `set_flowrate_factor` arm of `PrintAction`.

    Set the flowrate factor, where one means one hundred percent.
    """

    action: Literal["set_flowrate_factor"]
    # Who is asking.
    actor: Actor
    # How long the change stands for, in whole seconds.
    duration_s: NotRequired[int | None]
    # The multiplier asked for.
    factor: float
    # Why the actor is asking for this.
    reason: str


class PrintActionSetToolTargetC(TypedDict):
    """The `set_tool_target_c` arm of `PrintAction`.

    Set one tool's target temperature.
    """

    action: Literal["set_tool_target_c"]
    # Who is asking.
    actor: Actor
    # How long the change stands for, in whole seconds.
    duration_s: NotRequired[int | None]
    # Why the actor is asking for this.
    reason: str
    # The target temperature asked for, in degrees Celsius.
    target_c: float
    # The tool, in the printer's own numbering.
    tool: int


class PrintActionSetBedTargetC(TypedDict):
    """The `set_bed_target_c` arm of `PrintAction`.

    Set the bed's target temperature.
    """

    action: Literal["set_bed_target_c"]
    # Who is asking.
    actor: Actor
    # How long the change stands for, in whole seconds.
    duration_s: NotRequired[int | None]
    # Why the actor is asking for this.
    reason: str
    # The target temperature asked for, in degrees Celsius.
    target_c: float


class PrintActionSetFanPercent(TypedDict):
    """The `set_fan_percent` arm of `PrintAction`.

    Set the part-cooling fan percentage.
    """

    action: Literal["set_fan_percent"]
    # Who is asking.
    actor: Actor
    # How long the change stands for, in whole seconds.
    duration_s: NotRequired[int | None]
    # The percentage asked for.
    percent: float
    # Why the actor is asking for this.
    reason: str


class PrintActionAcknowledgeFailure(TypedDict):
    """The `acknowledge_failure` arm of `PrintAction`.

    Acknowledge a failure event, with a disposition.
    """

    action: Literal["acknowledge_failure"]
    # Who is asking.
    actor: Actor
    # What to do next.
    disposition: AcknowledgementDisposition
    # The event being acknowledged.
    event_id: EventId
    # Why the actor is asking for this.
    reason: str


# The whole vocabulary an actor may ask for, and there is no other.
type PrintAction = (
    PrintActionPause
    | PrintActionResume
    | PrintActionCancel
    | PrintActionStartPrint
    | PrintActionSetFeedrateFactor
    | PrintActionSetFlowrateFactor
    | PrintActionSetToolTargetC
    | PrintActionSetBedTargetC
    | PrintActionSetFanPercent
    | PrintActionAcknowledgeFailure
)


class PrintContext(TypedDict):
    """`PrintContext`, as the contracts declare it.

    Everything a supervision turn is given about one print.
    """

    # The limits in force, so that the agent can see them before it asks.
    bounds: EffectiveBounds
    # The interventions still active.
    interventions: list[Intervention]
    # The job, when a snapshot could be taken.
    job: NotRequired[JobSnapshot | None]
    # The most recent image, when there is one.
    latest_image: NotRequired[ImageRef | None]
    # The manifest, when the print has one.
    manifest: NotRequired[JobManifest | None]
    # The print itself.
    print: PrintRecord
    # The printer, when a snapshot could be taken.
    printer: NotRequired[PrinterSnapshot | None]
    # A bounded list of this print's events, newest first.
    recent_events: list[EventRecord]


# A lowercase hyphenated version 7 UUID identifying one print.
type PrintId = str


class PrintRecord(TypedDict):
    """`PrintRecord`, as the contracts declare it.

    One print, and the record supervision keys from.

    Obico's own print id is carried beside this record's identifier rather
    than
    as it, because a print may be observed before Obico has one.
    """

    # Why it ended, if it has.
    end_reason: NotRequired[str | None]
    # When it ended, if it has.
    ended_at: NotRequired[Timestamp | None]
    # The file being printed, as the source reported it.
    file_name: NotRequired[str | None]
    # This print's identifier, minted by the store.
    id: PrintId
    # Every manifest range this print narrowed to the envelope's.
    narrowings: list[ManifestNarrowing]
    # Obico's own identifier for the print, when Obico has one.
    obico_print_id: NotRequired[int | None]
    # When the print was opened.
    opened_at: Timestamp
    # The state the print is in.
    state: PrinterState


class PrinterSnapshot(TypedDict):
    """`PrinterSnapshot`, as the contracts declare it.

    A printer, as a source reported it at one instant.
    """

    # The bed heater, when the printer reports one.
    bed: NotRequired[HeaterSnapshot | None]
    # The chamber heater, when the printer reports one.
    chamber: NotRequired[HeaterSnapshot | None]
    # The state the printer is in.
    connection: PrinterState
    # The part-cooling fan, in percent.
    fan_percent: NotRequired[Reported | None]
    # The feedrate multiplier, where one means one hundred percent.
    feedrate_factor: NotRequired[Reported | None]
    # The flowrate multiplier, where one means one hundred percent.
    flowrate_factor: NotRequired[Reported | None]
    # The instant this observation was taken.
    observed_at: Timestamp
    # The tool heaters, indexed by tool number.
    tools: list[HeaterSnapshot]


class PrinterStateUnknown(TypedDict):
    """The `unknown` arm of `PrinterState`.

    A state this vocabulary does not name, in the source's own word for
    it.
    """

    unknown: str


# The state a source reports a printer or a print to be in.
#
# The `unknown` arm exists so that a state nobody anticipated is recorded
# carrying the source's own word for it rather than lost.
type PrinterState = (
    PrinterStateUnknown
    | Literal["operational", "paused", "printing", "cancelling", "error", "offline"]
)


class Range(TypedDict):
    """`Range`, as the contracts declare it.

    An inclusive pair of 64-bit floats.
    """

    # The highest value the range admits, inclusive.
    max: float
    # The lowest value the range admits, inclusive.
    min: float


# Bytes exactly as received, base64-encoded.
type RawBytes = str


class RejectionReasonOutOfBoundsPayload(TypedDict):
    """What the `out_of_bounds` arm of `RejectionReason` carries.

    The value asked for is outside the range allowed for that adjustable.
    """

    # The adjustable that was asked for.
    adjustable: Adjustable
    # The range that was allowed.
    allowed: Range
    # The value that was asked for.
    requested: float


class RejectionReasonOutOfBounds(TypedDict):
    """The `out_of_bounds` arm of `RejectionReason`.

    The value asked for is outside the range allowed for that adjustable.
    """

    out_of_bounds: RejectionReasonOutOfBoundsPayload


class RejectionReasonActorMayNotRequestPayload(TypedDict):
    """What the `actor_may_not_request` arm of `RejectionReason` carries.

    This actor class may not request this action at all.
    """

    # The action they asked for.
    action: ActionKind
    # The class of the actor that asked.
    actor_class: ActorClass


class RejectionReasonActorMayNotRequest(TypedDict):
    """The `actor_may_not_request` arm of `RejectionReason`.

    This actor class may not request this action at all.
    """

    actor_may_not_request: RejectionReasonActorMayNotRequestPayload


class RejectionReasonInvalidFromStatePayload(TypedDict):
    """What the `invalid_from_state` arm of `RejectionReason` carries.

    The printer is not in a state this action is valid from.
    """

    # The state the printer is in.
    state: PrinterState


class RejectionReasonInvalidFromState(TypedDict):
    """The `invalid_from_state` arm of `RejectionReason`.

    The printer is not in a state this action is valid from.
    """

    invalid_from_state: RejectionReasonInvalidFromStatePayload


class RejectionReasonMinIntervalNotElapsedPayload(TypedDict):
    """What the `min_interval_not_elapsed` arm of `RejectionReason` carries.

    The agent's minimum interval has not elapsed.
    """

    # The minimum interval, in whole seconds.
    interval_s: int
    # How long it has been since the last agent action, in whole seconds.
    since_last_s: int


class RejectionReasonMinIntervalNotElapsed(TypedDict):
    """The `min_interval_not_elapsed` arm of `RejectionReason`.

    The agent's minimum interval has not elapsed.
    """

    min_interval_not_elapsed: RejectionReasonMinIntervalNotElapsedPayload


class RejectionReasonUnsupportedAdjustablePayload(TypedDict):
    """What the `unsupported_adjustable` arm of `RejectionReason` carries.

    The adjustable is not one this printer has.
    """

    # The adjustable this printer cannot express.
    adjustable: Adjustable


class RejectionReasonUnsupportedAdjustable(TypedDict):
    """The `unsupported_adjustable` arm of `RejectionReason`.

    The adjustable is not one this printer has.
    """

    unsupported_adjustable: RejectionReasonUnsupportedAdjustablePayload


# Why a request was refused.
#
# Each rejection is a distinct variant, so a consumer distinguishes them by
# matching rather than by reading a message.
type RejectionReason = (
    RejectionReasonOutOfBounds
    | RejectionReasonActorMayNotRequest
    | RejectionReasonInvalidFromState
    | RejectionReasonMinIntervalNotElapsed
    | RejectionReasonUnsupportedAdjustable
    | Literal["no_active_print"]
)


class Reported(TypedDict):
    """`Reported`, as the contracts declare it.

    A value as a source reported it, flagged when it is outside the
    plausibility range this crate declares for its field.
    """

    # One shape of the contracts, which say nothing more about it.
    out_of_range: bool
    # One shape of the contracts, which say nothing more about it.
    value: float


class StartupOutcomeSessionResumedPayload(TypedDict):
    """What the `session_resumed` arm of `StartupOutcome` carries.

    A session left open was resumed rather than replaced.
    """

    # The session's own name in the harness.
    session_name: str


class StartupOutcomeSessionResumed(TypedDict):
    """The `session_resumed` arm of `StartupOutcome`.

    A session left open was resumed rather than replaced.
    """

    session_resumed: StartupOutcomeSessionResumedPayload


class StartupOutcomeInterventionExpiredPayload(TypedDict):
    """What the `intervention_expired` arm of `StartupOutcome` carries.

    An intervention already past its expiry was expired on start.
    """

    # What it had changed.
    adjustable: Adjustable
    # The intervention that had outlived its bound.
    intervention_id: InterventionId
    # What became of putting the prior value back.
    outcome: InterventionOutcome


class StartupOutcomeInterventionExpired(TypedDict):
    """The `intervention_expired` arm of `StartupOutcome`.

    An intervention already past its expiry was expired on start.
    """

    intervention_expired: StartupOutcomeInterventionExpiredPayload


# What one restart put back the way it found it.
#
# A supervisor that has been restarted adopts whatever the store holds
# rather
# than starting empty, and each of these is one of those adoptions. They are
# recorded rather than merely done, because a print that carried on across a
# restart and one that was started again look identical afterwards unless
# the
# history says which happened.
type StartupOutcome = (
    StartupOutcomeSessionResumed | StartupOutcomeInterventionExpired | Literal["print_adopted"]
)


class StartupReconciliationPayload(TypedDict):
    """`StartupReconciliationPayload`, as the contracts declare it.

    A supervisor reconciled one thing the store held when it started.
    """

    # What was reconciled.
    outcome: StartupOutcome
    # The print it is about.
    print_id: PrintId


class StatusAnswer(TypedDict):
    """`StatusAnswer`, as the contracts declare it.

    What a status read answers.
    """

    # The bounded interventions still in force.
    interventions: list[Intervention]
    # The job, when a snapshot could be taken.
    job: NotRequired[JobSnapshot | None]
    # The print.
    print: PrintRecord
    # The printer, when a snapshot could be taken.
    printer: NotRequired[PrinterSnapshot | None]
    # The supervision session watching it, when one is.
    session: NotRequired[SupervisionSession | None]


class SupervisionSession(TypedDict):
    """`SupervisionSession`, as the contracts declare it.

    The supervision session keyed to one print.
    """

    # Why it was closed, if it was.
    close_reason: NotRequired[str | None]
    # When the session was closed, if it was.
    closed_at: NotRequired[Timestamp | None]
    # When the session was opened.
    created_at: Timestamp
    # The identity the harness ran the session under.
    harness_identity: str
    # When the last turn ran.
    last_turn_at: Timestamp
    # The print this session watches.
    print_id: PrintId
    # The session's own name in the harness.
    session_name: str


class SupervisionSessionClosedPayload(TypedDict):
    """`SupervisionSessionClosedPayload`, as the contracts declare it.

    A supervision session was closed.
    """

    # Why it was closed.
    close_reason: str
    # The session's own name in the harness.
    session_name: str


class SupervisionSessionOpenedPayload(TypedDict):
    """`SupervisionSessionOpenedPayload`, as the contracts declare it.

    A supervision session was opened.
    """

    # The identity the harness ran it under.
    harness_identity: str
    # The session's own name in the harness.
    session_name: str


# An instant in UTC, as an RFC 3339 string with a zero offset.
type Timestamp = str


class GeneratedClient(GeneratedSurface):
    """One method per operation the server declares.

    Every method here is generated from the checked-in description of the
    server's own operations. The transport, the configuration and the
    error vocabulary are hand-written, and this class is written against
    them.
    """

    def status(self, print_id: str) -> StatusAnswer:
        """Call `status` on the configured supervisor.

        Raises:
            UnreachableError: If nothing answered at the configured
                address.
            UnreadableError: If the supervisor answered something this
                client cannot read.
            RefusedError: If the supervisor will not do what it was asked.
        """
        target = f"/v1/prints/{print_id}/status"
        asked: list[tuple[str, str]] = []
        sending = None
        answered = self.call("GET", target, asked, sending)
        return cast(StatusAnswer, answered)

    def context(self, print_id: str) -> ContextAnswer:
        """Call `context` on the configured supervisor.

        Raises:
            UnreachableError: If nothing answered at the configured
                address.
            UnreadableError: If the supervisor answered something this
                client cannot read.
            RefusedError: If the supervisor will not do what it was asked.
        """
        target = f"/v1/prints/{print_id}/context"
        asked: list[tuple[str, str]] = []
        sending = None
        answered = self.call("GET", target, asked, sending)
        return cast(ContextAnswer, answered)

    def image(self, image_id: str) -> ImageAnswer:
        """Call `image` on the configured supervisor.

        Raises:
            UnreachableError: If nothing answered at the configured
                address.
            UnreadableError: If the supervisor answered something this
                client cannot read.
            RefusedError: If the supervisor will not do what it was asked.
        """
        target = f"/v1/images/{image_id}"
        asked: list[tuple[str, str]] = []
        sending = None
        answered = self.call("GET", target, asked, sending)
        return cast(ImageAnswer, answered)

    def history(self, print_id: str, limit: int | None = None) -> HistoryAnswer:
        """Call `history` on the configured supervisor.

        Raises:
            UnreachableError: If nothing answered at the configured
                address.
            UnreadableError: If the supervisor answered something this
                client cannot read.
            RefusedError: If the supervisor will not do what it was asked.
        """
        target = f"/v1/prints/{print_id}/history"
        asked: list[tuple[str, str]] = []
        if limit is not None:
            asked.append(("limit", str(limit)))
        sending = None
        answered = self.call("GET", target, asked, sending)
        return cast(HistoryAnswer, answered)

    def manifest_get(self, print_id: str) -> ManifestAnswer:
        """Call `manifest_get` on the configured supervisor.

        Raises:
            UnreachableError: If nothing answered at the configured
                address.
            UnreadableError: If the supervisor answered something this
                client cannot read.
            RefusedError: If the supervisor will not do what it was asked.
        """
        target = f"/v1/prints/{print_id}/manifest"
        asked: list[tuple[str, str]] = []
        sending = None
        answered = self.call("GET", target, asked, sending)
        return cast(ManifestAnswer, answered)

    def manifest_set(self, print_id: str, reason: str, manifest: JobManifest) -> ManifestAnswer:
        """Call `manifest_set` on the configured supervisor.

        Raises:
            NoReasonError: If the reason is absent or is nothing but
                whitespace.
            UnreachableError: If nothing answered at the configured
                address.
            UnreadableError: If the supervisor answered something this
                client cannot read.
            RefusedError: If the supervisor will not do what it was asked.
            RejectedError: If the policy refused the action. It carries
                the reason, the value asked for and the range allowed.
        """
        reason_given(reason)
        target = f"/v1/prints/{print_id}/manifest"
        asked: list[tuple[str, str]] = []
        sending: dict[str, object] = {}
        sending["reason"] = reason
        sending["manifest"] = manifest
        answered = self.call("PUT", target, asked, sending)
        return cast(ManifestAnswer, answered)

    def pause(self, print_id: str, reason: str) -> ActionAnswer:
        """Call `pause` on the configured supervisor.

        Raises:
            NoReasonError: If the reason is absent or is nothing but
                whitespace.
            UnreachableError: If nothing answered at the configured
                address.
            UnreadableError: If the supervisor answered something this
                client cannot read.
            RefusedError: If the supervisor will not do what it was asked.
            RejectedError: If the policy refused the action. It carries
                the reason, the value asked for and the range allowed.
        """
        reason_given(reason)
        target = f"/v1/prints/{print_id}/actions/pause"
        asked: list[tuple[str, str]] = []
        sending: dict[str, object] = {}
        sending["actor"] = self.actor
        sending["reason"] = reason
        answered = self.call("POST", target, asked, sending)
        return cast(ActionAnswer, answered)

    def resume(self, print_id: str, reason: str) -> ActionAnswer:
        """Call `resume` on the configured supervisor.

        Raises:
            NoReasonError: If the reason is absent or is nothing but
                whitespace.
            UnreachableError: If nothing answered at the configured
                address.
            UnreadableError: If the supervisor answered something this
                client cannot read.
            RefusedError: If the supervisor will not do what it was asked.
            RejectedError: If the policy refused the action. It carries
                the reason, the value asked for and the range allowed.
        """
        reason_given(reason)
        target = f"/v1/prints/{print_id}/actions/resume"
        asked: list[tuple[str, str]] = []
        sending: dict[str, object] = {}
        sending["actor"] = self.actor
        sending["reason"] = reason
        answered = self.call("POST", target, asked, sending)
        return cast(ActionAnswer, answered)

    def cancel(self, print_id: str, reason: str) -> ActionAnswer:
        """Call `cancel` on the configured supervisor.

        Raises:
            NoReasonError: If the reason is absent or is nothing but
                whitespace.
            UnreachableError: If nothing answered at the configured
                address.
            UnreadableError: If the supervisor answered something this
                client cannot read.
            RefusedError: If the supervisor will not do what it was asked.
            RejectedError: If the policy refused the action. It carries
                the reason, the value asked for and the range allowed.
        """
        reason_given(reason)
        target = f"/v1/prints/{print_id}/actions/cancel"
        asked: list[tuple[str, str]] = []
        sending: dict[str, object] = {}
        sending["actor"] = self.actor
        sending["reason"] = reason
        answered = self.call("POST", target, asked, sending)
        return cast(ActionAnswer, answered)

    def start_print(
        self, print_id: str, file_name: FileName, manifest: JobManifest, reason: str
    ) -> ActionAnswer:
        """Call `start_print` on the configured supervisor.

        Raises:
            NoReasonError: If the reason is absent or is nothing but
                whitespace.
            UnreachableError: If nothing answered at the configured
                address.
            UnreadableError: If the supervisor answered something this
                client cannot read.
            RefusedError: If the supervisor will not do what it was asked.
            RejectedError: If the policy refused the action. It carries
                the reason, the value asked for and the range allowed.
        """
        reason_given(reason)
        target = f"/v1/prints/{print_id}/actions/start_print"
        asked: list[tuple[str, str]] = []
        sending: dict[str, object] = {}
        sending["actor"] = self.actor
        sending["file_name"] = file_name
        sending["manifest"] = manifest
        sending["reason"] = reason
        answered = self.call("POST", target, asked, sending)
        return cast(ActionAnswer, answered)

    def set_feedrate_factor(
        self, print_id: str, factor: float, reason: str, duration_s: int | None = None
    ) -> ActionAnswer:
        """Call `set_feedrate_factor` on the configured supervisor.

        Raises:
            NoReasonError: If the reason is absent or is nothing but
                whitespace.
            UnreachableError: If nothing answered at the configured
                address.
            UnreadableError: If the supervisor answered something this
                client cannot read.
            RefusedError: If the supervisor will not do what it was asked.
            RejectedError: If the policy refused the action. It carries
                the reason, the value asked for and the range allowed.
        """
        reason_given(reason)
        target = f"/v1/prints/{print_id}/actions/set_feedrate_factor"
        asked: list[tuple[str, str]] = []
        sending: dict[str, object] = {}
        sending["actor"] = self.actor
        if duration_s is not None:
            sending["duration_s"] = duration_s
        sending["factor"] = factor
        sending["reason"] = reason
        answered = self.call("POST", target, asked, sending)
        return cast(ActionAnswer, answered)

    def set_flowrate_factor(
        self, print_id: str, factor: float, reason: str, duration_s: int | None = None
    ) -> ActionAnswer:
        """Call `set_flowrate_factor` on the configured supervisor.

        Raises:
            NoReasonError: If the reason is absent or is nothing but
                whitespace.
            UnreachableError: If nothing answered at the configured
                address.
            UnreadableError: If the supervisor answered something this
                client cannot read.
            RefusedError: If the supervisor will not do what it was asked.
            RejectedError: If the policy refused the action. It carries
                the reason, the value asked for and the range allowed.
        """
        reason_given(reason)
        target = f"/v1/prints/{print_id}/actions/set_flowrate_factor"
        asked: list[tuple[str, str]] = []
        sending: dict[str, object] = {}
        sending["actor"] = self.actor
        if duration_s is not None:
            sending["duration_s"] = duration_s
        sending["factor"] = factor
        sending["reason"] = reason
        answered = self.call("POST", target, asked, sending)
        return cast(ActionAnswer, answered)

    def set_tool_target_c(
        self, print_id: str, reason: str, target_c: float, tool: int, duration_s: int | None = None
    ) -> ActionAnswer:
        """Call `set_tool_target_c` on the configured supervisor.

        Raises:
            NoReasonError: If the reason is absent or is nothing but
                whitespace.
            UnreachableError: If nothing answered at the configured
                address.
            UnreadableError: If the supervisor answered something this
                client cannot read.
            RefusedError: If the supervisor will not do what it was asked.
            RejectedError: If the policy refused the action. It carries
                the reason, the value asked for and the range allowed.
        """
        reason_given(reason)
        target = f"/v1/prints/{print_id}/actions/set_tool_target_c"
        asked: list[tuple[str, str]] = []
        sending: dict[str, object] = {}
        sending["actor"] = self.actor
        if duration_s is not None:
            sending["duration_s"] = duration_s
        sending["reason"] = reason
        sending["target_c"] = target_c
        sending["tool"] = tool
        answered = self.call("POST", target, asked, sending)
        return cast(ActionAnswer, answered)

    def set_bed_target_c(
        self, print_id: str, reason: str, target_c: float, duration_s: int | None = None
    ) -> ActionAnswer:
        """Call `set_bed_target_c` on the configured supervisor.

        Raises:
            NoReasonError: If the reason is absent or is nothing but
                whitespace.
            UnreachableError: If nothing answered at the configured
                address.
            UnreadableError: If the supervisor answered something this
                client cannot read.
            RefusedError: If the supervisor will not do what it was asked.
            RejectedError: If the policy refused the action. It carries
                the reason, the value asked for and the range allowed.
        """
        reason_given(reason)
        target = f"/v1/prints/{print_id}/actions/set_bed_target_c"
        asked: list[tuple[str, str]] = []
        sending: dict[str, object] = {}
        sending["actor"] = self.actor
        if duration_s is not None:
            sending["duration_s"] = duration_s
        sending["reason"] = reason
        sending["target_c"] = target_c
        answered = self.call("POST", target, asked, sending)
        return cast(ActionAnswer, answered)

    def set_fan_percent(
        self, print_id: str, percent: float, reason: str, duration_s: int | None = None
    ) -> ActionAnswer:
        """Call `set_fan_percent` on the configured supervisor.

        Raises:
            NoReasonError: If the reason is absent or is nothing but
                whitespace.
            UnreachableError: If nothing answered at the configured
                address.
            UnreadableError: If the supervisor answered something this
                client cannot read.
            RefusedError: If the supervisor will not do what it was asked.
            RejectedError: If the policy refused the action. It carries
                the reason, the value asked for and the range allowed.
        """
        reason_given(reason)
        target = f"/v1/prints/{print_id}/actions/set_fan_percent"
        asked: list[tuple[str, str]] = []
        sending: dict[str, object] = {}
        sending["actor"] = self.actor
        if duration_s is not None:
            sending["duration_s"] = duration_s
        sending["percent"] = percent
        sending["reason"] = reason
        answered = self.call("POST", target, asked, sending)
        return cast(ActionAnswer, answered)

    def acknowledge_failure(
        self, print_id: str, disposition: AcknowledgementDisposition, event_id: EventId, reason: str
    ) -> ActionAnswer:
        """Call `acknowledge_failure` on the configured supervisor.

        Raises:
            NoReasonError: If the reason is absent or is nothing but
                whitespace.
            UnreachableError: If nothing answered at the configured
                address.
            UnreadableError: If the supervisor answered something this
                client cannot read.
            RefusedError: If the supervisor will not do what it was asked.
            RejectedError: If the policy refused the action. It carries
                the reason, the value asked for and the range allowed.
        """
        reason_given(reason)
        target = f"/v1/prints/{print_id}/actions/acknowledge_failure"
        asked: list[tuple[str, str]] = []
        sending: dict[str, object] = {}
        sending["actor"] = self.actor
        sending["disposition"] = disposition
        sending["event_id"] = event_id
        sending["reason"] = reason
        answered = self.call("POST", target, asked, sending)
        return cast(ActionAnswer, answered)
