[package]
name = "printobserver-store-api"
description = "The store port for printobserver."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
printobserver-types = { path = "../printobserver-types", version = "0.1.0" }

[lints]
workspace = true
