"""The supervisor adapter's three structural claims, checked over the tree.

The adapter drives OneHarness through its Rust crate API in process. What that
claim rests on is not a comment: no source of the crate may use a
process-spawning interface at all, whatever executable it would name. A check
that looked for the word `oneharness` would miss a computed name, so this one
refuses the interfaces rather than the executables.

The other two are about what constrains a turn. The agent's answer is
constrained by the assessment schema the contracts generate, so the crate may
carry no schema file of its own — a copy of the generated bytes would pass any
content comparison while defeating the thing the comparison is for. And the
prompt template may name no operation of this program but the one read, with the
forbidden set derived from the generated action vocabulary rather than restated
here: a variant `PrintAction` gains enters that set the moment the contracts'
generation target writes it, so the walk cannot fall behind the type.

The fourth is about the first one's own test: proving the answer is constrained
by the *generated* artifact means changing that artifact on disk, and every
suite that reads the schema tree runs beside that one. Both sides take one
operating-system lock, and this check holds every declared holder to one name,
because two suites locking two different files are back to no lock at all.

The template rule is keyed on those names rather than on words that sound like
instructions, deliberately. An event description that says the printer paused is
a fact, not an instruction, and a rule hunting remediation-sounding words would
refuse it while catching nothing phrased another way.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path

from repo_checks.model import (
    PolicyValueError,
    Repo,
    policy_string_list,
    policy_strings,
    policy_table,
)

# Every way a Rust source starts a process. Each is refused wherever it appears
# in the adapter's sources, whatever executable it would name — which is what
# closes the conditional path a name-matching rule would miss. The aliased form
# (`use std::process::Command as Runner`) is reached by the `use` line and by
# the call that finishes it.
SPAWNING_INTERFACES = (
    "std::process::Command",
    "process::Command",
    "Command::new",
    ".spawn(",
    ".output(",
    ".status(",
    "tokio::process",
    "async_process",
    "CommandExt",
    "posix_spawn",
    "execvp",
    "execve",
    "libc::fork",
    "duct::",
    "subprocess::",
)

# Top-level keys that make a JSON document a JSON Schema rather than ordinary
# configuration. A project or package manifest carries none of them.
SCHEMA_MARKERS = ("$defs", "oneOf", "properties", "required")


# Every declaration of the `[supervisor]` section, by the kind it is read as.
# A key here is one the checks below act on, so its absence or its wrong type is
# refused where the section is parsed rather than met as an attribute error
# inside whichever check happened to read it first.
POLICY_NAMES = (
    "adapter",
    "prompt_template",
    "skill",
    "assessment_schema",
    "action_schema",
    "program",
    "context_read",
    "schema_lock",
)


@dataclass(frozen=True, slots=True)
class SupervisorPolicy:
    """The `[supervisor]` section of `repo-policy.toml`, narrowed once."""

    #: The one crate implementing the supervisor port.
    adapter: str
    #: The committed prompt template a turn fills.
    prompt_template: str
    #: The committed skill sent as every turn's system prompt.
    skill: str
    #: The generated assessment schema the agent's answer is constrained by.
    assessment_schema: str
    #: The generated action vocabulary the forbidden set is derived from.
    action_schema: str
    #: The program whose operations the template may not name.
    program: str
    #: The one operation the template may name, because it is a read.
    context_read: str
    #: The file every suite reading the checked-in schema tree locks.
    schema_lock: str
    #: The reads this system exposes beside the action vocabulary.
    reads: tuple[str, ...]
    #: Every suite declared to take the schema lock.
    schema_lock_holders: tuple[str, ...]


def supervisor_policy(repo: Repo) -> SupervisorPolicy:
    """Read the `[supervisor]` section, narrowing every value the checks act on.

    Raises:
        PolicyValueError: If the section is absent, or declares a key these
            checks read as something other than what they read it as. A check
            reading it unnarrowed would fail the tier with a traceback naming a
            key nobody outside these sources has heard of.
    """
    table = policy_table(repo, "supervisor")
    if not table:
        msg = "`repo-policy.toml` declares no `[supervisor]` section"
        raise PolicyValueError(msg)
    named = policy_strings(table, POLICY_NAMES, "supervisor")
    return SupervisorPolicy(
        adapter=named["adapter"],
        prompt_template=named["prompt_template"],
        skill=named["skill"],
        assessment_schema=named["assessment_schema"],
        action_schema=named["action_schema"],
        program=named["program"],
        context_read=named["context_read"],
        schema_lock=named["schema_lock"],
        reads=policy_string_list(table, "reads", "supervisor"),
        schema_lock_holders=policy_string_list(table, "schema_lock_holders", "supervisor"),
    )


def spawn_free(repo: Repo) -> list[str]:
    """No source of the adapter names one of the spawning interfaces below.

    That is the whole of what this establishes, and it is deliberately keyed on
    the interfaces rather than on the executables: a rule looking for the word
    `oneharness` is one a computed name walks past, while every construction of
    a child process in Rust goes through one of the spellings in
    `SPAWNING_INTERFACES`, whatever it would run.
    """
    try:
        policy = supervisor_policy(repo)
    except PolicyValueError as error:
        return [str(error)]
    adapter = policy.adapter

    sources = repo.path("crates") / adapter / "src"
    if not sources.is_dir():
        return [f"crate `{adapter}` has no `src` directory to read"]

    findings: list[str] = []
    for path in sorted(sources.rglob("*.rs")):
        relative = path.relative_to(repo.root)
        for number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
            findings.extend(
                f"{relative}:{number} uses the process-spawning interface `{interface}`. "
                f"`{adapter}` drives OneHarness through its Rust crate API in process, "
                f"so it spawns nothing at all — not even something it computed the name of."
                for interface in SPAWNING_INTERFACES
                if interface in line
            )
    return findings


def _is_json_schema(path: Path) -> bool:
    """Whether one JSON file reads as a JSON Schema rather than configuration.

    A heuristic, and it errs towards refusing: a document declaring a
    json-schema.org `$schema`, or carrying one of the top-level keys a schema is
    built from, is treated as one. Configuration that happened to carry
    `properties` would be refused with it, which is the direction to be wrong in
    — the alternative is a schema this crate carries slipping past for want of a
    marker.
    """
    try:
        document = json.loads(path.read_text(encoding="utf-8"))
    except OSError, json.JSONDecodeError:
        return False
    if not isinstance(document, dict):
        return False
    declared = document.get("$schema")
    if isinstance(declared, str) and "json-schema.org" in declared:
        return True
    return any(marker in document for marker in SCHEMA_MARKERS)


def schema_source(repo: Repo) -> list[str]:
    """The generated schema is in the tree and the adapter carries no JSON one.

    JSON is the only representation this reads, because it is the only one the
    contracts' generation target writes and the only one `OneHarness` is handed.
    """
    try:
        policy = supervisor_policy(repo)
    except PolicyValueError as error:
        return [str(error)]
    adapter = policy.adapter
    generated = policy.assessment_schema

    findings: list[str] = []
    if not repo.exists(generated):
        findings.append(
            f"the generated assessment schema `{generated}` is absent, so nothing "
            f"constrains the agent's answer"
        )

    crate = repo.path("crates") / adapter
    for path in sorted(crate.rglob("*.json")):
        if "target" in path.relative_to(crate).parts:
            continue
        if _is_json_schema(path):
            findings.append(
                f"crate `{adapter}` carries the JSON Schema file "
                f"`{path.relative_to(repo.root)}`. The agent's answer is constrained by "
                f"`{generated}`, the artifact the contracts' generation target writes; a "
                f"schema this crate carries would be one it wrote, whatever its bytes say."
            )

    checked_in = repo.path("schemas") / adapter
    if checked_in.exists():
        findings.append(
            f"`schemas/{adapter}` exists: the supervisor adapter declares no types of "
            f"its own, and the answer it constrains is constrained by `{generated}`"
        )
    return findings


def _variant_of(arm: object) -> str | None:
    """The variant one arm of the action vocabulary tags, if it tags one."""
    for step in ("properties", "action"):
        if not isinstance(arm, dict):
            return None
        arm = arm.get(step, {})
    if not isinstance(arm, dict):
        return None
    tag = arm.get("const")
    return tag if isinstance(tag, str) else None


@dataclass(frozen=True, slots=True)
class ActionVocabulary:
    """What one reading of the generated action vocabulary found."""

    #: Every variant the artifact declares, in the order it declares them.
    variants: tuple[str, ...]
    #: Why the reading found none, when it found none.
    problems: tuple[str, ...]


def _action_variants(repo: Repo, relative: str) -> ActionVocabulary:
    """Every variant the generated action vocabulary declares, and why not."""
    if not repo.exists(relative):
        return ActionVocabulary((), (f"the generated action vocabulary `{relative}` is absent",))
    try:
        schema = json.loads(repo.read(relative))
    except json.JSONDecodeError as error:
        return ActionVocabulary(
            (), (f"the generated action vocabulary `{relative}` is not JSON: {error}",)
        )
    # The artifact is JSON the generation target wrote, so every value below is
    # `Any` until it is narrowed — and the narrowing goes all the way down: an
    # arm that is not a mapping, whose `properties` is not one, or whose
    # `action` is not one, declares no variant and is skipped. Reading a nested
    # value without that would fail the tier with an attribute error on a
    # generated file rather than with what is wrong with it.
    arms = schema.get("oneOf") if isinstance(schema, dict) else None
    variants = tuple(
        tag
        for arm in (arms if isinstance(arms, list) else ())
        for tag in [_variant_of(arm)]
        if tag is not None
    )
    if not variants:
        return ActionVocabulary(
            (), (f"the generated action vocabulary `{relative}` declares no variants",)
        )
    return ActionVocabulary(variants, ())


def _spellings(name: str) -> set[str]:
    """The spellings one operation may be written in on a command line."""
    return {name.replace("-", "_"), name.replace("_", "-")}


def prompt_template(repo: Repo) -> list[str]:
    """The committed template names no operation of this program but the one read."""
    try:
        policy = supervisor_policy(repo)
    except PolicyValueError as error:
        return [str(error)]

    template = policy.prompt_template
    skill = policy.skill
    program = policy.program
    context_read = policy.context_read
    reads = policy.reads

    findings: list[str] = []
    if not repo.exists(skill):
        findings.append(f"the committed skill `{skill}` is absent")
    if context_read not in reads:
        findings.append(
            f"`repo-policy.toml`'s supervisor.context_read names `{context_read}`, "
            f"which its `reads` do not"
        )
    vocabulary = _action_variants(repo, policy.action_schema)
    findings.extend(vocabulary.problems)
    if not repo.exists(template):
        return [*findings, f"the committed prompt template `{template}` is absent"]

    text = repo.read(template)
    forbidden = {name for name in [*vocabulary.variants, *reads] if name != context_read}
    for name in sorted(forbidden):
        for spelling in sorted(_spellings(name)):
            if re.search(rf"\b{re.escape(program)}\s+{re.escape(spelling)}\b", text):
                findings.append(
                    f"`{template}` names `{program} {spelling}`. The turn this template "
                    f"asks for is a reading: the only operation of this program it may "
                    f"name is the context read `{program} {context_read}`."
                )
    return findings


def schema_lock(repo: Repo) -> list[str]:
    """Every declared holder names the one lock file and takes a lock on it.

    The set of holders is `repo-policy.toml`'s rather than derived: a suite
    reading the schema tree is not something this can recognize from a source,
    so a new one joins by being declared, and that declaration is what this
    holds to the one name. What it establishes is that no two declared holders
    lock two different files, which is the failure mode a lock has.
    """
    try:
        policy = supervisor_policy(repo)
    except PolicyValueError as error:
        return [str(error)]
    name = policy.schema_lock
    holders = policy.schema_lock_holders

    findings: list[str] = []
    if len(holders) < 2:
        findings.append(
            "`repo-policy.toml`'s supervisor.schema_lock_holders names fewer than two "
            "suites, and a lock only one side takes serializes nothing"
        )
    for holder in holders:
        if not repo.exists(holder):
            findings.append(f"the declared schema-lock holder `{holder}` is absent")
            continue
        text = repo.read(holder)
        if name not in text:
            findings.append(
                f"`{holder}` is declared a holder of the schema lock and does not name "
                f"`{name}`. Two suites locking two different files are back to no lock "
                f"at all, and the journey that changes a checked-in schema would run "
                f"beside the suite that reads it."
            )
        if ".lock()" not in text:
            findings.append(
                f"`{holder}` names the schema lock file `{name}` and never takes the lock on it"
            )
    return findings
