"""The supervisor adapter's three structural claims, checked over the tree.

The adapter drives OneHarness through its Rust crate API in process. What that
claim rests on is not a comment: no source of the crate may use a
process-spawning interface at all, whatever executable it would name. A check
that looked for the word `oneharness` would miss a computed name, so this one
refuses the interfaces rather than the executables.

The other two are about what constrains a turn. The agent's answer is
constrained by the assessment schema the contracts generate, so the crate may
carry no schema file of its own — a copy of the generated bytes would pass any
content comparison while defeating the thing the comparison is for. And the
prompt template may name no operation of this program but the one read, with the
forbidden set derived from the generated action vocabulary rather than restated
here: a variant `PrintAction` gains enters that set the moment the contracts'
generation target writes it, so the walk cannot fall behind the type.

The fourth is about the first one's own test: proving the answer is constrained
by the *generated* artifact means changing that artifact on disk, and every
suite that reads the schema tree runs beside that one. Both sides take one
operating-system lock, and this check holds every declared holder to one name,
because two suites locking two different files are back to no lock at all.

The template rule is keyed on those names rather than on words that sound like
instructions, deliberately. An event description that says the printer paused is
a fact, not an instruction, and a rule hunting remediation-sounding words would
refuse it while catching nothing phrased another way.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

from repo_checks.model import Repo

# Every way a Rust source starts a process. Each is refused wherever it appears
# in the adapter's sources, whatever executable it would name — which is what
# closes the conditional path a name-matching rule would miss. The aliased form
# (`use std::process::Command as Runner`) is reached by the `use` line and by
# the call that finishes it.
SPAWNING_INTERFACES = (
    "std::process::Command",
    "process::Command",
    "Command::new",
    ".spawn(",
    ".output(",
    ".status(",
    "tokio::process",
    "async_process",
    "CommandExt",
    "posix_spawn",
    "execvp",
    "execve",
    "libc::fork",
    "duct::",
    "subprocess::",
)

# Top-level keys that make a JSON document a JSON Schema rather than ordinary
# configuration. A project or package manifest carries none of them.
SCHEMA_MARKERS = ("$defs", "oneOf", "properties", "required")


def _adapter(repo: Repo) -> tuple[dict[str, Any], str] | None:
    """The `[supervisor]` policy and the crate it is about."""
    policy = repo.policy.get("supervisor")
    if not policy:
        return None
    return policy, str(policy["adapter"])


def spawn_free(repo: Repo) -> list[str]:
    """No source of the supervisor adapter uses a process-spawning interface."""
    found = _adapter(repo)
    if found is None:
        return ["`repo-policy.toml` declares no `[supervisor]` section"]
    _, adapter = found

    sources = repo.path("crates") / adapter / "src"
    if not sources.is_dir():
        return [f"crate `{adapter}` has no `src` directory to read"]

    findings: list[str] = []
    for path in sorted(sources.rglob("*.rs")):
        relative = path.relative_to(repo.root)
        for number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
            findings.extend(
                f"{relative}:{number} uses the process-spawning interface `{interface}`. "
                f"`{adapter}` drives OneHarness through its Rust crate API in process, "
                f"so it spawns nothing at all — not even something it computed the name of."
                for interface in SPAWNING_INTERFACES
                if interface in line
            )
    return findings


def _is_json_schema(path: Path) -> bool:
    """Whether one JSON file is a JSON Schema rather than configuration."""
    try:
        document = json.loads(path.read_text(encoding="utf-8"))
    except OSError, json.JSONDecodeError:
        return False
    if not isinstance(document, dict):
        return False
    declared = document.get("$schema")
    if isinstance(declared, str) and "json-schema.org" in declared:
        return True
    return any(marker in document for marker in SCHEMA_MARKERS)


def schema_source(repo: Repo) -> list[str]:
    """The supervisor adapter carries no schema of its own."""
    found = _adapter(repo)
    if found is None:
        return ["`repo-policy.toml` declares no `[supervisor]` section"]
    policy, adapter = found
    generated = str(policy["assessment_schema"])

    findings: list[str] = []
    if not repo.exists(generated):
        findings.append(
            f"the generated assessment schema `{generated}` is absent, so nothing "
            f"constrains the agent's answer"
        )

    crate = repo.path("crates") / adapter
    for path in sorted(crate.rglob("*.json")):
        if "target" in path.relative_to(crate).parts:
            continue
        if _is_json_schema(path):
            findings.append(
                f"crate `{adapter}` carries the JSON Schema file "
                f"`{path.relative_to(repo.root)}`. The agent's answer is constrained by "
                f"`{generated}`, the artifact the contracts' generation target writes; a "
                f"schema this crate carries would be one it wrote, whatever its bytes say."
            )

    checked_in = repo.path("schemas") / adapter
    if checked_in.exists():
        findings.append(
            f"`schemas/{adapter}` exists: the supervisor adapter declares no types of "
            f"its own, and the answer it constrains is constrained by `{generated}`"
        )
    return findings


def _action_variants(repo: Repo, relative: str) -> tuple[list[str], list[str]]:
    """Every variant the generated action vocabulary declares, and why not."""
    if not repo.exists(relative):
        return [], [f"the generated action vocabulary `{relative}` is absent"]
    try:
        schema = json.loads(repo.read(relative))
    except json.JSONDecodeError as error:
        return [], [f"the generated action vocabulary `{relative}` is not JSON: {error}"]
    arms = schema.get("oneOf")
    if not isinstance(arms, list):
        return [], [f"the generated action vocabulary `{relative}` declares no variants"]
    variants: list[str] = []
    for arm in arms:
        tag = arm.get("properties", {}).get("action", {}).get("const")
        if isinstance(tag, str):
            variants.append(tag)
    if not variants:
        return [], [f"the generated action vocabulary `{relative}` declares no variants"]
    return variants, []


def _spellings(name: str) -> set[str]:
    """The spellings one operation may be written in on a command line."""
    return {name.replace("-", "_"), name.replace("_", "-")}


def prompt_template(repo: Repo) -> list[str]:
    """The committed template names no operation of this program but the one read."""
    found = _adapter(repo)
    if found is None:
        return ["`repo-policy.toml` declares no `[supervisor]` section"]
    policy, _ = found

    template = str(policy["prompt_template"])
    skill = str(policy["skill"])
    program = str(policy["program"])
    context_read = str(policy["context_read"])
    reads = [str(name) for name in policy["reads"]]

    findings: list[str] = []
    if not repo.exists(skill):
        findings.append(f"the committed skill `{skill}` is absent")
    if context_read not in reads:
        findings.append(
            f"`repo-policy.toml`'s supervisor.context_read names `{context_read}`, "
            f"which its `reads` do not"
        )
    variants, problems = _action_variants(repo, str(policy["action_schema"]))
    findings.extend(problems)
    if not repo.exists(template):
        return [*findings, f"the committed prompt template `{template}` is absent"]

    text = repo.read(template)
    forbidden = {name for name in [*variants, *reads] if name != context_read}
    for name in sorted(forbidden):
        for spelling in sorted(_spellings(name)):
            if re.search(rf"\b{re.escape(program)}\s+{re.escape(spelling)}\b", text):
                findings.append(
                    f"`{template}` names `{program} {spelling}`. The turn this template "
                    f"asks for is a reading: the only operation of this program it may "
                    f"name is the context read `{program} {context_read}`."
                )
    return findings


def schema_lock(repo: Repo) -> list[str]:
    """Every suite that reads the checked-in schema tree locks the same file."""
    found = _adapter(repo)
    if found is None:
        return ["`repo-policy.toml` declares no `[supervisor]` section"]
    policy, _ = found
    name = str(policy["schema_lock"])
    holders = [str(path) for path in policy["schema_lock_holders"]]

    findings: list[str] = []
    if len(holders) < 2:
        findings.append(
            "`repo-policy.toml`'s supervisor.schema_lock_holders names fewer than two "
            "suites, and a lock only one side takes serializes nothing"
        )
    for holder in holders:
        if not repo.exists(holder):
            findings.append(f"the declared schema-lock holder `{holder}` is absent")
            continue
        text = repo.read(holder)
        if name not in text:
            findings.append(
                f"`{holder}` is declared a holder of the schema lock and does not name "
                f"`{name}`. Two suites locking two different files are back to no lock "
                f"at all, and the journey that changes a checked-in schema would run "
                f"beside the suite that reads it."
            )
        if ".lock()" not in text:
            findings.append(
                f"`{holder}` names the schema lock file `{name}` and never takes the lock on it"
            )
    return findings
