"""Generated by `contract-codegen` from the checked-in contract schemas.

 This file is the Python client's walk over every operation, against a real supervisor.

 Do not edit by hand: change the contracts, regenerate with `just
 generate-clients`, and commit what that writes.

Every method this client exposes is driven against the **real**
printobserver supervisor — the program this repository builds, over the
OctoPrint `just octoprint-up` started, holding a print and a stored image
the supervisor's own ingress opened. A recording proxy sits in front of
it, so what each assertion is against is the request that supervisor
received and the answer it actually sent.

The order is the one a real machine admits: a printer is a state machine
and the policy refuses an action that is not valid from where it is. It
ends with the machine printing, where the bring-up left it.
"""

from __future__ import annotations

import json
import time
from collections.abc import Iterator
from typing import cast

import pytest
from live import PATIENCE_SECONDS, Proxy, same
from printobserver_sdk import Client, RejectedError
from printobserver_sdk.contract import JobManifest
from repo_checks.expect import equal, truth
from supervisor_world import Standing, Supervisor

#: The reason every mutating call of this walk carries.
REASON = "a generated walk is asking"


def manifest(world: Supervisor) -> JobManifest:
    """The manifest this walk writes and starts a print under.

    It narrows nothing: what the walk needs is every adjustment the envelope
    allows to be answered, and a narrowing here would refuse one for a reason
    that is not what this walk is about.
    """
    return cast(
        JobManifest,
        {
            "file_name": world.file_name,
            "material": "PLA",
            "nozzle_diameter_mm": 0.4,
            "slicer_profile": "the walk over every operation",
            "allowed": {},
            "metadata": {},
        },
    )


def ready(client: Client, print_id: str, wanted: str) -> None:
    """Wait until the machine reports the state one step needs.

    A real printer is a state machine and the policy refuses an action that is
    not valid from where it is, so a walk that went on regardless would assert
    against a machine that was somewhere else.

    Raises:
        AssertionError: If it does not, saying what it reported instead.
    """
    if not wanted:
        return
    deadline = time.monotonic() + PATIENCE_SECONDS
    last: object = "nothing was reported"
    while time.monotonic() < deadline:
        printer = client.status(print_id).get("printer")
        if printer is not None:
            last = printer["connection"]
            if last == wanted:
                return
        time.sleep(0.5)
    message = f"the machine reported {last!r} and the next step needs `{wanted}`"
    raise AssertionError(message)


@pytest.fixture(scope="module")
def world(tmp_path_factory: pytest.TempPathFactory) -> Iterator[Supervisor]:
    """A real supervisor over the scripted `OctoPrint`, held up for this module."""
    with Standing(tmp_path_factory.mktemp("live")) as supervisor:
        yield supervisor


def step_status(client: Client, world: Supervisor, proxy: Proxy) -> None:
    """`status`, answered by a real supervisor."""
    ready(client, world.print_id, "")

    answered = client.status(world.print_id)

    seen = proxy.last()
    equal(seen.method, "GET", describing="`status`")
    equal(seen.target, f"/v1/prints/{world.print_id}/status", describing="`status`")
    equal(seen.status, 200, describing="`status`")
    equal(seen.body, "", describing="what `status` sent")
    same("status", answered, seen.answer)


def step_context(client: Client, world: Supervisor, proxy: Proxy) -> None:
    """`context`, answered by a real supervisor."""
    ready(client, world.print_id, "")

    answered = client.context(world.print_id)

    seen = proxy.last()
    equal(seen.method, "GET", describing="`context`")
    equal(seen.target, f"/v1/prints/{world.print_id}/context", describing="`context`")
    equal(seen.status, 200, describing="`context`")
    equal(seen.body, "", describing="what `context` sent")
    same("context", answered, seen.answer)


def step_image(client: Client, world: Supervisor, proxy: Proxy) -> None:
    """`image`, answered by a real supervisor."""
    ready(client, world.print_id, "")

    answered = client.image(world.image_id)

    seen = proxy.last()
    equal(seen.method, "GET", describing="`image`")
    equal(seen.target, f"/v1/images/{world.image_id}", describing="`image`")
    equal(seen.status, 200, describing="`image`")
    equal(seen.body, "", describing="what `image` sent")
    same("image", answered, seen.answer)


def step_manifest_set(client: Client, world: Supervisor, proxy: Proxy) -> None:
    """`manifest_set`, answered by a real supervisor."""
    ready(client, world.print_id, "")

    answered = client.manifest_set(world.print_id, REASON, manifest(world))

    seen = proxy.last()
    equal(seen.method, "PUT", describing="`manifest_set`")
    equal(seen.target, f"/v1/prints/{world.print_id}/manifest", describing="`manifest_set`")
    equal(seen.status, 200, describing="`manifest_set`")
    sent = json.loads(seen.body)
    equal(
        sent["reason"],
        REASON,
        describing="the `reason` `manifest_set` sent",
    )
    equal(
        sent["manifest"],
        manifest(world),
        describing="the `manifest` `manifest_set` sent",
    )
    same("manifest_set", answered, seen.answer)


def step_manifest_get(client: Client, world: Supervisor, proxy: Proxy) -> None:
    """`manifest_get`, answered by a real supervisor."""
    ready(client, world.print_id, "")

    answered = client.manifest_get(world.print_id)

    seen = proxy.last()
    equal(seen.method, "GET", describing="`manifest_get`")
    equal(seen.target, f"/v1/prints/{world.print_id}/manifest", describing="`manifest_get`")
    equal(seen.status, 200, describing="`manifest_get`")
    equal(seen.body, "", describing="what `manifest_get` sent")
    same("manifest_get", answered, seen.answer)


def step_history(client: Client, world: Supervisor, proxy: Proxy) -> None:
    """`history`, answered by a real supervisor."""
    ready(client, world.print_id, "")

    answered = client.history(world.print_id, 20)

    seen = proxy.last()
    equal(seen.method, "GET", describing="`history`")
    equal(seen.target, f"/v1/prints/{world.print_id}/history?limit=20", describing="`history`")
    equal(seen.status, 200, describing="`history`")
    equal(seen.body, "", describing="what `history` sent")
    same("history", answered, seen.answer)


def step_cancel(client: Client, world: Supervisor, proxy: Proxy) -> None:
    """`cancel`, answered by a real supervisor."""
    ready(client, world.print_id, "printing")

    answered = client.cancel(world.print_id, REASON)

    seen = proxy.last()
    equal(seen.method, "POST", describing="`cancel`")
    equal(seen.target, f"/v1/prints/{world.print_id}/actions/cancel", describing="`cancel`")
    equal(seen.status, 200, describing="`cancel`")
    sent = json.loads(seen.body)
    equal(sent["actor"], "operator", describing="who `cancel` acted as")
    equal(
        sent["reason"],
        REASON,
        describing="the `reason` `cancel` sent",
    )
    same("cancel", answered, seen.answer)


def step_start_print(client: Client, world: Supervisor, proxy: Proxy) -> None:
    """`start_print`, answered by a real supervisor."""
    ready(client, world.print_id, "operational")

    answered = client.start_print(world.print_id, world.file_name, manifest(world), REASON)

    seen = proxy.last()
    equal(seen.method, "POST", describing="`start_print`")
    equal(
        seen.target, f"/v1/prints/{world.print_id}/actions/start_print", describing="`start_print`"
    )
    equal(seen.status, 200, describing="`start_print`")
    sent = json.loads(seen.body)
    equal(sent["actor"], "operator", describing="who `start_print` acted as")
    equal(
        sent["file_name"],
        world.file_name,
        describing="the `file_name` `start_print` sent",
    )
    equal(
        sent["manifest"],
        manifest(world),
        describing="the `manifest` `start_print` sent",
    )
    equal(
        sent["reason"],
        REASON,
        describing="the `reason` `start_print` sent",
    )
    same("start_print", answered, seen.answer)


def step_set_feedrate_factor(client: Client, world: Supervisor, proxy: Proxy) -> None:
    """`set_feedrate_factor`, answered by a real supervisor."""
    ready(client, world.print_id, "printing")

    answered = client.set_feedrate_factor(world.print_id, 1.1, REASON, 60)

    seen = proxy.last()
    equal(seen.method, "POST", describing="`set_feedrate_factor`")
    equal(
        seen.target,
        f"/v1/prints/{world.print_id}/actions/set_feedrate_factor",
        describing="`set_feedrate_factor`",
    )
    equal(seen.status, 200, describing="`set_feedrate_factor`")
    sent = json.loads(seen.body)
    equal(sent["actor"], "operator", describing="who `set_feedrate_factor` acted as")
    equal(
        sent["duration_s"],
        60,
        describing="the `duration_s` `set_feedrate_factor` sent",
    )
    equal(
        sent["factor"],
        1.1,
        describing="the `factor` `set_feedrate_factor` sent",
    )
    equal(
        sent["reason"],
        REASON,
        describing="the `reason` `set_feedrate_factor` sent",
    )
    same("set_feedrate_factor", answered, seen.answer)


def step_set_flowrate_factor(client: Client, world: Supervisor, proxy: Proxy) -> None:
    """`set_flowrate_factor`, answered by a real supervisor."""
    ready(client, world.print_id, "printing")

    answered = client.set_flowrate_factor(world.print_id, 1.0, REASON, 60)

    seen = proxy.last()
    equal(seen.method, "POST", describing="`set_flowrate_factor`")
    equal(
        seen.target,
        f"/v1/prints/{world.print_id}/actions/set_flowrate_factor",
        describing="`set_flowrate_factor`",
    )
    equal(seen.status, 200, describing="`set_flowrate_factor`")
    sent = json.loads(seen.body)
    equal(sent["actor"], "operator", describing="who `set_flowrate_factor` acted as")
    equal(
        sent["duration_s"],
        60,
        describing="the `duration_s` `set_flowrate_factor` sent",
    )
    equal(
        sent["factor"],
        1.0,
        describing="the `factor` `set_flowrate_factor` sent",
    )
    equal(
        sent["reason"],
        REASON,
        describing="the `reason` `set_flowrate_factor` sent",
    )
    same("set_flowrate_factor", answered, seen.answer)


def step_set_fan_percent(client: Client, world: Supervisor, proxy: Proxy) -> None:
    """`set_fan_percent`, answered by a real supervisor."""
    ready(client, world.print_id, "printing")

    answered = client.set_fan_percent(world.print_id, 50.0, REASON, 60)

    seen = proxy.last()
    equal(seen.method, "POST", describing="`set_fan_percent`")
    equal(
        seen.target,
        f"/v1/prints/{world.print_id}/actions/set_fan_percent",
        describing="`set_fan_percent`",
    )
    equal(seen.status, 200, describing="`set_fan_percent`")
    sent = json.loads(seen.body)
    equal(sent["actor"], "operator", describing="who `set_fan_percent` acted as")
    equal(
        sent["duration_s"],
        60,
        describing="the `duration_s` `set_fan_percent` sent",
    )
    equal(
        sent["percent"],
        50.0,
        describing="the `percent` `set_fan_percent` sent",
    )
    equal(
        sent["reason"],
        REASON,
        describing="the `reason` `set_fan_percent` sent",
    )
    same("set_fan_percent", answered, seen.answer)


def step_set_tool_target_c(client: Client, world: Supervisor, proxy: Proxy) -> None:
    """`set_tool_target_c`, answered by a real supervisor."""
    ready(client, world.print_id, "printing")

    answered = client.set_tool_target_c(world.print_id, REASON, 210.0, 0, 60)

    seen = proxy.last()
    equal(seen.method, "POST", describing="`set_tool_target_c`")
    equal(
        seen.target,
        f"/v1/prints/{world.print_id}/actions/set_tool_target_c",
        describing="`set_tool_target_c`",
    )
    equal(seen.status, 200, describing="`set_tool_target_c`")
    sent = json.loads(seen.body)
    equal(sent["actor"], "operator", describing="who `set_tool_target_c` acted as")
    equal(
        sent["duration_s"],
        60,
        describing="the `duration_s` `set_tool_target_c` sent",
    )
    equal(
        sent["reason"],
        REASON,
        describing="the `reason` `set_tool_target_c` sent",
    )
    equal(
        sent["target_c"],
        210.0,
        describing="the `target_c` `set_tool_target_c` sent",
    )
    equal(
        sent["tool"],
        0,
        describing="the `tool` `set_tool_target_c` sent",
    )
    same("set_tool_target_c", answered, seen.answer)


def step_set_bed_target_c(client: Client, world: Supervisor, proxy: Proxy) -> None:
    """`set_bed_target_c`, answered by a real supervisor."""
    ready(client, world.print_id, "printing")

    answered = client.set_bed_target_c(world.print_id, REASON, 60.0, 60)

    seen = proxy.last()
    equal(seen.method, "POST", describing="`set_bed_target_c`")
    equal(
        seen.target,
        f"/v1/prints/{world.print_id}/actions/set_bed_target_c",
        describing="`set_bed_target_c`",
    )
    equal(seen.status, 200, describing="`set_bed_target_c`")
    sent = json.loads(seen.body)
    equal(sent["actor"], "operator", describing="who `set_bed_target_c` acted as")
    equal(
        sent["duration_s"],
        60,
        describing="the `duration_s` `set_bed_target_c` sent",
    )
    equal(
        sent["reason"],
        REASON,
        describing="the `reason` `set_bed_target_c` sent",
    )
    equal(
        sent["target_c"],
        60.0,
        describing="the `target_c` `set_bed_target_c` sent",
    )
    same("set_bed_target_c", answered, seen.answer)


def step_acknowledge_failure(client: Client, world: Supervisor, proxy: Proxy) -> None:
    """`acknowledge_failure`, answered by a real supervisor."""
    ready(client, world.print_id, "")

    answered = client.acknowledge_failure(world.print_id, "continue", world.event_id, REASON)

    seen = proxy.last()
    equal(seen.method, "POST", describing="`acknowledge_failure`")
    equal(
        seen.target,
        f"/v1/prints/{world.print_id}/actions/acknowledge_failure",
        describing="`acknowledge_failure`",
    )
    equal(seen.status, 200, describing="`acknowledge_failure`")
    sent = json.loads(seen.body)
    equal(sent["actor"], "operator", describing="who `acknowledge_failure` acted as")
    equal(
        sent["disposition"],
        "continue",
        describing="the `disposition` `acknowledge_failure` sent",
    )
    equal(
        sent["event_id"],
        world.event_id,
        describing="the `event_id` `acknowledge_failure` sent",
    )
    equal(
        sent["reason"],
        REASON,
        describing="the `reason` `acknowledge_failure` sent",
    )
    same("acknowledge_failure", answered, seen.answer)


def step_pause(client: Client, world: Supervisor, proxy: Proxy) -> None:
    """`pause`, answered by a real supervisor."""
    ready(client, world.print_id, "printing")

    answered = client.pause(world.print_id, REASON)

    seen = proxy.last()
    equal(seen.method, "POST", describing="`pause`")
    equal(seen.target, f"/v1/prints/{world.print_id}/actions/pause", describing="`pause`")
    equal(seen.status, 200, describing="`pause`")
    sent = json.loads(seen.body)
    equal(sent["actor"], "operator", describing="who `pause` acted as")
    equal(
        sent["reason"],
        REASON,
        describing="the `reason` `pause` sent",
    )
    same("pause", answered, seen.answer)


def step_resume(client: Client, world: Supervisor, proxy: Proxy) -> None:
    """`resume`, answered by a real supervisor."""
    ready(client, world.print_id, "paused")

    answered = client.resume(world.print_id, REASON)

    seen = proxy.last()
    equal(seen.method, "POST", describing="`resume`")
    equal(seen.target, f"/v1/prints/{world.print_id}/actions/resume", describing="`resume`")
    equal(seen.status, 200, describing="`resume`")
    sent = json.loads(seen.body)
    equal(sent["actor"], "operator", describing="who `resume` acted as")
    equal(
        sent["reason"],
        REASON,
        describing="the `reason` `resume` sent",
    )
    same("resume", answered, seen.answer)


def test_every_method_is_answered_by_a_real_supervisor(world: Supervisor) -> None:
    """Every method, answered by a real supervisor, in the one order it admits."""
    with Proxy(world.server) as proxy:
        client = Client(proxy.url, "operator")
        step_status(client, world, proxy)
        step_context(client, world, proxy)
        step_image(client, world, proxy)
        step_manifest_set(client, world, proxy)
        step_manifest_get(client, world, proxy)
        step_history(client, world, proxy)
        step_cancel(client, world, proxy)
        step_start_print(client, world, proxy)
        step_set_feedrate_factor(client, world, proxy)
        step_set_flowrate_factor(client, world, proxy)
        step_set_fan_percent(client, world, proxy)
        step_set_tool_target_c(client, world, proxy)
        step_set_bed_target_c(client, world, proxy)
        step_acknowledge_failure(client, world, proxy)
        step_pause(client, world, proxy)
        step_resume(client, world, proxy)

        truth(
            proxy.calls() >= 16,
            describing="every call to have gone through the proxy",
        )


def refused_cancel(client: Client, world: Supervisor, proxy: Proxy) -> None:
    """`cancel`, refused by a real supervisor's own policy."""
    try:
        client.cancel(world.print_id, REASON)
    except RejectedError as refused:
        truth(
            isinstance(refused.reason, dict) and "actor_may_not_request" in refused.reason,
            describing="`cancel` to be refused for the grant",
        )
        seen = proxy.last()
        equal(seen.status, 409, describing="`cancel`")
        same("cancel", refused.answer, seen.answer)
    else:
        truth(False, describing="`cancel` to be refused")


def refused_start_print(client: Client, world: Supervisor, proxy: Proxy) -> None:
    """`start_print`, refused by a real supervisor's own policy."""
    try:
        client.start_print(world.print_id, world.file_name, manifest(world), REASON)
    except RejectedError as refused:
        truth(
            isinstance(refused.reason, dict) and "actor_may_not_request" in refused.reason,
            describing="`start_print` to be refused for the grant",
        )
        seen = proxy.last()
        equal(seen.status, 409, describing="`start_print`")
        same("start_print", refused.answer, seen.answer)
    else:
        truth(False, describing="`start_print` to be refused")


def refused_set_feedrate_factor(client: Client, world: Supervisor, proxy: Proxy) -> None:
    """`set_feedrate_factor`, refused by a real supervisor's own policy."""
    try:
        client.set_feedrate_factor(world.print_id, 1.1, REASON, 60)
    except RejectedError as refused:
        truth(
            isinstance(refused.reason, dict) and "actor_may_not_request" in refused.reason,
            describing="`set_feedrate_factor` to be refused for the grant",
        )
        seen = proxy.last()
        equal(seen.status, 409, describing="`set_feedrate_factor`")
        same("set_feedrate_factor", refused.answer, seen.answer)
    else:
        truth(False, describing="`set_feedrate_factor` to be refused")


def refused_set_flowrate_factor(client: Client, world: Supervisor, proxy: Proxy) -> None:
    """`set_flowrate_factor`, refused by a real supervisor's own policy."""
    try:
        client.set_flowrate_factor(world.print_id, 1.0, REASON, 60)
    except RejectedError as refused:
        truth(
            isinstance(refused.reason, dict) and "actor_may_not_request" in refused.reason,
            describing="`set_flowrate_factor` to be refused for the grant",
        )
        seen = proxy.last()
        equal(seen.status, 409, describing="`set_flowrate_factor`")
        same("set_flowrate_factor", refused.answer, seen.answer)
    else:
        truth(False, describing="`set_flowrate_factor` to be refused")


def refused_set_fan_percent(client: Client, world: Supervisor, proxy: Proxy) -> None:
    """`set_fan_percent`, refused by a real supervisor's own policy."""
    try:
        client.set_fan_percent(world.print_id, 50.0, REASON, 60)
    except RejectedError as refused:
        truth(
            isinstance(refused.reason, dict) and "actor_may_not_request" in refused.reason,
            describing="`set_fan_percent` to be refused for the grant",
        )
        seen = proxy.last()
        equal(seen.status, 409, describing="`set_fan_percent`")
        same("set_fan_percent", refused.answer, seen.answer)
    else:
        truth(False, describing="`set_fan_percent` to be refused")


def refused_set_tool_target_c(client: Client, world: Supervisor, proxy: Proxy) -> None:
    """`set_tool_target_c`, refused by a real supervisor's own policy."""
    try:
        client.set_tool_target_c(world.print_id, REASON, 210.0, 0, 60)
    except RejectedError as refused:
        truth(
            isinstance(refused.reason, dict) and "actor_may_not_request" in refused.reason,
            describing="`set_tool_target_c` to be refused for the grant",
        )
        seen = proxy.last()
        equal(seen.status, 409, describing="`set_tool_target_c`")
        same("set_tool_target_c", refused.answer, seen.answer)
    else:
        truth(False, describing="`set_tool_target_c` to be refused")


def refused_set_bed_target_c(client: Client, world: Supervisor, proxy: Proxy) -> None:
    """`set_bed_target_c`, refused by a real supervisor's own policy."""
    try:
        client.set_bed_target_c(world.print_id, REASON, 60.0, 60)
    except RejectedError as refused:
        truth(
            isinstance(refused.reason, dict) and "actor_may_not_request" in refused.reason,
            describing="`set_bed_target_c` to be refused for the grant",
        )
        seen = proxy.last()
        equal(seen.status, 409, describing="`set_bed_target_c`")
        same("set_bed_target_c", refused.answer, seen.answer)
    else:
        truth(False, describing="`set_bed_target_c` to be refused")


def refused_acknowledge_failure(client: Client, world: Supervisor, proxy: Proxy) -> None:
    """`acknowledge_failure`, refused by a real supervisor's own policy."""
    try:
        client.acknowledge_failure(world.print_id, "continue", world.event_id, REASON)
    except RejectedError as refused:
        truth(
            isinstance(refused.reason, dict) and "actor_may_not_request" in refused.reason,
            describing="`acknowledge_failure` to be refused for the grant",
        )
        seen = proxy.last()
        equal(seen.status, 409, describing="`acknowledge_failure`")
        same("acknowledge_failure", refused.answer, seen.answer)
    else:
        truth(False, describing="`acknowledge_failure` to be refused")


def refused_pause(client: Client, world: Supervisor, proxy: Proxy) -> None:
    """`pause`, refused by a real supervisor's own policy."""
    try:
        client.pause(world.print_id, REASON)
    except RejectedError as refused:
        truth(
            isinstance(refused.reason, dict) and "actor_may_not_request" in refused.reason,
            describing="`pause` to be refused for the grant",
        )
        seen = proxy.last()
        equal(seen.status, 409, describing="`pause`")
        same("pause", refused.answer, seen.answer)
    else:
        truth(False, describing="`pause` to be refused")


def refused_resume(client: Client, world: Supervisor, proxy: Proxy) -> None:
    """`resume`, refused by a real supervisor's own policy."""
    try:
        client.resume(world.print_id, REASON)
    except RejectedError as refused:
        truth(
            isinstance(refused.reason, dict) and "actor_may_not_request" in refused.reason,
            describing="`resume` to be refused for the grant",
        )
        seen = proxy.last()
        equal(seen.status, 409, describing="`resume`")
        same("resume", refused.answer, seen.answer)
    else:
        truth(False, describing="`resume` to be refused")


def test_every_action_is_refused_as_a_typed_rejection(world: Supervisor) -> None:
    """Every action, refused by a real supervisor's own policy, typed.

    One client acting as an actor class the envelope grants nothing. The policy
    takes that decision before it looks at the state, the interval or the
    bounds, so every action is refused from wherever the machine happens to be.
    """
    with Proxy(world.server) as proxy:
        client = Client(
            proxy.url,
            {"agent": {"session_name": "an actor this envelope grants nothing"}},
        )
        refused_cancel(client, world, proxy)
        refused_start_print(client, world, proxy)
        refused_set_feedrate_factor(client, world, proxy)
        refused_set_flowrate_factor(client, world, proxy)
        refused_set_fan_percent(client, world, proxy)
        refused_set_tool_target_c(client, world, proxy)
        refused_set_bed_target_c(client, world, proxy)
        refused_acknowledge_failure(client, world, proxy)
        refused_pause(client, world, proxy)
        refused_resume(client, world, proxy)
