//! Generated by `contract-codegen` from the checked-in contract schemas.
//!
//! This file is the Rust client's walk over every operation, against a real supervisor.
//!
//! Do not edit by hand: change the contracts, regenerate with `just
//! generate-clients`, and commit what that writes.
//!
//! Every method this client exposes is driven against the **real**
//! printobserver supervisor — the program this repository builds, over the
//! `OctoPrint` `just octoprint-up` started, holding a print and a stored
//! image the supervisor's own ingress opened. A recording proxy sits in front
//! of it, so what each assertion is against is the request that supervisor
//! received and the answer it actually sent.
//!
//! The order is the one a real machine admits: a printer is a state machine
//! and the policy refuses an action that is not valid from where it is. It
//! ends with the machine printing, where the bring-up left it.

#[path = "support/live.rs"]
mod live;
#[path = "support/supervisor.rs"]
mod supervisor;

use std::collections::BTreeMap;

use printobserver_sdk::{Actor, Client, ClientError, JobManifest, RejectionReason};

/// The reason every mutating call of this walk carries.
const REASON: &str = "a generated walk is asking";

/// How long the machine is given to reach a state a step needs.
const PATIENCE: std::time::Duration = std::time::Duration::from_secs(180);

/// The manifest this walk writes and starts a print under.
///
/// It narrows nothing: what the walk needs is every adjustment the envelope
/// allows to be answered, and a narrowing here would refuse one for a reason
/// that is not what this walk is about.
fn manifest(file_name: &str) -> JobManifest {
    JobManifest {
        file_name: file_name.to_owned(),
        material: "PLA".to_owned(),
        nozzle_diameter_mm: 0.4,
        slicer_profile: "the all-operation walk's own profile".to_owned(),
        allowed: BTreeMap::new(),
        metadata: BTreeMap::new(),
    }
}

/// Wait until the machine reports the state one step needs.
///
/// A real printer is a state machine and the policy refuses an action that is
/// not valid from where it is, so a walk that went on regardless would assert
/// against a machine that was somewhere else.
///
/// # Panics
///
/// Panics saying what it reported instead.
fn ready(client: &Client, print_id: &str, wanted: &str) {
    if wanted.is_empty() {
        return;
    }
    let deadline = std::time::Instant::now() + PATIENCE;
    let mut last = String::from("nothing was reported");
    while std::time::Instant::now() < deadline {
        let status = client.status(print_id).expect("a status read is answered");
        if let Some(printer) = status.printer {
            last = serde_json::to_string(&printer.connection).unwrap_or_default();
            if last.trim_matches('"') == wanted {
                return;
            }
        }
        std::thread::sleep(std::time::Duration::from_millis(500));
    }
    panic!("the machine reported {last} and the next step needs `{wanted}`");
}

/// `status`, answered by a real supervisor.
fn step_status(client: &Client, world: &supervisor::Supervisor, proxy: &live::Proxy) {
    ready(client, &world.print_id, "");

    let answered = client
        .status(&world.print_id)
        .expect("`status` is answered by a real supervisor");

    let seen = proxy.last();
    assert_eq!(seen.method, "GET", "`status`");
    assert_eq!(
        seen.target,
        format!("/v1/prints/{print_id}/status", print_id = world.print_id),
        "`status`"
    );
    assert_eq!(seen.status, 200, "`status`");
    assert_eq!(seen.body, "", "`status` sends no body");
    live::same("status", &answered, &seen.answer);
}

/// `context`, answered by a real supervisor.
fn step_context(client: &Client, world: &supervisor::Supervisor, proxy: &live::Proxy) {
    ready(client, &world.print_id, "");

    let answered = client
        .context(&world.print_id)
        .expect("`context` is answered by a real supervisor");

    let seen = proxy.last();
    assert_eq!(seen.method, "GET", "`context`");
    assert_eq!(
        seen.target,
        format!("/v1/prints/{print_id}/context", print_id = world.print_id),
        "`context`"
    );
    assert_eq!(seen.status, 200, "`context`");
    assert_eq!(seen.body, "", "`context` sends no body");
    live::same("context", &answered, &seen.answer);
}

/// `image`, answered by a real supervisor.
fn step_image(client: &Client, world: &supervisor::Supervisor, proxy: &live::Proxy) {
    ready(client, &world.print_id, "");

    let answered = client
        .image(&world.image_id)
        .expect("`image` is answered by a real supervisor");

    let seen = proxy.last();
    assert_eq!(seen.method, "GET", "`image`");
    assert_eq!(
        seen.target,
        format!("/v1/images/{image_id}", image_id = world.image_id),
        "`image`"
    );
    assert_eq!(seen.status, 200, "`image`");
    assert_eq!(seen.body, "", "`image` sends no body");
    live::same("image", &answered, &seen.answer);
}

/// `manifest_set`, answered by a real supervisor.
fn step_manifest_set(
    client: &Client,
    world: &supervisor::Supervisor,
    proxy: &live::Proxy,
    manifest: &printobserver_sdk::JobManifest,
) {
    ready(client, &world.print_id, "");

    let answered = client
        .manifest_set(&world.print_id, REASON, manifest)
        .expect("`manifest_set` is answered by a real supervisor");

    let seen = proxy.last();
    assert_eq!(seen.method, "PUT", "`manifest_set`");
    assert_eq!(
        seen.target,
        format!("/v1/prints/{print_id}/manifest", print_id = world.print_id),
        "`manifest_set`"
    );
    assert_eq!(seen.status, 200, "`manifest_set`");
    let sent: serde_json::Value =
        serde_json::from_str(&seen.body).expect("the supervisor received a document");
    assert_eq!(
        sent["reason"],
        serde_json::to_value(REASON).expect("a value renders"),
        "`manifest_set` sent another `reason`"
    );
    assert_eq!(
        sent["manifest"],
        serde_json::to_value(manifest).expect("a value renders"),
        "`manifest_set` sent another `manifest`"
    );
    live::same("manifest_set", &answered, &seen.answer);
}

/// `manifest_get`, answered by a real supervisor.
fn step_manifest_get(client: &Client, world: &supervisor::Supervisor, proxy: &live::Proxy) {
    ready(client, &world.print_id, "");

    let answered = client
        .manifest_get(&world.print_id)
        .expect("`manifest_get` is answered by a real supervisor");

    let seen = proxy.last();
    assert_eq!(seen.method, "GET", "`manifest_get`");
    assert_eq!(
        seen.target,
        format!("/v1/prints/{print_id}/manifest", print_id = world.print_id),
        "`manifest_get`"
    );
    assert_eq!(seen.status, 200, "`manifest_get`");
    assert_eq!(seen.body, "", "`manifest_get` sends no body");
    live::same("manifest_get", &answered, &seen.answer);
}

/// `history`, answered by a real supervisor.
fn step_history(client: &Client, world: &supervisor::Supervisor, proxy: &live::Proxy) {
    ready(client, &world.print_id, "");

    let answered = client
        .history(&world.print_id, Some(20))
        .expect("`history` is answered by a real supervisor");

    let seen = proxy.last();
    assert_eq!(seen.method, "GET", "`history`");
    assert_eq!(
        seen.target,
        format!(
            "/v1/prints/{print_id}/history?limit=20",
            print_id = world.print_id
        ),
        "`history`"
    );
    assert_eq!(seen.status, 200, "`history`");
    assert_eq!(seen.body, "", "`history` sends no body");
    live::same("history", &answered, &seen.answer);
}

/// `cancel`, answered by a real supervisor.
fn step_cancel(client: &Client, world: &supervisor::Supervisor, proxy: &live::Proxy) {
    ready(client, &world.print_id, "printing");

    let answered = client
        .cancel(&world.print_id, REASON)
        .expect("`cancel` is answered by a real supervisor");

    let seen = proxy.last();
    assert_eq!(seen.method, "POST", "`cancel`");
    assert_eq!(
        seen.target,
        format!(
            "/v1/prints/{print_id}/actions/cancel",
            print_id = world.print_id
        ),
        "`cancel`"
    );
    assert_eq!(seen.status, 200, "`cancel`");
    let sent: serde_json::Value =
        serde_json::from_str(&seen.body).expect("the supervisor received a document");
    assert_eq!(sent["actor"], serde_json::json!("operator"), "`cancel`");
    assert_eq!(
        sent["reason"],
        serde_json::to_value(REASON).expect("a value renders"),
        "`cancel` sent another `reason`"
    );
    live::same("cancel", &answered, &seen.answer);
}

/// `start_print`, answered by a real supervisor.
fn step_start_print(
    client: &Client,
    world: &supervisor::Supervisor,
    proxy: &live::Proxy,
    manifest: &printobserver_sdk::JobManifest,
) {
    ready(client, &world.print_id, "operational");

    let answered = client
        .start_print(&world.print_id, &world.file_name, manifest, REASON)
        .expect("`start_print` is answered by a real supervisor");

    let seen = proxy.last();
    assert_eq!(seen.method, "POST", "`start_print`");
    assert_eq!(
        seen.target,
        format!(
            "/v1/prints/{print_id}/actions/start_print",
            print_id = world.print_id
        ),
        "`start_print`"
    );
    assert_eq!(seen.status, 200, "`start_print`");
    let sent: serde_json::Value =
        serde_json::from_str(&seen.body).expect("the supervisor received a document");
    assert_eq!(
        sent["actor"],
        serde_json::json!("operator"),
        "`start_print`"
    );
    assert_eq!(
        sent["file_name"],
        serde_json::to_value(&world.file_name).expect("a value renders"),
        "`start_print` sent another `file_name`"
    );
    assert_eq!(
        sent["manifest"],
        serde_json::to_value(manifest).expect("a value renders"),
        "`start_print` sent another `manifest`"
    );
    assert_eq!(
        sent["reason"],
        serde_json::to_value(REASON).expect("a value renders"),
        "`start_print` sent another `reason`"
    );
    live::same("start_print", &answered, &seen.answer);
}

/// `set_feedrate_factor`, answered by a real supervisor.
fn step_set_feedrate_factor(client: &Client, world: &supervisor::Supervisor, proxy: &live::Proxy) {
    ready(client, &world.print_id, "printing");

    let answered = client
        .set_feedrate_factor(&world.print_id, 1.1, REASON, Some(60))
        .expect("`set_feedrate_factor` is answered by a real supervisor");

    let seen = proxy.last();
    assert_eq!(seen.method, "POST", "`set_feedrate_factor`");
    assert_eq!(
        seen.target,
        format!(
            "/v1/prints/{print_id}/actions/set_feedrate_factor",
            print_id = world.print_id
        ),
        "`set_feedrate_factor`"
    );
    assert_eq!(seen.status, 200, "`set_feedrate_factor`");
    let sent: serde_json::Value =
        serde_json::from_str(&seen.body).expect("the supervisor received a document");
    assert_eq!(
        sent["actor"],
        serde_json::json!("operator"),
        "`set_feedrate_factor`"
    );
    assert_eq!(
        sent["duration_s"],
        serde_json::to_value(60).expect("a value renders"),
        "`set_feedrate_factor` sent another `duration_s`"
    );
    assert_eq!(
        sent["factor"],
        serde_json::to_value(1.1).expect("a value renders"),
        "`set_feedrate_factor` sent another `factor`"
    );
    assert_eq!(
        sent["reason"],
        serde_json::to_value(REASON).expect("a value renders"),
        "`set_feedrate_factor` sent another `reason`"
    );
    live::same("set_feedrate_factor", &answered, &seen.answer);
}

/// `set_flowrate_factor`, answered by a real supervisor.
fn step_set_flowrate_factor(client: &Client, world: &supervisor::Supervisor, proxy: &live::Proxy) {
    ready(client, &world.print_id, "printing");

    let answered = client
        .set_flowrate_factor(&world.print_id, 1.0, REASON, Some(60))
        .expect("`set_flowrate_factor` is answered by a real supervisor");

    let seen = proxy.last();
    assert_eq!(seen.method, "POST", "`set_flowrate_factor`");
    assert_eq!(
        seen.target,
        format!(
            "/v1/prints/{print_id}/actions/set_flowrate_factor",
            print_id = world.print_id
        ),
        "`set_flowrate_factor`"
    );
    assert_eq!(seen.status, 200, "`set_flowrate_factor`");
    let sent: serde_json::Value =
        serde_json::from_str(&seen.body).expect("the supervisor received a document");
    assert_eq!(
        sent["actor"],
        serde_json::json!("operator"),
        "`set_flowrate_factor`"
    );
    assert_eq!(
        sent["duration_s"],
        serde_json::to_value(60).expect("a value renders"),
        "`set_flowrate_factor` sent another `duration_s`"
    );
    assert_eq!(
        sent["factor"],
        serde_json::to_value(1.0).expect("a value renders"),
        "`set_flowrate_factor` sent another `factor`"
    );
    assert_eq!(
        sent["reason"],
        serde_json::to_value(REASON).expect("a value renders"),
        "`set_flowrate_factor` sent another `reason`"
    );
    live::same("set_flowrate_factor", &answered, &seen.answer);
}

/// `set_fan_percent`, answered by a real supervisor.
fn step_set_fan_percent(client: &Client, world: &supervisor::Supervisor, proxy: &live::Proxy) {
    ready(client, &world.print_id, "printing");

    let answered = client
        .set_fan_percent(&world.print_id, 50.0, REASON, Some(60))
        .expect("`set_fan_percent` is answered by a real supervisor");

    let seen = proxy.last();
    assert_eq!(seen.method, "POST", "`set_fan_percent`");
    assert_eq!(
        seen.target,
        format!(
            "/v1/prints/{print_id}/actions/set_fan_percent",
            print_id = world.print_id
        ),
        "`set_fan_percent`"
    );
    assert_eq!(seen.status, 200, "`set_fan_percent`");
    let sent: serde_json::Value =
        serde_json::from_str(&seen.body).expect("the supervisor received a document");
    assert_eq!(
        sent["actor"],
        serde_json::json!("operator"),
        "`set_fan_percent`"
    );
    assert_eq!(
        sent["duration_s"],
        serde_json::to_value(60).expect("a value renders"),
        "`set_fan_percent` sent another `duration_s`"
    );
    assert_eq!(
        sent["percent"],
        serde_json::to_value(50.0).expect("a value renders"),
        "`set_fan_percent` sent another `percent`"
    );
    assert_eq!(
        sent["reason"],
        serde_json::to_value(REASON).expect("a value renders"),
        "`set_fan_percent` sent another `reason`"
    );
    live::same("set_fan_percent", &answered, &seen.answer);
}

/// `set_tool_target_c`, answered by a real supervisor.
fn step_set_tool_target_c(client: &Client, world: &supervisor::Supervisor, proxy: &live::Proxy) {
    ready(client, &world.print_id, "printing");

    let answered = client
        .set_tool_target_c(&world.print_id, REASON, 210.0, 0, Some(60))
        .expect("`set_tool_target_c` is answered by a real supervisor");

    let seen = proxy.last();
    assert_eq!(seen.method, "POST", "`set_tool_target_c`");
    assert_eq!(
        seen.target,
        format!(
            "/v1/prints/{print_id}/actions/set_tool_target_c",
            print_id = world.print_id
        ),
        "`set_tool_target_c`"
    );
    assert_eq!(seen.status, 200, "`set_tool_target_c`");
    let sent: serde_json::Value =
        serde_json::from_str(&seen.body).expect("the supervisor received a document");
    assert_eq!(
        sent["actor"],
        serde_json::json!("operator"),
        "`set_tool_target_c`"
    );
    assert_eq!(
        sent["duration_s"],
        serde_json::to_value(60).expect("a value renders"),
        "`set_tool_target_c` sent another `duration_s`"
    );
    assert_eq!(
        sent["reason"],
        serde_json::to_value(REASON).expect("a value renders"),
        "`set_tool_target_c` sent another `reason`"
    );
    assert_eq!(
        sent["target_c"],
        serde_json::to_value(210.0).expect("a value renders"),
        "`set_tool_target_c` sent another `target_c`"
    );
    assert_eq!(
        sent["tool"],
        serde_json::to_value(0).expect("a value renders"),
        "`set_tool_target_c` sent another `tool`"
    );
    live::same("set_tool_target_c", &answered, &seen.answer);
}

/// `set_bed_target_c`, answered by a real supervisor.
fn step_set_bed_target_c(client: &Client, world: &supervisor::Supervisor, proxy: &live::Proxy) {
    ready(client, &world.print_id, "printing");

    let answered = client
        .set_bed_target_c(&world.print_id, REASON, 60.0, Some(60))
        .expect("`set_bed_target_c` is answered by a real supervisor");

    let seen = proxy.last();
    assert_eq!(seen.method, "POST", "`set_bed_target_c`");
    assert_eq!(
        seen.target,
        format!(
            "/v1/prints/{print_id}/actions/set_bed_target_c",
            print_id = world.print_id
        ),
        "`set_bed_target_c`"
    );
    assert_eq!(seen.status, 200, "`set_bed_target_c`");
    let sent: serde_json::Value =
        serde_json::from_str(&seen.body).expect("the supervisor received a document");
    assert_eq!(
        sent["actor"],
        serde_json::json!("operator"),
        "`set_bed_target_c`"
    );
    assert_eq!(
        sent["duration_s"],
        serde_json::to_value(60).expect("a value renders"),
        "`set_bed_target_c` sent another `duration_s`"
    );
    assert_eq!(
        sent["reason"],
        serde_json::to_value(REASON).expect("a value renders"),
        "`set_bed_target_c` sent another `reason`"
    );
    assert_eq!(
        sent["target_c"],
        serde_json::to_value(60.0).expect("a value renders"),
        "`set_bed_target_c` sent another `target_c`"
    );
    live::same("set_bed_target_c", &answered, &seen.answer);
}

/// `acknowledge_failure`, answered by a real supervisor.
fn step_acknowledge_failure(client: &Client, world: &supervisor::Supervisor, proxy: &live::Proxy) {
    ready(client, &world.print_id, "");

    let answered = client
        .acknowledge_failure(
            &world.print_id,
            &printobserver_sdk::AcknowledgementDisposition::Continue,
            &world.event_id,
            REASON,
        )
        .expect("`acknowledge_failure` is answered by a real supervisor");

    let seen = proxy.last();
    assert_eq!(seen.method, "POST", "`acknowledge_failure`");
    assert_eq!(
        seen.target,
        format!(
            "/v1/prints/{print_id}/actions/acknowledge_failure",
            print_id = world.print_id
        ),
        "`acknowledge_failure`"
    );
    assert_eq!(seen.status, 200, "`acknowledge_failure`");
    let sent: serde_json::Value =
        serde_json::from_str(&seen.body).expect("the supervisor received a document");
    assert_eq!(
        sent["actor"],
        serde_json::json!("operator"),
        "`acknowledge_failure`"
    );
    assert_eq!(
        sent["disposition"],
        serde_json::to_value(printobserver_sdk::AcknowledgementDisposition::Continue)
            .expect("a value renders"),
        "`acknowledge_failure` sent another `disposition`"
    );
    assert_eq!(
        sent["event_id"],
        serde_json::to_value(&world.event_id).expect("a value renders"),
        "`acknowledge_failure` sent another `event_id`"
    );
    assert_eq!(
        sent["reason"],
        serde_json::to_value(REASON).expect("a value renders"),
        "`acknowledge_failure` sent another `reason`"
    );
    live::same("acknowledge_failure", &answered, &seen.answer);
}

/// `pause`, answered by a real supervisor.
fn step_pause(client: &Client, world: &supervisor::Supervisor, proxy: &live::Proxy) {
    ready(client, &world.print_id, "printing");

    let answered = client
        .pause(&world.print_id, REASON)
        .expect("`pause` is answered by a real supervisor");

    let seen = proxy.last();
    assert_eq!(seen.method, "POST", "`pause`");
    assert_eq!(
        seen.target,
        format!(
            "/v1/prints/{print_id}/actions/pause",
            print_id = world.print_id
        ),
        "`pause`"
    );
    assert_eq!(seen.status, 200, "`pause`");
    let sent: serde_json::Value =
        serde_json::from_str(&seen.body).expect("the supervisor received a document");
    assert_eq!(sent["actor"], serde_json::json!("operator"), "`pause`");
    assert_eq!(
        sent["reason"],
        serde_json::to_value(REASON).expect("a value renders"),
        "`pause` sent another `reason`"
    );
    live::same("pause", &answered, &seen.answer);
}

/// `resume`, answered by a real supervisor.
fn step_resume(client: &Client, world: &supervisor::Supervisor, proxy: &live::Proxy) {
    ready(client, &world.print_id, "paused");

    let answered = client
        .resume(&world.print_id, REASON)
        .expect("`resume` is answered by a real supervisor");

    let seen = proxy.last();
    assert_eq!(seen.method, "POST", "`resume`");
    assert_eq!(
        seen.target,
        format!(
            "/v1/prints/{print_id}/actions/resume",
            print_id = world.print_id
        ),
        "`resume`"
    );
    assert_eq!(seen.status, 200, "`resume`");
    let sent: serde_json::Value =
        serde_json::from_str(&seen.body).expect("the supervisor received a document");
    assert_eq!(sent["actor"], serde_json::json!("operator"), "`resume`");
    assert_eq!(
        sent["reason"],
        serde_json::to_value(REASON).expect("a value renders"),
        "`resume` sent another `reason`"
    );
    live::same("resume", &answered, &seen.answer);
}

/// `cancel`, refused by a real supervisor's own policy.
fn refused_cancel(client: &Client, world: &supervisor::Supervisor, proxy: &live::Proxy) {
    let refused = client
        .cancel(&world.print_id, REASON)
        .expect_err("`cancel` is refused for an actor granted nothing");

    let ClientError::Rejected(rejection) = refused else {
        panic!("`cancel`: the refusal did not arrive as a rejection");
    };
    assert!(
        matches!(rejection.reason, RejectionReason::ActorMayNotRequest { .. }),
        "`cancel` was refused for something other than the grant: {:?}",
        rejection.reason
    );
    let seen = proxy.last();
    assert_eq!(seen.status, 409, "`cancel`");
    live::same("cancel", rejection.answer.as_ref(), &seen.answer);
}

/// `start_print`, refused by a real supervisor's own policy.
fn refused_start_print(
    client: &Client,
    world: &supervisor::Supervisor,
    proxy: &live::Proxy,
    manifest: &printobserver_sdk::JobManifest,
) {
    let refused = client
        .start_print(&world.print_id, &world.file_name, manifest, REASON)
        .expect_err("`start_print` is refused for an actor granted nothing");

    let ClientError::Rejected(rejection) = refused else {
        panic!("`start_print`: the refusal did not arrive as a rejection");
    };
    assert!(
        matches!(rejection.reason, RejectionReason::ActorMayNotRequest { .. }),
        "`start_print` was refused for something other than the grant: {:?}",
        rejection.reason
    );
    let seen = proxy.last();
    assert_eq!(seen.status, 409, "`start_print`");
    live::same("start_print", rejection.answer.as_ref(), &seen.answer);
}

/// `set_feedrate_factor`, refused by a real supervisor's own policy.
fn refused_set_feedrate_factor(
    client: &Client,
    world: &supervisor::Supervisor,
    proxy: &live::Proxy,
) {
    let refused = client
        .set_feedrate_factor(&world.print_id, 1.1, REASON, Some(60))
        .expect_err("`set_feedrate_factor` is refused for an actor granted nothing");

    let ClientError::Rejected(rejection) = refused else {
        panic!("`set_feedrate_factor`: the refusal did not arrive as a rejection");
    };
    assert!(
        matches!(rejection.reason, RejectionReason::ActorMayNotRequest { .. }),
        "`set_feedrate_factor` was refused for something other than the grant: {:?}",
        rejection.reason
    );
    let seen = proxy.last();
    assert_eq!(seen.status, 409, "`set_feedrate_factor`");
    live::same(
        "set_feedrate_factor",
        rejection.answer.as_ref(),
        &seen.answer,
    );
}

/// `set_flowrate_factor`, refused by a real supervisor's own policy.
fn refused_set_flowrate_factor(
    client: &Client,
    world: &supervisor::Supervisor,
    proxy: &live::Proxy,
) {
    let refused = client
        .set_flowrate_factor(&world.print_id, 1.0, REASON, Some(60))
        .expect_err("`set_flowrate_factor` is refused for an actor granted nothing");

    let ClientError::Rejected(rejection) = refused else {
        panic!("`set_flowrate_factor`: the refusal did not arrive as a rejection");
    };
    assert!(
        matches!(rejection.reason, RejectionReason::ActorMayNotRequest { .. }),
        "`set_flowrate_factor` was refused for something other than the grant: {:?}",
        rejection.reason
    );
    let seen = proxy.last();
    assert_eq!(seen.status, 409, "`set_flowrate_factor`");
    live::same(
        "set_flowrate_factor",
        rejection.answer.as_ref(),
        &seen.answer,
    );
}

/// `set_fan_percent`, refused by a real supervisor's own policy.
fn refused_set_fan_percent(client: &Client, world: &supervisor::Supervisor, proxy: &live::Proxy) {
    let refused = client
        .set_fan_percent(&world.print_id, 50.0, REASON, Some(60))
        .expect_err("`set_fan_percent` is refused for an actor granted nothing");

    let ClientError::Rejected(rejection) = refused else {
        panic!("`set_fan_percent`: the refusal did not arrive as a rejection");
    };
    assert!(
        matches!(rejection.reason, RejectionReason::ActorMayNotRequest { .. }),
        "`set_fan_percent` was refused for something other than the grant: {:?}",
        rejection.reason
    );
    let seen = proxy.last();
    assert_eq!(seen.status, 409, "`set_fan_percent`");
    live::same("set_fan_percent", rejection.answer.as_ref(), &seen.answer);
}

/// `set_tool_target_c`, refused by a real supervisor's own policy.
fn refused_set_tool_target_c(client: &Client, world: &supervisor::Supervisor, proxy: &live::Proxy) {
    let refused = client
        .set_tool_target_c(&world.print_id, REASON, 210.0, 0, Some(60))
        .expect_err("`set_tool_target_c` is refused for an actor granted nothing");

    let ClientError::Rejected(rejection) = refused else {
        panic!("`set_tool_target_c`: the refusal did not arrive as a rejection");
    };
    assert!(
        matches!(rejection.reason, RejectionReason::ActorMayNotRequest { .. }),
        "`set_tool_target_c` was refused for something other than the grant: {:?}",
        rejection.reason
    );
    let seen = proxy.last();
    assert_eq!(seen.status, 409, "`set_tool_target_c`");
    live::same("set_tool_target_c", rejection.answer.as_ref(), &seen.answer);
}

/// `set_bed_target_c`, refused by a real supervisor's own policy.
fn refused_set_bed_target_c(client: &Client, world: &supervisor::Supervisor, proxy: &live::Proxy) {
    let refused = client
        .set_bed_target_c(&world.print_id, REASON, 60.0, Some(60))
        .expect_err("`set_bed_target_c` is refused for an actor granted nothing");

    let ClientError::Rejected(rejection) = refused else {
        panic!("`set_bed_target_c`: the refusal did not arrive as a rejection");
    };
    assert!(
        matches!(rejection.reason, RejectionReason::ActorMayNotRequest { .. }),
        "`set_bed_target_c` was refused for something other than the grant: {:?}",
        rejection.reason
    );
    let seen = proxy.last();
    assert_eq!(seen.status, 409, "`set_bed_target_c`");
    live::same("set_bed_target_c", rejection.answer.as_ref(), &seen.answer);
}

/// `acknowledge_failure`, refused by a real supervisor's own policy.
fn refused_acknowledge_failure(
    client: &Client,
    world: &supervisor::Supervisor,
    proxy: &live::Proxy,
) {
    let refused = client
        .acknowledge_failure(
            &world.print_id,
            &printobserver_sdk::AcknowledgementDisposition::Continue,
            &world.event_id,
            REASON,
        )
        .expect_err("`acknowledge_failure` is refused for an actor granted nothing");

    let ClientError::Rejected(rejection) = refused else {
        panic!("`acknowledge_failure`: the refusal did not arrive as a rejection");
    };
    assert!(
        matches!(rejection.reason, RejectionReason::ActorMayNotRequest { .. }),
        "`acknowledge_failure` was refused for something other than the grant: {:?}",
        rejection.reason
    );
    let seen = proxy.last();
    assert_eq!(seen.status, 409, "`acknowledge_failure`");
    live::same(
        "acknowledge_failure",
        rejection.answer.as_ref(),
        &seen.answer,
    );
}

/// `pause`, refused by a real supervisor's own policy.
fn refused_pause(client: &Client, world: &supervisor::Supervisor, proxy: &live::Proxy) {
    let refused = client
        .pause(&world.print_id, REASON)
        .expect_err("`pause` is refused for an actor granted nothing");

    let ClientError::Rejected(rejection) = refused else {
        panic!("`pause`: the refusal did not arrive as a rejection");
    };
    assert!(
        matches!(rejection.reason, RejectionReason::ActorMayNotRequest { .. }),
        "`pause` was refused for something other than the grant: {:?}",
        rejection.reason
    );
    let seen = proxy.last();
    assert_eq!(seen.status, 409, "`pause`");
    live::same("pause", rejection.answer.as_ref(), &seen.answer);
}

/// `resume`, refused by a real supervisor's own policy.
fn refused_resume(client: &Client, world: &supervisor::Supervisor, proxy: &live::Proxy) {
    let refused = client
        .resume(&world.print_id, REASON)
        .expect_err("`resume` is refused for an actor granted nothing");

    let ClientError::Rejected(rejection) = refused else {
        panic!("`resume`: the refusal did not arrive as a rejection");
    };
    assert!(
        matches!(rejection.reason, RejectionReason::ActorMayNotRequest { .. }),
        "`resume` was refused for something other than the grant: {:?}",
        rejection.reason
    );
    let seen = proxy.last();
    assert_eq!(seen.status, 409, "`resume`");
    live::same("resume", rejection.answer.as_ref(), &seen.answer);
}

/// Every method, answered by a real supervisor, in the one order it admits.
#[test]
fn every_method_is_answered_by_a_real_supervisor() {
    let root = tempfile::tempdir().expect("this walk's own root");
    let mut standing = supervisor::standing(root.path());
    let world = standing.at.clone();
    let proxy = live::Proxy::in_front_of(&world.server);
    let client = Client::new(proxy.url(), Actor::Operator);
    let manifest = manifest(&world.file_name);

    step_status(&client, &world, &proxy);
    step_context(&client, &world, &proxy);
    step_image(&client, &world, &proxy);
    step_manifest_set(&client, &world, &proxy, &manifest);
    step_manifest_get(&client, &world, &proxy);
    step_history(&client, &world, &proxy);
    step_cancel(&client, &world, &proxy);
    step_start_print(&client, &world, &proxy, &manifest);
    step_set_feedrate_factor(&client, &world, &proxy);
    step_set_flowrate_factor(&client, &world, &proxy);
    step_set_fan_percent(&client, &world, &proxy);
    step_set_tool_target_c(&client, &world, &proxy);
    step_set_bed_target_c(&client, &world, &proxy);
    step_acknowledge_failure(&client, &world, &proxy);
    step_pause(&client, &world, &proxy);
    step_resume(&client, &world, &proxy);

    assert!(proxy.calls() >= 16, "every call went through the proxy");
    standing.stop();
}

/// Every action, refused by a real supervisor's own policy, as a typed rejection.
///
/// One client acting as an actor class the envelope grants nothing. The policy
/// takes that decision before it looks at the state, the interval or the
/// bounds, so every action is refused from wherever the machine happens to be.
#[test]
fn every_action_is_refused_as_a_typed_rejection_by_a_real_supervisor() {
    let root = tempfile::tempdir().expect("this walk's own root");
    let mut standing = supervisor::standing(root.path());
    let world = standing.at.clone();
    let proxy = live::Proxy::in_front_of(&world.server);
    let client = Client::new(
        proxy.url(),
        Actor::Agent {
            session_name: "an actor this envelope grants nothing".to_owned(),
        },
    );
    let manifest = manifest(&world.file_name);

    refused_cancel(&client, &world, &proxy);
    refused_start_print(&client, &world, &proxy, &manifest);
    refused_set_feedrate_factor(&client, &world, &proxy);
    refused_set_flowrate_factor(&client, &world, &proxy);
    refused_set_fan_percent(&client, &world, &proxy);
    refused_set_tool_target_c(&client, &world, &proxy);
    refused_set_bed_target_c(&client, &world, &proxy);
    refused_acknowledge_failure(&client, &world, &proxy);
    refused_pause(&client, &world, &proxy);
    refused_resume(&client, &world, &proxy);

    standing.stop();
}
