/**
 *  Generated by `contract-codegen` from the checked-in contract schemas.
 *
 *  This file is the Node client's request and response types.
 *
 *  Do not edit by hand: change the contracts, regenerate with `just
 *  generate-clients`, and commit what that writes.
 */

import { GeneratedSurface, reasonGiven } from "./surface.ts";

/**
 * The version of the server contract these types were generated from, which
 * is the version the type crate declares in the tree they came from.
 */
export const CONTRACT_VERSION = "0.1.0";

/**
 * Every operation this client exposes a method for, which is every operation
 * the server declares and no other.
 */
export const OPERATION_NAMES = [
  "status",
  "context",
  "image",
  "history",
  "manifest_get",
  "manifest_set",
  "pause",
  "resume",
  "cancel",
  "start_print",
  "set_feedrate_factor",
  "set_flowrate_factor",
  "set_tool_target_c",
  "set_bed_target_c",
  "set_fan_percent",
  "acknowledge_failure",
] as const;

/** What an operator's acknowledgement of a failure event asks for next. */
export type AcknowledgementDisposition = "continue" | "watch" | "stop";

/** What one mutating request left behind it. */
export interface ActionAnswer {
  /** The bounded intervention it opened, when it opened one. */
  intervention?: Intervention | null;
  /** What the printer said, when the request reached it and it refused. */
  printer_refusal?: string | null;
  /**
   * The record of the request and the decision taken on it. A rejected
   * request's rejection is here, carrying its reason, the value asked for
   * and the range allowed, so a caller can ask again inside the range.
   */
  record: ActionRecord;
}

/** An accepted action reached the printer. */
export interface ActionExecutedPayload {
  /** The action's identifier. */
  action_id: ActionId;
  /** The bounded intervention it opened, when it opened one. */
  intervention_id?: InterventionId | null;
}

/** A lowercase hyphenated version 7 UUID identifying one requested action. */
export type ActionId = string;

/**
 * One action of the closed vocabulary, named without its payload.
 *
 * This is what a safety envelope grants and what a policy rejection names;
 * the
 * payload lives on `PrintAction` itself.
 */
export type ActionKind =
  | "pause"
  | "resume"
  | "cancel"
  | "start_print"
  | "set_feedrate_factor"
  | "set_flowrate_factor"
  | "set_tool_target_c"
  | "set_bed_target_c"
  | "set_fan_percent"
  | "acknowledge_failure";

/**
 * One request, the decision taken on it, and what became of it.
 *
 * `executed_at` and `outcome` are both optional and are absent together: a
 * record is written when the decision is taken, which is before — and, for a
 * rejected request, instead of — anything reaching the printer.
 */
export interface ActionRecord {
  /** The decision policy took on it. */
  decision: PolicyDecision;
  /** When it reached the printer, if it did. */
  executed_at?: Timestamp | null;
  /** This record's identifier, minted by the store. */
  id: ActionId;
  /** What the printer made of it, if it reached the printer. */
  outcome?: ExecutionOutcome | null;
  /** The print this request was made against. */
  print_id: PrintId;
  /** The request itself. */
  request: ActionRequest;
}

/** Policy refused an action. */
export interface ActionRejectedPayload {
  /** The action's identifier. */
  action_id: ActionId;
  /** The whole decision, carrying which rejection it was. */
  decision: PolicyDecision;
}

/** One request an actor made, at the instant it made it. */
export interface ActionRequest {
  /** What was asked for. */
  action: PrintAction;
  /** Who asked. */
  actor: Actor;
  /** When they asked. */
  requested_at: Timestamp;
}

/** An actor asked for an action. */
export interface ActionRequestedPayload {
  /** What was asked for. */
  action: PrintAction;
  /** The action's identifier. */
  action_id: ActionId;
  /** Who asked. */
  actor: Actor;
}

/** Who asked for something. */
export type Actor = { agent: { session_name: string } } | "operator" | "system";

/** An actor class, which is what a safety envelope grants actions to. */
export type ActorClass = "agent" | "operator" | "system";

/** One thing an adjustment may change. */
export type Adjustable = string;

/**
 * The agent's written record of one supervision turn.
 *
 * This is deliberately not how the agent acts: acting is a
 * `PrintAction` that policy rules on.
 */
export interface AgentAssessment {
  /** How sure the agent is. */
  confidence: Confidence;
  /** What the agent did. */
  did: string;
  /** Whether the agent is escalating to a person. */
  escalating: boolean;
  /** Whether the print should carry on. */
  should_continue: boolean;
  /** One line saying what is happening. */
  summary: string;
  /** Why it did it. */
  why: string;
}

/** The agent wrote down what it made of a turn. */
export interface AgentAssessmentPayload {
  /** What the agent answered with. */
  assessment: AgentAssessment;
  /** The session the turn ran in. */
  session_name: string;
}

/**
 * How sure the agent is.
 *
 * A closed vocabulary rather than a number, because a number invites a
 * precision the agent does not have.
 */
export type Confidence = "low" | "medium" | "high";

/**
 * What a context read answers.
 *
 * The latest image is **materialized** here rather than left as the handle
 * `PrintContext` carries: the one thing a supervision turn does with an
 * image is look at it, and a handle is not something anything can open. The
 * path is absolute on this server's own filesystem, exactly as
 * `ImageAnswer`'s is, and is absent when there is no image or when the
 * record is intact and the file is not.
 */
export interface ContextAnswer {
  /** Everything a supervision turn is given about the print. */
  context: PrintContext;
  /** Where the latest image's bytes are, absolute on this host. */
  image_path?: string | null;
}

/**
 * The envelope intersected with the print's manifest.
 *
 * This is what context reports, so that the agent can see its own limits
 * before it asks. Computing one is the supervision core's; this crate
 * declares
 * the shape and nothing that produces it.
 */
export interface EffectiveBounds {
  /** The range each adjustable may be set to, inclusive. */
  allowed: Record<string, Range>;
}

/** What this server answers when it will not do what it was asked. */
export interface ErrorAnswer {
  /** One line saying why, in the words of whatever refused it. */
  error: string;
}

/** A lowercase hyphenated version 7 UUID identifying one event. */
export type EventId = string;

/**
 * What every arm of `EventRecord` carries beside its own payload.
 *
 * One event, as the store holds it.
 *
 * `raw` holds the bytes exactly as received for an externally sourced event
 * and is absent for an internally raised one — it is what makes the history
 * auditable when a normalization turns out to be wrong. `print_id` is
 * optional, because an externally sourced event may name no print this
 * system
 * knows.
 */
export interface EventRecordCommon {
  /** This event's identifier, minted by the store. */
  id: EventId;
  /** The image it arrived with, when it arrived with one. */
  image?: ImageRef | null;
  /** The print it belongs to, when it belongs to one. */
  print_id?: PrintId | null;
  /** The bytes exactly as received, for an externally sourced event. */
  raw?: RawBytes | null;
  /** When it was received. */
  received_at: Timestamp;
  /** Where it came from. */
  source: EventSource;
}

/**
 * One event, as the store holds it.
 *
 * `raw` holds the bytes exactly as received for an externally sourced event
 * and is absent for an internally raised one — it is what makes the history
 * auditable when a normalization turns out to be wrong. `print_id` is
 * optional, because an externally sourced event may name no print this
 * system
 * knows.
 */
export type EventRecord =
  | (EventRecordCommon & { kind: "obico_failure_alert"; payload: ObicoFailureAlertPayload })
  | (EventRecordCommon & {
      kind: "obico_printer_notification";
      payload: ObicoPrinterNotificationPayload;
    })
  | (EventRecordCommon & {
      kind: "malformed_external_event";
      payload: MalformedExternalEventPayload;
    })
  | (EventRecordCommon & { kind: "action_requested"; payload: ActionRequestedPayload })
  | (EventRecordCommon & { kind: "action_executed"; payload: ActionExecutedPayload })
  | (EventRecordCommon & { kind: "action_rejected"; payload: ActionRejectedPayload })
  | (EventRecordCommon & { kind: "intervention_expired"; payload: InterventionExpiredPayload })
  | (EventRecordCommon & {
      kind: "supervision_session_opened";
      payload: SupervisionSessionOpenedPayload;
    })
  | (EventRecordCommon & {
      kind: "supervision_session_closed";
      payload: SupervisionSessionClosedPayload;
    })
  | (EventRecordCommon & { kind: "agent_assessment"; payload: AgentAssessmentPayload })
  | (EventRecordCommon & {
      kind: "operator_acknowledgement";
      payload: OperatorAcknowledgementPayload;
    })
  | (EventRecordCommon & { kind: "port_failure"; payload: PortFailurePayload })
  | (EventRecordCommon & { kind: "startup_reconciliation"; payload: StartupReconciliationPayload });

/** Where an event came from. */
export type EventSource = "obico" | "operator" | "agent" | "system";

/** What happened when an accepted action reached the printer. */
export type ExecutionOutcome = "succeeded" | { failed: { reason: string } };

/**
 * A file name a printer's own file API can be asked for: no path separator,
 * no NUL byte, no `.` or `..` segment, no drive prefix, and not empty.
 */
export type FileName = string;

/**
 * One heater, as a source reported it.
 *
 * Every field is optional, because a source that reports no heater at all
 * reports none of these; each is a plausibility-ranged reported value in
 * degrees Celsius.
 */
export interface HeaterSnapshot {
  /** The temperature the heater is at. */
  actual_c?: Reported | null;
  /** The offset applied to this heater's target. */
  offset_c?: Reported | null;
  /** The temperature the heater is driving towards. */
  target_c?: Reported | null;
}

/** What a history read answers. */
export interface HistoryAnswer {
  /** The print's events, newest first. */
  events: Array<EventRecord>;
}

/**
 * What an image read answers.
 *
 * The path is absolute on this server's own filesystem, and is the whole of
 * the answer about the bytes: nothing here renders them, encodes them or
 * serves them. It is absent when the record is intact and the file is not,
 * which is a different answer from there being no such image.
 */
export interface ImageAnswer {
  /** Where its bytes are, absolute on this host. */
  path?: string | null;
  /** The record. */
  record: ImageRecord;
}

/** A lowercase hyphenated version 7 UUID identifying one image. */
export type ImageId = string;

/**
 * One image, stored beside the event it arrived with.
 *
 * `relative_path` is relative to the configured state directory, so that the
 * store stays portable. Materializing an image resolves that to an absolute
 * path; nothing in this system renders image bytes into JSON.
 */
export interface ImageRecord {
  /** How many bytes it is. */
  byte_len: number;
  /** The content type it was served as. */
  content_type: string;
  /** The event it arrived with. */
  event_id: EventId;
  /** When it was fetched. */
  fetched_at: Timestamp;
  /** This image's identifier, minted by the store. */
  id: ImageId;
  /** The print it belongs to. */
  print_id: PrintId;
  /** Where it lives, relative to the configured state directory. */
  relative_path: string;
  /** The SHA-256 of its bytes, lowercase hexadecimal. */
  sha256: string;
  /** Where it was fetched from, when it was fetched from somewhere. */
  source_url?: string | null;
}

/** The handle an image travels in context under. */
export interface ImageRef {
  /** The image's identifier. */
  id: ImageId;
  /** The SHA-256 of its bytes, lowercase hexadecimal. */
  sha256: string;
}

/**
 * One adjustment made for a bounded time.
 *
 * `prior_value` is read from the printer snapshot taken before the change,
 * and
 * is absent when the printer reported none — in which case expiry restores
 * nothing and the outcome says so rather than guessing a default.
 */
export interface Intervention {
  /** The action that asked for it. */
  action_id: ActionId;
  /** What it changed. */
  adjustable: Adjustable;
  /** When it was applied. */
  applied_at: Timestamp;
  /** What it was changed to. */
  applied_value: number;
  /** When it stops standing. */
  expires_at: Timestamp;
  /** This intervention's identifier, minted by the store. */
  id: InterventionId;
  /** What became of it. */
  outcome: InterventionOutcome;
  /** The print it was made against. */
  print_id: PrintId;
  /** What the printer reported before the change, if it reported anything. */
  prior_value?: number | null;
  /** When the prior value was put back, if it was. */
  restored_at?: Timestamp | null;
}

/** A bounded intervention expired. */
export interface InterventionExpiredPayload {
  /** What it had changed. */
  adjustable: Adjustable;
  /** The intervention's identifier. */
  intervention_id: InterventionId;
  /** What became of it. */
  outcome: InterventionOutcome;
}

/**
 * A lowercase hyphenated version 7 UUID identifying one bounded
 * intervention.
 */
export type InterventionId = string;

/** What became of a bounded change. */
export type InterventionOutcome =
  | "still_active"
  | "restored"
  | "restore_unavailable"
  | { restore_failed: { reason: string } }
  | { superseded: { by: InterventionId } };

/**
 * What a sliced job declares about itself and about what may be adjusted.
 *
 * An adjustable the manifest does not name takes the envelope's own range; a
 * manifest range wider than the envelope's is narrowed to the envelope's and
 * the narrowing is recorded on the print. A manifest may only narrow.
 */
export interface JobManifest {
  /** The range each named adjustable may take, inclusive. */
  allowed: Record<string, Range>;
  /** The file this manifest is about, as the slicer named it. */
  file_name: string;
  /** The material the job is sliced for. */
  material: string;
  /** Whatever else the slicer recorded. */
  metadata: Record<string, string>;
  /** The nozzle the job is sliced for, in millimetres. */
  nozzle_diameter_mm: number;
  /** The slicer profile the job was sliced with. */
  slicer_profile: string;
}

/**
 * The job a printer reports it is running.
 *
 * Every field but `state` is optional: an absent one means the source did
 * not
 * report it.
 */
export interface JobSnapshot {
  /**
   * How far through the print is, as a fraction from zero to one.
   *
   * Normalized to a fraction here regardless of how the source expresses it.
   */
  completion?: Reported | null;
  /** The error the source reports, when it reports one. */
  error?: string | null;
  /** The whole print's estimated duration, in whole seconds. */
  estimated_print_time_s?: number | null;
  /** The name of the file being printed, as the source reported it. */
  file_name?: string | null;
  /** Where the file lives, in the source's own vocabulary. */
  file_origin?: string | null;
  /** How long the print has left, in whole seconds. */
  print_time_left_s?: number | null;
  /** How long the print has been running, in whole seconds. */
  print_time_s?: number | null;
  /** The file's size in bytes. */
  size_bytes?: number | null;
  /** The state the source reports the job to be in. */
  state: PrinterState;
}

/**
 * An external body arrived that could not be read.
 *
 * This kind always carries its `raw` bytes, and it exists so that an alert
 * this system cannot read is written down rather than dropped.
 */
export interface MalformedExternalEventPayload {
  /** One line saying why the body could not be read. */
  detail: string;
}

/** What a manifest read or write answers. */
export interface ManifestAnswer {
  /** The manifest, when the print has one. */
  manifest?: JobManifest | null;
  /**
   * Every range this manifest asked wider than the envelope allows, narrowed
   * to the envelope's — recorded on the print, so nobody has to wonder later
   * which bound applied.
   */
  narrowings: Array<ManifestNarrowing>;
}

/** One adjustable whose manifest range was wider than the envelope's. */
export interface ManifestNarrowing {
  /** The adjustable that was narrowed. */
  adjustable: Adjustable;
  /** The range that stands. */
  applied: Range;
  /** The range the manifest asked for. */
  requested: Range;
}

/**
 * Obico reported a print failure.
 *
 * The two instants are optional because Obico's own field for each is a Unix
 * timestamp number, an empty string, or absent, and the last two both mean
 * the
 * producer reported no instant. An absent field here is that, never an epoch
 * date standing in for it.
 */
export interface ObicoFailureAlertPayload {
  /** When the print ended, when Obico reported an instant for it. */
  ended_at?: Timestamp | null;
  /** The file being printed, when Obico named one. */
  file_name?: string | null;
  /** Whether Obico called it a warning rather than a failure. */
  is_warning: boolean;
  /** Obico's own identifier for the print, when it named one. */
  obico_print_id?: number | null;
  /** Whether Obico paused the print itself. */
  print_paused: boolean;
  /** When the print started, when Obico reported an instant for it. */
  started_at?: Timestamp | null;
}

/** The kind of printer notification Obico sent, normalized. */
export type ObicoNotificationType =
  | "started"
  | "done"
  | "cancelled"
  | "paused"
  | "resumed"
  | "filament_change"
  | "heater_cooled"
  | "heater_target";

/**
 * Obico sent a printer notification.
 *
 * The two instants are optional for the same reason
 * `ObicoFailureAlertPayload`'s are, and are absent along with the rest of
 * the print's fields when the notification is about no print at all.
 */
export interface ObicoPrinterNotificationPayload {
  /** When the print ended, when Obico reported an instant for it. */
  ended_at?: Timestamp | null;
  /** The file being printed, when the notification is about one. */
  file_name?: string | null;
  /** Which notification it is. */
  notification_type: ObicoNotificationType;
  /**
   * Obico's own identifier for the print, when the notification is about
   * one.
   */
  obico_print_id?: number | null;
  /** When the print started, when Obico reported an instant for it. */
  started_at?: Timestamp | null;
}

/** An operator acknowledged an event. */
export interface OperatorAcknowledgementPayload {
  /** The event being acknowledged. */
  acknowledged_event_id: EventId;
  /** What the operator asked for next. */
  disposition: AcknowledgementDisposition;
}

/** The decision policy took on one request. */
export type PolicyDecision = "accepted" | { rejected: RejectionReason };

/**
 * A port failed while one event was being handled.
 *
 * The event is named rather than implied, so that a reader holding an
 * event's
 * identifier reaches every failure recorded while that event was being
 * handled. A failure recorded here is one the handling survived: the event
 * is
 * already in the history by the time any of these sites is reached, and the
 * loop goes on to handle the next event.
 */
export interface PortFailurePayload {
  /** What the port said about it, in the port's own words. */
  detail: string;
  /** The event whose handling reached the failing call. */
  event_id: EventId;
  /** Where it failed. */
  site: PortFailureSite;
}

/**
 * Where a port failed while an event was being handled.
 *
 * A closed set of exactly the sites at which a failure has nowhere else to
 * be
 * recorded. The printer's action methods record theirs on the
 * `ActionRecord` the request minted, and a restoring
 * call records its own on the `Intervention` it was
 * expiring; those are not sites here, because a second record of them would
 * be
 * a second version of one fact.
 */
export type PortFailureSite =
  | "printer_snapshot"
  | "printer_job"
  | "image_write"
  | "supervision_turn";

/** The whole vocabulary an actor may ask for, and there is no other. */
export type PrintAction =
  | { action: "pause"; actor: Actor; reason: string }
  | { action: "resume"; actor: Actor; reason: string }
  | { action: "cancel"; actor: Actor; reason: string }
  | {
      action: "start_print";
      actor: Actor;
      file_name: FileName;
      manifest: JobManifest;
      reason: string;
    }
  | {
      action: "set_feedrate_factor";
      actor: Actor;
      duration_s?: number | null;
      factor: number;
      reason: string;
    }
  | {
      action: "set_flowrate_factor";
      actor: Actor;
      duration_s?: number | null;
      factor: number;
      reason: string;
    }
  | {
      action: "set_tool_target_c";
      actor: Actor;
      duration_s?: number | null;
      reason: string;
      target_c: number;
      tool: number;
    }
  | {
      action: "set_bed_target_c";
      actor: Actor;
      duration_s?: number | null;
      reason: string;
      target_c: number;
    }
  | {
      action: "set_fan_percent";
      actor: Actor;
      duration_s?: number | null;
      percent: number;
      reason: string;
    }
  | {
      action: "acknowledge_failure";
      actor: Actor;
      disposition: AcknowledgementDisposition;
      event_id: EventId;
      reason: string;
    };

/** Everything a supervision turn is given about one print. */
export interface PrintContext {
  /** The limits in force, so that the agent can see them before it asks. */
  bounds: EffectiveBounds;
  /** The interventions still active. */
  interventions: Array<Intervention>;
  /** The job, when a snapshot could be taken. */
  job?: JobSnapshot | null;
  /** The most recent image, when there is one. */
  latest_image?: ImageRef | null;
  /** The manifest, when the print has one. */
  manifest?: JobManifest | null;
  /** The print itself. */
  print: PrintRecord;
  /** The printer, when a snapshot could be taken. */
  printer?: PrinterSnapshot | null;
  /** A bounded list of this print's events, newest first. */
  recent_events: Array<EventRecord>;
}

/** A lowercase hyphenated version 7 UUID identifying one print. */
export type PrintId = string;

/**
 * One print, and the record supervision keys from.
 *
 * Obico's own print id is carried beside this record's identifier rather
 * than
 * as it, because a print may be observed before Obico has one.
 */
export interface PrintRecord {
  /** Why it ended, if it has. */
  end_reason?: string | null;
  /** When it ended, if it has. */
  ended_at?: Timestamp | null;
  /** The file being printed, as the source reported it. */
  file_name?: string | null;
  /** This print's identifier, minted by the store. */
  id: PrintId;
  /** Every manifest range this print narrowed to the envelope's. */
  narrowings: Array<ManifestNarrowing>;
  /** Obico's own identifier for the print, when Obico has one. */
  obico_print_id?: number | null;
  /** When the print was opened. */
  opened_at: Timestamp;
  /** The state the print is in. */
  state: PrinterState;
}

/** A printer, as a source reported it at one instant. */
export interface PrinterSnapshot {
  /** The bed heater, when the printer reports one. */
  bed?: HeaterSnapshot | null;
  /** The chamber heater, when the printer reports one. */
  chamber?: HeaterSnapshot | null;
  /** The state the printer is in. */
  connection: PrinterState;
  /** The part-cooling fan, in percent. */
  fan_percent?: Reported | null;
  /** The feedrate multiplier, where one means one hundred percent. */
  feedrate_factor?: Reported | null;
  /** The flowrate multiplier, where one means one hundred percent. */
  flowrate_factor?: Reported | null;
  /** The instant this observation was taken. */
  observed_at: Timestamp;
  /** The tool heaters, indexed by tool number. */
  tools: Array<HeaterSnapshot>;
}

/**
 * The state a source reports a printer or a print to be in.
 *
 * The `unknown` arm exists so that a state nobody anticipated is recorded
 * carrying the source's own word for it rather than lost.
 */
export type PrinterState =
  | "operational"
  | "paused"
  | "printing"
  | "cancelling"
  | "error"
  | "offline"
  | { unknown: string };

/** An inclusive pair of 64-bit floats. */
export interface Range {
  /** The highest value the range admits, inclusive. */
  max: number;
  /** The lowest value the range admits, inclusive. */
  min: number;
}

/** Bytes exactly as received, base64-encoded. */
export type RawBytes = string;

/**
 * Why a request was refused.
 *
 * Each rejection is a distinct variant, so a consumer distinguishes them by
 * matching rather than by reading a message.
 */
export type RejectionReason =
  | { out_of_bounds: { adjustable: Adjustable; allowed: Range; requested: number } }
  | { actor_may_not_request: { action: ActionKind; actor_class: ActorClass } }
  | "no_active_print"
  | { invalid_from_state: { state: PrinterState } }
  | { min_interval_not_elapsed: { interval_s: number; since_last_s: number } }
  | { unsupported_adjustable: { adjustable: Adjustable } };

/**
 * A value as a source reported it, flagged when it is outside the
 * plausibility range this crate declares for its field.
 */
export interface Reported {
  /** One shape of the contracts, which say nothing more about it. */
  out_of_range: boolean;
  /** One shape of the contracts, which say nothing more about it. */
  value: number;
}

/**
 * What one restart put back the way it found it.
 *
 * A supervisor that has been restarted adopts whatever the store holds
 * rather
 * than starting empty, and each of these is one of those adoptions. They are
 * recorded rather than merely done, because a print that carried on across a
 * restart and one that was started again look identical afterwards unless
 * the
 * history says which happened.
 */
export type StartupOutcome =
  | "print_adopted"
  | { session_resumed: { session_name: string } }
  | {
      intervention_expired: {
        adjustable: Adjustable;
        intervention_id: InterventionId;
        outcome: InterventionOutcome;
      };
    };

/** A supervisor reconciled one thing the store held when it started. */
export interface StartupReconciliationPayload {
  /** What was reconciled. */
  outcome: StartupOutcome;
  /** The print it is about. */
  print_id: PrintId;
}

/** What a status read answers. */
export interface StatusAnswer {
  /** The bounded interventions still in force. */
  interventions: Array<Intervention>;
  /** The job, when a snapshot could be taken. */
  job?: JobSnapshot | null;
  /** The print. */
  print: PrintRecord;
  /** The printer, when a snapshot could be taken. */
  printer?: PrinterSnapshot | null;
  /** The supervision session watching it, when one is. */
  session?: SupervisionSession | null;
}

/** The supervision session keyed to one print. */
export interface SupervisionSession {
  /** Why it was closed, if it was. */
  close_reason?: string | null;
  /** When the session was closed, if it was. */
  closed_at?: Timestamp | null;
  /** When the session was opened. */
  created_at: Timestamp;
  /** The identity the harness ran the session under. */
  harness_identity: string;
  /** When the last turn ran. */
  last_turn_at: Timestamp;
  /** The print this session watches. */
  print_id: PrintId;
  /** The session's own name in the harness. */
  session_name: string;
}

/** A supervision session was closed. */
export interface SupervisionSessionClosedPayload {
  /** Why it was closed. */
  close_reason: string;
  /** The session's own name in the harness. */
  session_name: string;
}

/** A supervision session was opened. */
export interface SupervisionSessionOpenedPayload {
  /** The identity the harness ran it under. */
  harness_identity: string;
  /** The session's own name in the harness. */
  session_name: string;
}

/** An instant in UTC, as an RFC 3339 string with a zero offset. */
export type Timestamp = string;

/**
 * One method per operation the server declares.
 *
 * Every method here is generated from the checked-in description of the
 * server's own operations. The transport, the configuration and the error
 * vocabulary are hand-written, and this class is written against them.
 */
export class GeneratedClient extends GeneratedSurface {
  /**
   * Call `status` on the configured supervisor.
   *
   * Rejects with `Unreachable` when nothing answered, with `Unreadable` when
   * the answer could not be read, and with `Refused` when the supervisor
   * said no.
   */
  async status(printId: string): Promise<StatusAnswer> {
    const target = `/v1/prints/${printId}/status`;
    const asked: Array<[string, string]> = [];
    const sending = undefined;
    return await this.call<StatusAnswer>("GET", target, asked, sending);
  }

  /**
   * Call `context` on the configured supervisor.
   *
   * Rejects with `Unreachable` when nothing answered, with `Unreadable` when
   * the answer could not be read, and with `Refused` when the supervisor
   * said no.
   */
  async context(printId: string): Promise<ContextAnswer> {
    const target = `/v1/prints/${printId}/context`;
    const asked: Array<[string, string]> = [];
    const sending = undefined;
    return await this.call<ContextAnswer>("GET", target, asked, sending);
  }

  /**
   * Call `image` on the configured supervisor.
   *
   * Rejects with `Unreachable` when nothing answered, with `Unreadable` when
   * the answer could not be read, and with `Refused` when the supervisor
   * said no.
   */
  async image(imageId: string): Promise<ImageAnswer> {
    const target = `/v1/images/${imageId}`;
    const asked: Array<[string, string]> = [];
    const sending = undefined;
    return await this.call<ImageAnswer>("GET", target, asked, sending);
  }

  /**
   * Call `history` on the configured supervisor.
   *
   * Rejects with `Unreachable` when nothing answered, with `Unreadable` when
   * the answer could not be read, and with `Refused` when the supervisor
   * said no.
   */
  async history(printId: string, limit?: number): Promise<HistoryAnswer> {
    const target = `/v1/prints/${printId}/history`;
    const asked: Array<[string, string]> = [];
    if (limit !== undefined) {
      asked.push(["limit", String(limit)]);
    }
    const sending = undefined;
    return await this.call<HistoryAnswer>("GET", target, asked, sending);
  }

  /**
   * Call `manifest_get` on the configured supervisor.
   *
   * Rejects with `Unreachable` when nothing answered, with `Unreadable` when
   * the answer could not be read, and with `Refused` when the supervisor
   * said no.
   */
  async manifestGet(printId: string): Promise<ManifestAnswer> {
    const target = `/v1/prints/${printId}/manifest`;
    const asked: Array<[string, string]> = [];
    const sending = undefined;
    return await this.call<ManifestAnswer>("GET", target, asked, sending);
  }

  /**
   * Call `manifest_set` on the configured supervisor.
   *
   * Rejects with `Unreachable` when nothing answered, with `Unreadable` when
   * the answer could not be read, and with `Refused` when the supervisor
   * said no. A call whose reason is empty is refused here, before a request
   * is made, and the policy's own refusal arrives as `Rejected`, carrying
   * the reason, the value asked for and the range allowed.
   */
  async manifestSet(
    printId: string,
    reason: string,
    manifest: JobManifest,
  ): Promise<ManifestAnswer> {
    reasonGiven(reason);
    const target = `/v1/prints/${printId}/manifest`;
    const asked: Array<[string, string]> = [];
    const sending: Record<string, unknown> = {};
    sending.reason = reason;
    sending.manifest = manifest;
    return await this.call<ManifestAnswer>("PUT", target, asked, sending);
  }

  /**
   * Call `pause` on the configured supervisor.
   *
   * Rejects with `Unreachable` when nothing answered, with `Unreadable` when
   * the answer could not be read, and with `Refused` when the supervisor
   * said no. A call whose reason is empty is refused here, before a request
   * is made, and the policy's own refusal arrives as `Rejected`, carrying
   * the reason, the value asked for and the range allowed.
   */
  async pause(printId: string, reason: string): Promise<ActionAnswer> {
    reasonGiven(reason);
    const target = `/v1/prints/${printId}/actions/pause`;
    const asked: Array<[string, string]> = [];
    const sending: Record<string, unknown> = {};
    sending.actor = this.actor;
    sending.reason = reason;
    return await this.call<ActionAnswer>("POST", target, asked, sending);
  }

  /**
   * Call `resume` on the configured supervisor.
   *
   * Rejects with `Unreachable` when nothing answered, with `Unreadable` when
   * the answer could not be read, and with `Refused` when the supervisor
   * said no. A call whose reason is empty is refused here, before a request
   * is made, and the policy's own refusal arrives as `Rejected`, carrying
   * the reason, the value asked for and the range allowed.
   */
  async resume(printId: string, reason: string): Promise<ActionAnswer> {
    reasonGiven(reason);
    const target = `/v1/prints/${printId}/actions/resume`;
    const asked: Array<[string, string]> = [];
    const sending: Record<string, unknown> = {};
    sending.actor = this.actor;
    sending.reason = reason;
    return await this.call<ActionAnswer>("POST", target, asked, sending);
  }

  /**
   * Call `cancel` on the configured supervisor.
   *
   * Rejects with `Unreachable` when nothing answered, with `Unreadable` when
   * the answer could not be read, and with `Refused` when the supervisor
   * said no. A call whose reason is empty is refused here, before a request
   * is made, and the policy's own refusal arrives as `Rejected`, carrying
   * the reason, the value asked for and the range allowed.
   */
  async cancel(printId: string, reason: string): Promise<ActionAnswer> {
    reasonGiven(reason);
    const target = `/v1/prints/${printId}/actions/cancel`;
    const asked: Array<[string, string]> = [];
    const sending: Record<string, unknown> = {};
    sending.actor = this.actor;
    sending.reason = reason;
    return await this.call<ActionAnswer>("POST", target, asked, sending);
  }

  /**
   * Call `start_print` on the configured supervisor.
   *
   * Rejects with `Unreachable` when nothing answered, with `Unreadable` when
   * the answer could not be read, and with `Refused` when the supervisor
   * said no. A call whose reason is empty is refused here, before a request
   * is made, and the policy's own refusal arrives as `Rejected`, carrying
   * the reason, the value asked for and the range allowed.
   */
  async startPrint(
    printId: string,
    fileName: FileName,
    manifest: JobManifest,
    reason: string,
  ): Promise<ActionAnswer> {
    reasonGiven(reason);
    const target = `/v1/prints/${printId}/actions/start_print`;
    const asked: Array<[string, string]> = [];
    const sending: Record<string, unknown> = {};
    sending.actor = this.actor;
    sending.file_name = fileName;
    sending.manifest = manifest;
    sending.reason = reason;
    return await this.call<ActionAnswer>("POST", target, asked, sending);
  }

  /**
   * Call `set_feedrate_factor` on the configured supervisor.
   *
   * Rejects with `Unreachable` when nothing answered, with `Unreadable` when
   * the answer could not be read, and with `Refused` when the supervisor
   * said no. A call whose reason is empty is refused here, before a request
   * is made, and the policy's own refusal arrives as `Rejected`, carrying
   * the reason, the value asked for and the range allowed.
   */
  async setFeedrateFactor(
    printId: string,
    factor: number,
    reason: string,
    durationS?: number,
  ): Promise<ActionAnswer> {
    reasonGiven(reason);
    const target = `/v1/prints/${printId}/actions/set_feedrate_factor`;
    const asked: Array<[string, string]> = [];
    const sending: Record<string, unknown> = {};
    sending.actor = this.actor;
    if (durationS !== undefined) {
      sending.duration_s = durationS;
    }
    sending.factor = factor;
    sending.reason = reason;
    return await this.call<ActionAnswer>("POST", target, asked, sending);
  }

  /**
   * Call `set_flowrate_factor` on the configured supervisor.
   *
   * Rejects with `Unreachable` when nothing answered, with `Unreadable` when
   * the answer could not be read, and with `Refused` when the supervisor
   * said no. A call whose reason is empty is refused here, before a request
   * is made, and the policy's own refusal arrives as `Rejected`, carrying
   * the reason, the value asked for and the range allowed.
   */
  async setFlowrateFactor(
    printId: string,
    factor: number,
    reason: string,
    durationS?: number,
  ): Promise<ActionAnswer> {
    reasonGiven(reason);
    const target = `/v1/prints/${printId}/actions/set_flowrate_factor`;
    const asked: Array<[string, string]> = [];
    const sending: Record<string, unknown> = {};
    sending.actor = this.actor;
    if (durationS !== undefined) {
      sending.duration_s = durationS;
    }
    sending.factor = factor;
    sending.reason = reason;
    return await this.call<ActionAnswer>("POST", target, asked, sending);
  }

  /**
   * Call `set_tool_target_c` on the configured supervisor.
   *
   * Rejects with `Unreachable` when nothing answered, with `Unreadable` when
   * the answer could not be read, and with `Refused` when the supervisor
   * said no. A call whose reason is empty is refused here, before a request
   * is made, and the policy's own refusal arrives as `Rejected`, carrying
   * the reason, the value asked for and the range allowed.
   */
  async setToolTargetC(
    printId: string,
    reason: string,
    targetC: number,
    tool: number,
    durationS?: number,
  ): Promise<ActionAnswer> {
    reasonGiven(reason);
    const target = `/v1/prints/${printId}/actions/set_tool_target_c`;
    const asked: Array<[string, string]> = [];
    const sending: Record<string, unknown> = {};
    sending.actor = this.actor;
    if (durationS !== undefined) {
      sending.duration_s = durationS;
    }
    sending.reason = reason;
    sending.target_c = targetC;
    sending.tool = tool;
    return await this.call<ActionAnswer>("POST", target, asked, sending);
  }

  /**
   * Call `set_bed_target_c` on the configured supervisor.
   *
   * Rejects with `Unreachable` when nothing answered, with `Unreadable` when
   * the answer could not be read, and with `Refused` when the supervisor
   * said no. A call whose reason is empty is refused here, before a request
   * is made, and the policy's own refusal arrives as `Rejected`, carrying
   * the reason, the value asked for and the range allowed.
   */
  async setBedTargetC(
    printId: string,
    reason: string,
    targetC: number,
    durationS?: number,
  ): Promise<ActionAnswer> {
    reasonGiven(reason);
    const target = `/v1/prints/${printId}/actions/set_bed_target_c`;
    const asked: Array<[string, string]> = [];
    const sending: Record<string, unknown> = {};
    sending.actor = this.actor;
    if (durationS !== undefined) {
      sending.duration_s = durationS;
    }
    sending.reason = reason;
    sending.target_c = targetC;
    return await this.call<ActionAnswer>("POST", target, asked, sending);
  }

  /**
   * Call `set_fan_percent` on the configured supervisor.
   *
   * Rejects with `Unreachable` when nothing answered, with `Unreadable` when
   * the answer could not be read, and with `Refused` when the supervisor
   * said no. A call whose reason is empty is refused here, before a request
   * is made, and the policy's own refusal arrives as `Rejected`, carrying
   * the reason, the value asked for and the range allowed.
   */
  async setFanPercent(
    printId: string,
    percent: number,
    reason: string,
    durationS?: number,
  ): Promise<ActionAnswer> {
    reasonGiven(reason);
    const target = `/v1/prints/${printId}/actions/set_fan_percent`;
    const asked: Array<[string, string]> = [];
    const sending: Record<string, unknown> = {};
    sending.actor = this.actor;
    if (durationS !== undefined) {
      sending.duration_s = durationS;
    }
    sending.percent = percent;
    sending.reason = reason;
    return await this.call<ActionAnswer>("POST", target, asked, sending);
  }

  /**
   * Call `acknowledge_failure` on the configured supervisor.
   *
   * Rejects with `Unreachable` when nothing answered, with `Unreadable` when
   * the answer could not be read, and with `Refused` when the supervisor
   * said no. A call whose reason is empty is refused here, before a request
   * is made, and the policy's own refusal arrives as `Rejected`, carrying
   * the reason, the value asked for and the range allowed.
   */
  async acknowledgeFailure(
    printId: string,
    disposition: AcknowledgementDisposition,
    eventId: EventId,
    reason: string,
  ): Promise<ActionAnswer> {
    reasonGiven(reason);
    const target = `/v1/prints/${printId}/actions/acknowledge_failure`;
    const asked: Array<[string, string]> = [];
    const sending: Record<string, unknown> = {};
    sending.actor = this.actor;
    sending.disposition = disposition;
    sending.event_id = eventId;
    sending.reason = reason;
    return await this.call<ActionAnswer>("POST", target, asked, sending);
  }
}
