"""The three clients are one product, and two checks are what make that true.

Every journey here drives the committed check functions over a real copy of the
committed tree with one defect in it. Nothing is mocked: the drift check runs
the real generator, which runs the three real formatters, over real files.
"""

from __future__ import annotations

import json
from collections.abc import Callable
from pathlib import Path

import pytest
from repo_checks.checks_clients import (
    CLIENTS,
    client_surface,
    generated_clients,
    response_shapes,
)
from repo_checks.expect import accepted, refused, refused_naming
from treecopy import REPO_ROOT, Tree, copy_tree

RUST = "crates/printobserver-sdk/src/contract.rs"
PYTHON = "python/printobserver-sdk/src/printobserver_sdk/contract.py"
NODE = "npm/printobserver-sdk/src/contract.ts"
IMAGE_RECORD = "schemas/printobserver-types/ImageRecord.json"


@pytest.fixture
def client_tree(tmp_path: Path) -> Callable[[], Tree]:
    """A copy of the tree the client generator can be run over.

    It carries a link to the committed tree's installed JavaScript
    dependencies, because the generator lays the Node client out with the same
    `biome` the gate holds it to and that binary lives there.
    """
    counter = {"n": 0}

    def make() -> Tree:
        counter["n"] += 1
        root = copy_tree(tmp_path / f"clients{counter['n']}")
        (root / "node_modules").symlink_to(REPO_ROOT / "node_modules")
        return Tree(root)

    return make


def test_the_committed_clients_are_what_the_generator_writes(
    client_tree: Callable[[], Tree],
) -> None:
    """The tree this repository ships is accepted by the drift check."""
    accepted(generated_clients(client_tree().repo))


def test_the_committed_clients_expose_exactly_the_declared_operations(
    client_tree: Callable[[], Tree],
) -> None:
    """The tree this repository ships is accepted by the surface check."""
    accepted(client_surface(client_tree().repo))


@pytest.mark.parametrize("path", [RUST, PYTHON, NODE])
def test_a_generated_file_edited_by_hand_is_refused(
    path: str, client_tree: Callable[[], Tree]
) -> None:
    """A hand-written type agreeing today fails the moment somebody edits one."""
    broken = client_tree()
    broken.append(path, "\n// a line somebody added by hand\n")

    refused_naming(generated_clients(broken.repo), path, "a line somebody added by hand")


@pytest.mark.parametrize("path", [RUST, PYTHON, NODE])
def test_a_generated_file_that_does_not_say_it_is_generated_is_refused(
    path: str, client_tree: Callable[[], Tree]
) -> None:
    """A reader who edits one has to be told the edit will not survive."""
    broken = client_tree()
    broken.write(path, broken.read(path).replace("Generated by", "Written by", 1))

    refused_naming(generated_clients(broken.repo), path, "does not say it is generated")


def _alter(tree: Tree, alter: Callable[[dict[str, object], list[str]], None]) -> None:
    """Move one shape of a checked-in contract schema, and put it back."""
    schema = json.loads(tree.read(IMAGE_RECORD))
    properties = schema.get("properties")
    required = schema.get("required")
    if not isinstance(properties, dict) or not isinstance(required, list):
        msg = f"{IMAGE_RECORD} is not the object schema these journeys alter"
        raise AssertionError(msg)
    alter(properties, required)
    tree.write(IMAGE_RECORD, json.dumps(schema, indent=2, sort_keys=True) + "\n")


def test_a_required_field_added_to_a_schema_is_refused_naming_it(
    client_tree: Callable[[], Tree],
) -> None:
    """A field the contracts gain and the clients have not is named."""
    broken = client_tree()

    def add(properties: dict[str, object], required: list[str]) -> None:
        properties["captured_by"] = {"description": "What captured it.", "type": "string"}
        required.append("captured_by")

    _alter(broken, add)

    refused(generated_clients(broken.repo), "captured_by")


def test_a_field_renamed_in_a_schema_is_refused_naming_it(
    client_tree: Callable[[], Tree],
) -> None:
    """A rename the clients have not followed is named."""
    broken = client_tree()

    def rename(properties: dict[str, object], required: list[str]) -> None:
        properties["digest"] = properties.pop("sha256")
        required[:] = ["digest" if name == "sha256" else name for name in required]

    _alter(broken, rename)

    refused(generated_clients(broken.repo), "digest")


def test_a_fields_type_changed_in_a_schema_is_refused_naming_it(
    client_tree: Callable[[], Tree],
) -> None:
    """A field whose declared type moved is named."""
    broken = client_tree()

    def retype(properties: dict[str, object], _required: list[str]) -> None:
        properties["sha256"] = {"description": "The digest of its bytes.", "type": "number"}

    _alter(broken, retype)

    refused(generated_clients(broken.repo), "sha256")


@pytest.mark.parametrize(
    ("path", "old", "new"),
    [
        (RUST, "pub fn status(", "pub fn state_of("),
        (PYTHON, "    def status(", "    def state_of("),
        (NODE, "  async status(", "  async stateOf("),
    ],
)
def test_a_client_that_renames_a_method_is_refused(
    path: str, old: str, new: str, client_tree: Callable[[], Tree]
) -> None:
    """An operation a client exposes no method for, and a method nothing backs."""
    broken = client_tree()
    broken.edit(path, old, new)

    findings = client_surface(broken.repo)
    refused(findings, "`status`, which the")
    refused(findings, "which no operation the server declares backs")


@pytest.mark.parametrize(
    ("path", "old", "new"),
    [
        (
            RUST,
            "pub fn pause(&self, print_id: &str, reason: &str)",
            "pub fn pause(&self, print_id: &str, reason: Option<String>)",
        ),
        (
            PYTHON,
            "def pause(self, print_id: str, reason: str)",
            "def pause(self, print_id: str, reason: str | None = None)",
        ),
        (
            NODE,
            "async pause(printId: string, reason: string)",
            "async pause(printId: string, reason?: string)",
        ),
    ],
)
def test_a_client_whose_reason_may_be_left_out_is_refused(
    path: str, old: str, new: str, client_tree: Callable[[], Tree]
) -> None:
    """A reason a caller may omit is not the reason every mutating call carries."""
    broken = client_tree()
    broken.edit(path, old, new)

    refused(client_surface(broken.repo), "`reason` as optional")


@pytest.mark.parametrize(
    ("path", "old", "new"),
    [
        (
            RUST,
            "        reason: &str,\n        duration_s: Option<i64>,\n    ) "
            "-> Result<ActionAnswer, ClientError> {\n        crate::reason_given(reason)?;\n"
            '        let target = format!("/v1/prints/{print_id}/actions/set_feedrate_factor");',
            "        reason: &str,\n        duration_s: i64,\n    ) "
            "-> Result<ActionAnswer, ClientError> {\n        crate::reason_given(reason)?;\n"
            '        let target = format!("/v1/prints/{print_id}/actions/set_feedrate_factor");',
        ),
        (
            PYTHON,
            "def set_feedrate_factor(\n        self, print_id: str, factor: float, "
            "reason: str, duration_s: int | None = None\n    )",
            "def set_feedrate_factor(\n        self, print_id: str, factor: float, "
            "reason: str, duration_s: int\n    )",
        ),
        (
            NODE,
            "async setFeedrateFactor(\n    printId: string,\n    factor: number,\n"
            "    reason: string,\n    durationS?: number,\n  )",
            "async setFeedrateFactor(\n    printId: string,\n    factor: number,\n"
            "    reason: string,\n    durationS: number,\n  )",
        ),
    ],
)
def test_a_client_that_requires_the_duration_is_refused(
    path: str, old: str, new: str, client_tree: Callable[[], Tree]
) -> None:
    """A bounded adjustment's duration is optional in every one of the three."""
    broken = client_tree()
    broken.edit(path, old, new)

    refused(client_surface(broken.repo), "requires `duration_s`")


@pytest.mark.parametrize(
    ("path", "old", "new"),
    [
        (
            RUST,
            "pub fn pause(&self, print_id: &str",
            "pub fn pause(&self, actor: &Actor, print_id: &str",
        ),
        (
            PYTHON,
            "    def pause(self, print_id: str",
            "    def pause(self, actor: Actor, print_id: str",
        ),
        (
            NODE,
            "  async pause(printId: string",
            "  async pause(actor: Actor, printId: string",
        ),
    ],
)
def test_a_client_whose_method_takes_the_actor_is_refused(
    path: str, old: str, new: str, client_tree: Callable[[], Tree]
) -> None:
    """Who a client acts as is what it was made with, not what one call says."""
    broken = client_tree()
    broken.edit(path, old, new)

    refused(client_surface(broken.repo), "takes `actor`")


def test_every_client_is_read_by_the_surface_check(
    client_tree: Callable[[], Tree],
) -> None:
    """A client whose generated module is gone is reported rather than skipped."""
    for client in CLIENTS:
        broken = client_tree()
        broken.remove(client.generated)

        refused(client_surface(broken.repo), f"the {client.language} client carries no")


def test_no_shape_this_server_answers_carries_an_image(
    client_tree: Callable[[], Tree],
) -> None:
    """The tree this repository ships is accepted by the shape walk."""
    accepted(response_shapes(client_tree().repo))


def test_a_byte_sequence_field_a_response_reaches_is_refused(
    client_tree: Callable[[], Tree],
) -> None:
    """A new byte-sequence field cannot appear in a response shape unnoticed."""
    broken = client_tree()

    def add(properties: dict[str, object], required: list[str]) -> None:
        properties["thumbnail"] = {
            "contentEncoding": "base64",
            "description": "The image, inline.",
            "type": "string",
        }
        required.append("thumbnail")

    _alter(broken, add)

    refused_naming(response_shapes(broken.repo), "ImageRecord.thumbnail", "byte-sequence")


def test_a_string_declared_as_image_content_is_refused(
    client_tree: Callable[[], Tree],
) -> None:
    """A string declared as an image is refused outright, with no exception."""
    broken = client_tree()

    def add(properties: dict[str, object], required: list[str]) -> None:
        properties["rendered"] = {
            "contentMediaType": "image/jpeg",
            "description": "The image, as a string.",
            "type": "string",
        }
        required.append("rendered")

    _alter(broken, add)

    refused_naming(response_shapes(broken.repo), "ImageRecord.rendered", "image content")


def test_a_byte_sequence_field_the_policy_records_is_accepted(
    client_tree: Callable[[], Tree],
) -> None:
    """A recorded field is accepted, and only while the record carries a reason."""
    reasoned = client_tree()
    accepted(response_shapes(reasoned.repo))

    unreasoned = client_tree()
    unreasoned.edit(
        "repo-policy.toml",
        'type = "EventRecord"\nfield = "raw"\nreason = """',
        'type = "EventRecord"\nfield = "raw"\nunreason = """',
    )

    refused_naming(response_shapes(unreasoned.repo), "EventRecord.raw", "byte-sequence")


def test_a_recorded_field_no_response_reaches_is_refused(
    client_tree: Callable[[], Tree],
) -> None:
    """An exception guarding nothing has stopped being one."""
    broken = client_tree()
    broken.edit("repo-policy.toml", 'field = "raw"', 'field = "no_such_field"')

    refused_naming(response_shapes(broken.repo), "EventRecord.no_such_field", "guarding nothing")


def test_a_response_shape_the_contracts_do_not_declare_is_refused(
    client_tree: Callable[[], Tree],
) -> None:
    """A described answer nothing declares is reported rather than walked past."""
    broken = client_tree()
    broken.edit(
        "schemas/printobserver-server/operations.json",
        '"type": "StatusAnswer"',
        '"type": "NoSuchAnswer"',
    )

    refused(response_shapes(broken.repo), "NoSuchAnswer")


def test_an_operation_with_no_place_in_the_real_walk_is_refused(
    client_tree: Callable[[], Tree],
) -> None:
    """A new operation cannot arrive with nothing driving it against a machine.

    The walk each client runs against a **real** supervisor has an order,
    because a printer is a state machine. An operation with no place in that
    order is one the generator writes no walk for, and this is where the tree
    is refused for it — so the completeness gate reaches the real walk and not
    only the one against a stub host.
    """
    broken = client_tree()
    described = json.loads(broken.read("schemas/printobserver-server/operations.json"))
    described["operations"].append({**described["operations"][0], "name": "reboot"})
    broken.write("schemas/printobserver-server/operations.json", json.dumps(described, indent=2))

    refused_naming(generated_clients(broken.repo), "reboot", "could not run over this tree")
