"""The supervisor adapter's structural claims, each driven against a defect.

Every journey drives the committed check against a real copy of the committed
tree with one defect in it. The spawn journeys matter most: the fixture crate
they add spawns an executable whose name it *computes*, which is exactly the
path a rule keyed on the word `oneharness` would let through.

The journeys after them are about the artifacts these checks read rather than
about the rules: what each check says when the policy, the crate, the template,
the skill or a generated schema is absent or unreadable. A check that crashed
there would fail the gate with a traceback instead of with what is missing, and
one that returned nothing would pass over a tree its rule has no subject in.
"""

from __future__ import annotations

import json
from collections.abc import Callable

from repo_checks.checks_supervisor import (
    prompt_template,
    schema_lock,
    schema_source,
    spawn_free,
    supervisor_policy,
)
from repo_checks.expect import accepted, equal, refused
from repo_checks.model import Repo
from treecopy import Tree

CRATE = "crates/printobserver-oneharness"
TEMPLATE = f"{CRATE}/assets/turn-prompt.md"
ACTION_SCHEMA = "schemas/printobserver-types/PrintAction.json"
ASSESSMENT_SCHEMA = "schemas/printobserver-types/AgentAssessment.json"

# A source that spawns something whose name it worked out at run time. Nothing
# in it says `oneharness`, which is the whole point: the check refuses the
# interface, not the executable.
COMPUTED_SPAWN = """//! A fixture: a source that spawns a name it computed.

/// Start whatever this works out the name of.
pub fn start(part: &str) {
    let program = format!("one{part}arness");
    let _ = std::process::Command::new(program).spawn();
}
"""

# The same spawn behind an alias, so that neither the type's name nor the
# executable's appears in the call that finishes it.
ALIASED_SPAWN = """//! A fixture: the same spawn, behind an alias.

use std::process::Command as Runner;

/// Start whatever it was handed.
pub fn start(program: &str) {
    let _ = Runner::new(program).output();
}
"""


def test_the_committed_crate_spawns_nothing(committed: Repo) -> None:
    """The crate as it stands uses no process-spawning interface."""
    accepted(spawn_free(committed))


def test_a_source_spawning_a_computed_executable_name_is_refused(
    tree: Callable[[], Tree],
) -> None:
    """A spawn whose executable is computed is refused all the same."""
    copy = tree()
    copy.write(f"{CRATE}/src/spawner.rs", COMPUTED_SPAWN)
    refused(spawn_free(copy.repo), "src/spawner.rs")


def test_a_spawn_behind_an_alias_is_refused(tree: Callable[[], Tree]) -> None:
    """Renaming the type does not get a spawn past the check."""
    copy = tree()
    copy.write(f"{CRATE}/src/aliased.rs", ALIASED_SPAWN)
    refused(spawn_free(copy.repo), "src/aliased.rs")


def test_the_committed_crate_carries_no_schema_of_its_own(committed: Repo) -> None:
    """The crate as it stands carries no schema file."""
    accepted(schema_source(committed))


def test_a_schema_file_the_crate_carries_is_refused(tree: Callable[[], Tree]) -> None:
    """A copy of the generated bytes, carried by the crate, is still refused."""
    copy = tree()
    copy.write(f"{CRATE}/assessment-schema.json", copy.read(ASSESSMENT_SCHEMA))
    refused(schema_source(copy.repo), "assessment-schema.json")


def test_the_smallest_schema_the_crate_could_carry_is_refused(
    tree: Callable[[], Tree],
) -> None:
    """A schema need not be the generated one, or large, to be one it carries."""
    copy = tree()
    copy.write(f"{CRATE}/tiny-schema.json", json.dumps({"type": "object"}))
    refused(schema_source(copy.repo), "tiny-schema.json")


def test_a_schemas_directory_for_the_adapter_is_refused(tree: Callable[[], Tree]) -> None:
    """A schema checked in under the adapter's own name is refused too."""
    copy = tree()
    copy.write(
        "schemas/printobserver-oneharness/AgentAssessment.json",
        copy.read(ASSESSMENT_SCHEMA),
    )
    refused(schema_source(copy.repo), "schemas/printobserver-oneharness")


def test_the_committed_template_names_no_operation_but_the_context_read(
    committed: Repo,
) -> None:
    """The template as it stands is accepted."""
    accepted(prompt_template(committed))


def _forbidden_names(copy: Tree) -> list[str]:
    """Every operation the template may not name, derived as the check derives it."""
    schema = json.loads(copy.read(ACTION_SCHEMA))
    variants = [arm["properties"]["action"]["const"] for arm in schema["oneOf"]]
    reads = copy.repo.policy["supervisor"]["reads"]
    context_read = copy.repo.policy["supervisor"]["context_read"]
    return [name for name in [*variants, *reads] if name != context_read]


def test_every_member_of_the_derived_set_is_refused(tree: Callable[[], Tree]) -> None:
    """Each `PrintAction` variant, and each read but the context one, is refused."""
    copy = tree()
    template = copy.read(TEMPLATE)
    names = _forbidden_names(copy)
    if len(names) < 2:
        message = f"the derived set is {names}, which is not a set worth walking"
        raise AssertionError(message)
    for name in names:
        copy.write(TEMPLATE, f"{template}\n\nThen run `printobserver {name}`.\n")
        refused(prompt_template(copy.repo), f"printobserver {name}")
    copy.write(TEMPLATE, template)


def test_the_context_read_is_the_one_operation_the_template_may_name(
    tree: Callable[[], Tree],
) -> None:
    """Naming the read this turn is about is not what the rule refuses."""
    copy = tree()
    context_read = copy.repo.policy["supervisor"]["context_read"]
    copy.append(TEMPLATE, f"\n\nRun `printobserver {context_read}` to read the print.\n")
    accepted(prompt_template(copy.repo), describing="a template naming the context read")


def test_a_variant_the_vocabulary_gains_enters_the_forbidden_set(
    tree: Callable[[], Tree],
) -> None:
    """A variant `PrintAction` gains is refused with no edit to the walk.

    The set is derived from the artifact the contracts' generation target
    writes, so a variant that lands there is covered the moment it lands.
    """
    copy = tree()
    schema = json.loads(copy.read(ACTION_SCHEMA))
    schema["oneOf"].append(
        {
            "type": "object",
            "properties": {"action": {"const": "purge_nozzle", "type": "string"}},
            "required": ["action"],
        }
    )
    copy.write(ACTION_SCHEMA, json.dumps(schema, indent=2))
    copy.append(TEMPLATE, "\n\nThen run `printobserver purge-nozzle`.\n")
    refused(prompt_template(copy.repo), "printobserver purge-nozzle")


def test_an_action_vocabulary_that_declares_nothing_is_refused(
    tree: Callable[[], Tree],
) -> None:
    """A walk over an empty vocabulary would cover nothing, so it is refused."""
    copy = tree()
    copy.write(ACTION_SCHEMA, json.dumps({"title": "PrintAction"}))
    refused(prompt_template(copy.repo), "declares no variants")


def test_the_committed_holders_all_take_the_same_schema_lock(committed: Repo) -> None:
    """The two suites that read the checked-in schema tree lock one file."""
    accepted(schema_lock(committed))


def _holders(copy: Tree) -> list[str]:
    """The suites the policy declares as holders of the schema lock."""
    return [str(path) for path in copy.repo.policy["supervisor"]["schema_lock_holders"]]


def test_a_holder_locking_another_file_is_refused(tree: Callable[[], Tree]) -> None:
    """Two suites locking two different files are back to no lock at all."""
    copy = tree()
    holder = _holders(copy)[0]
    name = copy.repo.policy["supervisor"]["schema_lock"]
    copy.edit(holder, name, "some-other.lock")
    refused(schema_lock(copy.repo), holder)


def test_a_holder_that_never_takes_the_lock_is_refused(tree: Callable[[], Tree]) -> None:
    """Naming the file is not taking the lock on it."""
    copy = tree()
    holder = _holders(copy)[1]
    copy.write(holder, copy.read(holder).replace(".lock()", ".metadata()"))
    refused(schema_lock(copy.repo), "never takes the lock")


def test_a_lock_only_one_suite_takes_is_refused(tree: Callable[[], Tree]) -> None:
    """A lock one side takes serializes nothing, so a lone holder is refused."""
    copy = tree()
    policy = copy.read("repo-policy.toml")
    holders = _holders(copy)
    copy.write(
        "repo-policy.toml",
        policy.replace(f'    "{holders[1]}",\n', "", 1),
    )
    refused(schema_lock(copy.repo), "fewer than two")


POLICY = "repo-policy.toml"
SKILL = f"{CRATE}/assets/printobserver-skill.md"


def _without_the_supervisor_section(copy: Tree) -> None:
    """Drop the `[supervisor]` policy all four checks are declared by."""
    text = copy.read(POLICY)
    start = text.index("[supervisor]")
    end = text.index("[octoprint]")
    copy.write(POLICY, text[:start] + text[end:])


def test_every_check_says_so_when_the_policy_declares_no_supervisor(
    tree: Callable[[], Tree],
) -> None:
    """A rule with no subject is refused rather than passing over nothing."""
    copy = tree()
    _without_the_supervisor_section(copy)
    repo = copy.repo

    for findings in (
        spawn_free(repo),
        schema_source(repo),
        prompt_template(repo),
        schema_lock(repo),
    ):
        refused(findings, "declares no `[supervisor]` section")


def test_an_adapter_crate_with_no_sources_is_refused(tree: Callable[[], Tree]) -> None:
    """A spawn rule over a crate with nothing to read guards nothing."""
    copy = tree()
    copy.remove(f"{CRATE}/src")

    refused(spawn_free(copy.repo), "no `src` directory")


def test_a_tree_without_the_generated_assessment_schema_is_refused(
    tree: Callable[[], Tree],
) -> None:
    """With the artifact absent, nothing constrains the agent's answer."""
    copy = tree()
    copy.remove(ASSESSMENT_SCHEMA)

    refused(schema_source(copy.repo), "is absent, so nothing")


def test_json_the_crate_carries_that_is_not_a_schema_is_left_alone(
    tree: Callable[[], Tree],
) -> None:
    """The rule is about schemas, so ordinary and unreadable JSON pass it."""
    copy = tree()
    copy.write(f"{CRATE}/fixtures/truncated.json", '{"$defs": ')
    copy.write(f"{CRATE}/fixtures/arms.json", '["pause_print", "cancel_print"]')
    copy.write(f"{CRATE}/fixtures/settings.json", json.dumps({"timeout_seconds": 30}))

    accepted(
        schema_source(copy.repo),
        describing="a crate carrying JSON that is not a schema",
    )


def test_a_generated_schema_under_the_crate_s_build_directory_is_left_alone(
    tree: Callable[[], Tree],
) -> None:
    """`target` holds what a build wrote, not what the crate carries."""
    copy = tree()
    copy.write(f"{CRATE}/target/debug/AgentAssessment.json", copy.read(ASSESSMENT_SCHEMA))

    accepted(
        schema_source(copy.repo),
        describing="a schema a build left under the crate's target directory",
    )


def test_a_tree_without_the_committed_skill_is_refused(tree: Callable[[], Tree]) -> None:
    """The system prompt is read from the tree, so the tree has to carry it."""
    copy = tree()
    copy.remove(SKILL)

    refused(prompt_template(copy.repo), "the committed skill")


def test_a_context_read_the_reads_do_not_name_is_refused(tree: Callable[[], Tree]) -> None:
    """The one operation the template may name has to be one of the reads."""
    copy = tree()
    copy.edit(POLICY, 'context_read = "context"', 'context_read = "diagnose"')

    refused(prompt_template(copy.repo), "which its `reads` do not")


def test_a_tree_without_the_committed_template_is_refused(tree: Callable[[], Tree]) -> None:
    """What a prompt may say is one committed file, and a missing one says anything."""
    copy = tree()
    copy.remove(TEMPLATE)

    refused(prompt_template(copy.repo), "prompt template")


def test_a_tree_without_the_action_vocabulary_is_refused(tree: Callable[[], Tree]) -> None:
    """The forbidden set is derived from that artifact, so its absence is a hole."""
    copy = tree()
    copy.remove(ACTION_SCHEMA)

    refused(prompt_template(copy.repo), "is absent")


def test_an_action_vocabulary_that_is_not_json_is_refused(tree: Callable[[], Tree]) -> None:
    """A vocabulary nothing can parse derives no set, and says so."""
    copy = tree()
    copy.write(ACTION_SCHEMA, '{"oneOf": [')

    refused(prompt_template(copy.repo), "is not JSON")


def test_an_action_vocabulary_whose_arms_name_no_variant_is_refused(
    tree: Callable[[], Tree],
) -> None:
    """Arms that tag nothing are a vocabulary that declares nothing."""
    copy = tree()
    copy.write(ACTION_SCHEMA, json.dumps({"oneOf": [{"type": "object", "properties": {}}]}))

    refused(prompt_template(copy.repo), "declares no variants")


def test_an_arm_whose_nested_values_are_not_mappings_is_skipped(
    tree: Callable[[], Tree],
) -> None:
    """A generated file this check cannot read is a finding, never a traceback.

    Every step down into an arm is narrowed, so an arm whose `properties` or
    whose `action` is something other than a mapping declares no variant and is
    passed over — leaving the arms that do declare one still refused.
    """
    copy = tree()
    schema = json.loads(copy.read(ACTION_SCHEMA))
    variant = schema["oneOf"][0]["properties"]["action"]["const"]
    schema["oneOf"].insert(0, {"type": "object", "properties": ["action"]})
    schema["oneOf"].insert(1, {"type": "object", "properties": {"action": "pause_print"}})
    copy.write(ACTION_SCHEMA, json.dumps(schema, indent=2))
    copy.append(TEMPLATE, f"\n\nThen run `printobserver {variant}`.\n")

    refused(prompt_template(copy.repo), f"printobserver {variant}")


def test_an_arm_naming_no_variant_does_not_hide_the_ones_that_do(
    tree: Callable[[], Tree],
) -> None:
    """One unreadable arm narrows the derived set by itself and nothing else."""
    copy = tree()
    schema = json.loads(copy.read(ACTION_SCHEMA))
    variant = schema["oneOf"][0]["properties"]["action"]["const"]
    schema["oneOf"].insert(0, {"type": "object", "properties": {}})
    copy.write(ACTION_SCHEMA, json.dumps(schema, indent=2))
    copy.append(TEMPLATE, f"\n\nThen run `printobserver {variant}`.\n")

    refused(prompt_template(copy.repo), f"printobserver {variant}")


def test_a_declared_holder_that_is_absent_is_refused(tree: Callable[[], Tree]) -> None:
    """A holder that is not in the tree takes no lock at all."""
    copy = tree()
    holder = _holders(copy)[0]
    copy.remove(holder)

    refused(schema_lock(copy.repo), "declared schema-lock holder")


def test_the_committed_policy_reads_as_the_declarations_the_checks_act_on(
    committed: Repo,
) -> None:
    """The section as it stands narrows to the values these checks are written in."""
    policy = supervisor_policy(committed)

    equal(policy.adapter, "printobserver-oneharness")
    equal(policy.context_read in policy.reads, True)
    equal(len(policy.schema_lock_holders), 2)


def _retype(copy: Tree, key: str, replacement: str) -> None:
    """Rewrite one declaration of the `[supervisor]` section.

    A declaration runs to the line that closes it, so a list written over
    several lines is replaced whole rather than leaving its entries behind as
    TOML nothing can parse.
    """
    text = copy.read(POLICY)
    start = text.index("[supervisor]")
    end = text.index("[octoprint]")
    lines = text[start:end].splitlines(keepends=True)
    first = next(index for index, line in enumerate(lines) if line.startswith(f"{key} = "))
    last = first
    depth = lines[first].count("[") - lines[first].count("]")
    while depth:
        last += 1
        depth += lines[last].count("[") - lines[last].count("]")
    rewritten = lines[:first] + ([f"{replacement}\n"] if replacement else []) + lines[last + 1 :]
    copy.write(POLICY, text[:start] + "".join(rewritten) + text[end:])


def test_a_declaration_the_checks_read_as_a_name_is_refused_when_it_is_not_one(
    tree: Callable[[], Tree],
) -> None:
    """Every check names the key rather than failing the tier with a traceback."""
    copy = tree()
    _retype(copy, "adapter", "adapter = 7")
    repo = copy.repo

    for findings in (
        spawn_free(repo),
        schema_source(repo),
        prompt_template(repo),
        schema_lock(repo),
    ):
        refused(findings, "no `supervisor.adapter` string")


def test_a_declaration_read_as_a_name_is_refused_when_it_is_missing(
    tree: Callable[[], Tree],
) -> None:
    """A key a check acts on is refused where the section is parsed."""
    copy = tree()
    _retype(copy, "context_read", "")

    refused(prompt_template(copy.repo), "no `supervisor.context_read` string")


def test_a_declaration_read_as_a_list_is_refused_when_it_is_not_one(
    tree: Callable[[], Tree],
) -> None:
    """A list read as a string would walk its characters, so it is refused first."""
    copy = tree()
    _retype(copy, "reads", 'reads = "status"')

    refused(prompt_template(copy.repo), "no non-empty `supervisor.reads` list")


def test_a_list_holding_something_that_is_not_a_name_is_refused(
    tree: Callable[[], Tree],
) -> None:
    """One entry that is not a name is refused naming what was declared."""
    copy = tree()
    _retype(copy, "schema_lock_holders", "schema_lock_holders = [7]")

    refused(schema_lock(copy.repo), "which is not a name")
