"""The supervisor adapter's three structural claims, each driven against a defect.

Every journey drives the committed check against a real copy of the committed
tree with one defect in it. The spawn journeys matter most: the fixture crate
they add spawns an executable whose name it *computes*, which is exactly the
path a rule keyed on the word `oneharness` would let through.
"""

from __future__ import annotations

import json
from collections.abc import Callable

from repo_checks.checks_supervisor import (
    prompt_template,
    schema_lock,
    schema_source,
    spawn_free,
)
from repo_checks.expect import accepted, refused
from repo_checks.model import Repo
from treecopy import Tree

CRATE = "crates/printobserver-oneharness"
TEMPLATE = f"{CRATE}/assets/turn-prompt.md"
ACTION_SCHEMA = "schemas/printobserver-types/PrintAction.json"
ASSESSMENT_SCHEMA = "schemas/printobserver-types/AgentAssessment.json"

# A source that spawns something whose name it worked out at run time. Nothing
# in it says `oneharness`, which is the whole point: the check refuses the
# interface, not the executable.
COMPUTED_SPAWN = """//! A fixture: a source that spawns a name it computed.

/// Start whatever this works out the name of.
pub fn start(part: &str) {
    let program = format!("one{part}arness");
    let _ = std::process::Command::new(program).spawn();
}
"""

# The same spawn behind an alias, so that neither the type's name nor the
# executable's appears in the call that finishes it.
ALIASED_SPAWN = """//! A fixture: the same spawn, behind an alias.

use std::process::Command as Runner;

/// Start whatever it was handed.
pub fn start(program: &str) {
    let _ = Runner::new(program).output();
}
"""


def test_the_committed_crate_spawns_nothing(committed: Repo) -> None:
    """The crate as it stands uses no process-spawning interface."""
    accepted(spawn_free(committed))


def test_a_source_spawning_a_computed_executable_name_is_refused(
    tree: Callable[[], Tree],
) -> None:
    """A spawn whose executable is computed is refused all the same."""
    copy = tree()
    copy.write(f"{CRATE}/src/spawner.rs", COMPUTED_SPAWN)
    refused(spawn_free(copy.repo), "src/spawner.rs")


def test_a_spawn_behind_an_alias_is_refused(tree: Callable[[], Tree]) -> None:
    """Renaming the type does not get a spawn past the check."""
    copy = tree()
    copy.write(f"{CRATE}/src/aliased.rs", ALIASED_SPAWN)
    refused(spawn_free(copy.repo), "src/aliased.rs")


def test_the_committed_crate_carries_no_schema_of_its_own(committed: Repo) -> None:
    """The crate as it stands carries no schema file."""
    accepted(schema_source(committed))


def test_a_schema_file_the_crate_carries_is_refused(tree: Callable[[], Tree]) -> None:
    """A copy of the generated bytes, carried by the crate, is still refused."""
    copy = tree()
    copy.write(f"{CRATE}/assessment-schema.json", copy.read(ASSESSMENT_SCHEMA))
    refused(schema_source(copy.repo), "assessment-schema.json")


def test_a_schemas_directory_for_the_adapter_is_refused(tree: Callable[[], Tree]) -> None:
    """A schema checked in under the adapter's own name is refused too."""
    copy = tree()
    copy.write(
        "schemas/printobserver-oneharness/AgentAssessment.json",
        copy.read(ASSESSMENT_SCHEMA),
    )
    refused(schema_source(copy.repo), "schemas/printobserver-oneharness")


def test_the_committed_template_names_no_operation_but_the_context_read(
    committed: Repo,
) -> None:
    """The template as it stands is accepted."""
    accepted(prompt_template(committed))


def _forbidden_names(copy: Tree) -> list[str]:
    """Every operation the template may not name, derived as the check derives it."""
    schema = json.loads(copy.read(ACTION_SCHEMA))
    variants = [arm["properties"]["action"]["const"] for arm in schema["oneOf"]]
    reads = copy.repo.policy["supervisor"]["reads"]
    context_read = copy.repo.policy["supervisor"]["context_read"]
    return [name for name in [*variants, *reads] if name != context_read]


def test_every_member_of_the_derived_set_is_refused(tree: Callable[[], Tree]) -> None:
    """Each `PrintAction` variant, and each read but the context one, is refused."""
    copy = tree()
    template = copy.read(TEMPLATE)
    names = _forbidden_names(copy)
    if len(names) < 2:
        message = f"the derived set is {names}, which is not a set worth walking"
        raise AssertionError(message)
    for name in names:
        copy.write(TEMPLATE, f"{template}\n\nThen run `printobserver {name}`.\n")
        refused(prompt_template(copy.repo), f"printobserver {name}")
    copy.write(TEMPLATE, template)


def test_the_context_read_is_the_one_operation_the_template_may_name(
    tree: Callable[[], Tree],
) -> None:
    """Naming the read this turn is about is not what the rule refuses."""
    copy = tree()
    context_read = copy.repo.policy["supervisor"]["context_read"]
    copy.append(TEMPLATE, f"\n\nRun `printobserver {context_read}` to read the print.\n")
    accepted(prompt_template(copy.repo), describing="a template naming the context read")


def test_a_variant_the_vocabulary_gains_enters_the_forbidden_set(
    tree: Callable[[], Tree],
) -> None:
    """A variant `PrintAction` gains is refused with no edit to the walk.

    The set is derived from the artifact the contracts' generation target
    writes, so a variant that lands there is covered the moment it lands.
    """
    copy = tree()
    schema = json.loads(copy.read(ACTION_SCHEMA))
    schema["oneOf"].append(
        {
            "type": "object",
            "properties": {"action": {"const": "purge_nozzle", "type": "string"}},
            "required": ["action"],
        }
    )
    copy.write(ACTION_SCHEMA, json.dumps(schema, indent=2))
    copy.append(TEMPLATE, "\n\nThen run `printobserver purge-nozzle`.\n")
    refused(prompt_template(copy.repo), "printobserver purge-nozzle")


def test_an_action_vocabulary_that_declares_nothing_is_refused(
    tree: Callable[[], Tree],
) -> None:
    """A walk over an empty vocabulary would cover nothing, so it is refused."""
    copy = tree()
    copy.write(ACTION_SCHEMA, json.dumps({"title": "PrintAction"}))
    refused(prompt_template(copy.repo), "declares no variants")


def test_the_committed_holders_all_take_the_same_schema_lock(committed: Repo) -> None:
    """The two suites that read the checked-in schema tree lock one file."""
    accepted(schema_lock(committed))


def _holders(copy: Tree) -> list[str]:
    """The suites the policy declares as holders of the schema lock."""
    return [str(path) for path in copy.repo.policy["supervisor"]["schema_lock_holders"]]


def test_a_holder_locking_another_file_is_refused(tree: Callable[[], Tree]) -> None:
    """Two suites locking two different files are back to no lock at all."""
    copy = tree()
    holder = _holders(copy)[0]
    name = copy.repo.policy["supervisor"]["schema_lock"]
    copy.edit(holder, name, "some-other.lock")
    refused(schema_lock(copy.repo), holder)


def test_a_holder_that_never_takes_the_lock_is_refused(tree: Callable[[], Tree]) -> None:
    """Naming the file is not taking the lock on it."""
    copy = tree()
    holder = _holders(copy)[1]
    copy.write(holder, copy.read(holder).replace(".lock()", ".metadata()"))
    refused(schema_lock(copy.repo), "never takes the lock")


def test_a_lock_only_one_suite_takes_is_refused(tree: Callable[[], Tree]) -> None:
    """A lock one side takes serializes nothing, so a lone holder is refused."""
    copy = tree()
    policy = copy.read("repo-policy.toml")
    holders = _holders(copy)
    copy.write(
        "repo-policy.toml",
        policy.replace(f'    "{holders[1]}",\n', "", 1),
    )
    refused(schema_lock(copy.repo), "fewer than two")
