"""What every generated file says about itself, in whichever language it is in.

A reader who opens one of these files has to be told two things before
anything else: that nothing they change here will survive, and where to change
it instead. `just check-generated` refuses a tree in which any generated file
differs from what the generator writes, so an edit made here is an edit the
gate reports rather than one that quietly persists.
"""

from __future__ import annotations

#: The sentence a check looks for to know a file claims to be generated. It is
#: the same words in all three languages, so one check reads all three.
MARK = "Generated by `contract-codegen` from the checked-in contract schemas."

#: What a reader is told to do instead of editing the file in front of them.
INSTEAD = (
    "Do not edit by hand: change the contracts, regenerate with "
    "`just generate-clients`, and commit what that writes."
)


def banner(comment: str, describing: str) -> str:
    """The generated-file banner, as one language's comment.

    Wrapped like every other comment the generator writes, because none of the
    three formatters reflows one and a banner nobody wrapped would be the one
    over-long line in each of the three clients.
    """
    from contract_codegen.doc import wrapped

    lines = [
        MARK,
        "",
        f"This file is {describing}.",
        "",
        *wrapped(INSTEAD),
    ]
    return "\n".join(f"{comment} {line}".rstrip() for line in lines)
