/**
 *  Generated by `contract-codegen` from the checked-in contract schemas.
 *
 *  This file is the Node client's walk over every operation, against a real supervisor.
 *
 *  Do not edit by hand: change the contracts, regenerate with `just
 *  generate-clients`, and commit what that writes.
 *
 * Every method this client exposes is driven against the **real**
 * printobserver supervisor — the program this repository builds, over the
 * OctoPrint `just octoprint-up` started, holding a print and a stored image
 * the supervisor's own ingress opened. A recording proxy sits in front of
 * it, so what each assertion is against is the request that supervisor
 * received and the answer it actually sent.
 *
 * The order is the one a real machine admits: a printer is a state machine
 * and the policy refuses an action that is not valid from where it is. It
 * ends with the machine printing, where the bring-up left it.
 */

import { afterAll, beforeAll, expect, test } from "bun:test";
import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { Client } from "../src/client.ts";
import type { JobManifest } from "../src/contract.ts";
import { Rejected } from "../src/surface.ts";
import { Recording, ready, same } from "./live.ts";
import { SETUP_TIMEOUT_MS, Standing, type Supervisor } from "./world.ts";

/** The reason every mutating call of this walk carries. */
const REASON = "a generated walk is asking";

let standing: Standing;
let world: Supervisor;

beforeAll(async () => {
  standing = await Standing.standing(mkdtempSync(join(tmpdir(), "printobserver-live-")));
  world = standing.at;
}, SETUP_TIMEOUT_MS);

afterAll(async () => {
  await standing.stop();
});

/**
 * The manifest this walk writes and starts a print under.
 *
 * It narrows nothing: what the walk needs is every adjustment the envelope
 * allows to be answered, and a narrowing here would refuse one for a reason
 * that is not what this walk is about.
 */
function manifest(at: Supervisor): JobManifest {
  return {
    file_name: at.file_name,
    material: "PLA",
    nozzle_diameter_mm: 0.4,
    slicer_profile: "the walk over every operation",
    allowed: {},
    metadata: {},
  };
}

/** `status`, answered by a real supervisor. */
async function stepStatus(client: Client, proxy: Recording) {
  await ready(client, world.print_id, "");

  const answered = await client.status(world.print_id);

  const seen = proxy.last();
  expect(seen.method).toBe("GET");
  expect(seen.target).toBe(`/v1/prints/${world.print_id}/status`);
  expect(seen.status).toBe(200);
  expect(seen.body).toBe("");
  same("status", answered, seen.answer);
}

/** `context`, answered by a real supervisor. */
async function stepContext(client: Client, proxy: Recording) {
  await ready(client, world.print_id, "");

  const answered = await client.context(world.print_id);

  const seen = proxy.last();
  expect(seen.method).toBe("GET");
  expect(seen.target).toBe(`/v1/prints/${world.print_id}/context`);
  expect(seen.status).toBe(200);
  expect(seen.body).toBe("");
  same("context", answered, seen.answer);
}

/** `image`, answered by a real supervisor. */
async function stepImage(client: Client, proxy: Recording) {
  await ready(client, world.print_id, "");

  const answered = await client.image(world.image_id);

  const seen = proxy.last();
  expect(seen.method).toBe("GET");
  expect(seen.target).toBe(`/v1/images/${world.image_id}`);
  expect(seen.status).toBe(200);
  expect(seen.body).toBe("");
  same("image", answered, seen.answer);
}

/** `manifest_set`, answered by a real supervisor. */
async function stepManifestSet(client: Client, proxy: Recording) {
  await ready(client, world.print_id, "");

  const answered = await client.manifestSet(world.print_id, REASON, manifest(world));

  const seen = proxy.last();
  expect(seen.method).toBe("PUT");
  expect(seen.target).toBe(`/v1/prints/${world.print_id}/manifest`);
  expect(seen.status).toBe(200);
  const sent = JSON.parse(seen.body);
  expect(sent.reason).toEqual(REASON);
  expect(sent.manifest).toEqual(manifest(world));
  same("manifest_set", answered, seen.answer);
}

/** `manifest_get`, answered by a real supervisor. */
async function stepManifestGet(client: Client, proxy: Recording) {
  await ready(client, world.print_id, "");

  const answered = await client.manifestGet(world.print_id);

  const seen = proxy.last();
  expect(seen.method).toBe("GET");
  expect(seen.target).toBe(`/v1/prints/${world.print_id}/manifest`);
  expect(seen.status).toBe(200);
  expect(seen.body).toBe("");
  same("manifest_get", answered, seen.answer);
}

/** `history`, answered by a real supervisor. */
async function stepHistory(client: Client, proxy: Recording) {
  await ready(client, world.print_id, "");

  const answered = await client.history(world.print_id, 20);

  const seen = proxy.last();
  expect(seen.method).toBe("GET");
  expect(seen.target).toBe(`/v1/prints/${world.print_id}/history?limit=${20}`);
  expect(seen.status).toBe(200);
  expect(seen.body).toBe("");
  same("history", answered, seen.answer);
}

/** `cancel`, answered by a real supervisor. */
async function stepCancel(client: Client, proxy: Recording) {
  await ready(client, world.print_id, "printing");

  const answered = await client.cancel(world.print_id, REASON);

  const seen = proxy.last();
  expect(seen.method).toBe("POST");
  expect(seen.target).toBe(`/v1/prints/${world.print_id}/actions/cancel`);
  expect(seen.status).toBe(200);
  const sent = JSON.parse(seen.body);
  expect(sent.actor).toBe("operator");
  expect(sent.reason).toEqual(REASON);
  same("cancel", answered, seen.answer);
}

/** `start_print`, answered by a real supervisor. */
async function stepStartPrint(client: Client, proxy: Recording) {
  await ready(client, world.print_id, "operational");

  const answered = await client.startPrint(
    world.print_id,
    world.file_name,
    manifest(world),
    REASON,
  );

  const seen = proxy.last();
  expect(seen.method).toBe("POST");
  expect(seen.target).toBe(`/v1/prints/${world.print_id}/actions/start_print`);
  expect(seen.status).toBe(200);
  const sent = JSON.parse(seen.body);
  expect(sent.actor).toBe("operator");
  expect(sent.file_name).toEqual(world.file_name);
  expect(sent.manifest).toEqual(manifest(world));
  expect(sent.reason).toEqual(REASON);
  same("start_print", answered, seen.answer);
}

/** `set_feedrate_factor`, answered by a real supervisor. */
async function stepSetFeedrateFactor(client: Client, proxy: Recording) {
  await ready(client, world.print_id, "printing");

  const answered = await client.setFeedrateFactor(world.print_id, 1.1, REASON, 60);

  const seen = proxy.last();
  expect(seen.method).toBe("POST");
  expect(seen.target).toBe(`/v1/prints/${world.print_id}/actions/set_feedrate_factor`);
  expect(seen.status).toBe(200);
  const sent = JSON.parse(seen.body);
  expect(sent.actor).toBe("operator");
  expect(sent.duration_s).toEqual(60);
  expect(sent.factor).toEqual(1.1);
  expect(sent.reason).toEqual(REASON);
  same("set_feedrate_factor", answered, seen.answer);
}

/** `set_flowrate_factor`, answered by a real supervisor. */
async function stepSetFlowrateFactor(client: Client, proxy: Recording) {
  await ready(client, world.print_id, "printing");

  const answered = await client.setFlowrateFactor(world.print_id, 1.0, REASON, 60);

  const seen = proxy.last();
  expect(seen.method).toBe("POST");
  expect(seen.target).toBe(`/v1/prints/${world.print_id}/actions/set_flowrate_factor`);
  expect(seen.status).toBe(200);
  const sent = JSON.parse(seen.body);
  expect(sent.actor).toBe("operator");
  expect(sent.duration_s).toEqual(60);
  expect(sent.factor).toEqual(1.0);
  expect(sent.reason).toEqual(REASON);
  same("set_flowrate_factor", answered, seen.answer);
}

/** `set_fan_percent`, answered by a real supervisor. */
async function stepSetFanPercent(client: Client, proxy: Recording) {
  await ready(client, world.print_id, "printing");

  const answered = await client.setFanPercent(world.print_id, 50.0, REASON, 60);

  const seen = proxy.last();
  expect(seen.method).toBe("POST");
  expect(seen.target).toBe(`/v1/prints/${world.print_id}/actions/set_fan_percent`);
  expect(seen.status).toBe(200);
  const sent = JSON.parse(seen.body);
  expect(sent.actor).toBe("operator");
  expect(sent.duration_s).toEqual(60);
  expect(sent.percent).toEqual(50.0);
  expect(sent.reason).toEqual(REASON);
  same("set_fan_percent", answered, seen.answer);
}

/** `set_tool_target_c`, answered by a real supervisor. */
async function stepSetToolTargetC(client: Client, proxy: Recording) {
  await ready(client, world.print_id, "printing");

  const answered = await client.setToolTargetC(world.print_id, REASON, 210.0, 0, 60);

  const seen = proxy.last();
  expect(seen.method).toBe("POST");
  expect(seen.target).toBe(`/v1/prints/${world.print_id}/actions/set_tool_target_c`);
  expect(seen.status).toBe(200);
  const sent = JSON.parse(seen.body);
  expect(sent.actor).toBe("operator");
  expect(sent.duration_s).toEqual(60);
  expect(sent.reason).toEqual(REASON);
  expect(sent.target_c).toEqual(210.0);
  expect(sent.tool).toEqual(0);
  same("set_tool_target_c", answered, seen.answer);
}

/** `set_bed_target_c`, answered by a real supervisor. */
async function stepSetBedTargetC(client: Client, proxy: Recording) {
  await ready(client, world.print_id, "printing");

  const answered = await client.setBedTargetC(world.print_id, REASON, 60.0, 60);

  const seen = proxy.last();
  expect(seen.method).toBe("POST");
  expect(seen.target).toBe(`/v1/prints/${world.print_id}/actions/set_bed_target_c`);
  expect(seen.status).toBe(200);
  const sent = JSON.parse(seen.body);
  expect(sent.actor).toBe("operator");
  expect(sent.duration_s).toEqual(60);
  expect(sent.reason).toEqual(REASON);
  expect(sent.target_c).toEqual(60.0);
  same("set_bed_target_c", answered, seen.answer);
}

/** `acknowledge_failure`, answered by a real supervisor. */
async function stepAcknowledgeFailure(client: Client, proxy: Recording) {
  await ready(client, world.print_id, "");

  const answered = await client.acknowledgeFailure(
    world.print_id,
    "continue",
    world.event_id,
    REASON,
  );

  const seen = proxy.last();
  expect(seen.method).toBe("POST");
  expect(seen.target).toBe(`/v1/prints/${world.print_id}/actions/acknowledge_failure`);
  expect(seen.status).toBe(200);
  const sent = JSON.parse(seen.body);
  expect(sent.actor).toBe("operator");
  expect(sent.disposition).toEqual("continue");
  expect(sent.event_id).toEqual(world.event_id);
  expect(sent.reason).toEqual(REASON);
  same("acknowledge_failure", answered, seen.answer);
}

/** `pause`, answered by a real supervisor. */
async function stepPause(client: Client, proxy: Recording) {
  await ready(client, world.print_id, "printing");

  const answered = await client.pause(world.print_id, REASON);

  const seen = proxy.last();
  expect(seen.method).toBe("POST");
  expect(seen.target).toBe(`/v1/prints/${world.print_id}/actions/pause`);
  expect(seen.status).toBe(200);
  const sent = JSON.parse(seen.body);
  expect(sent.actor).toBe("operator");
  expect(sent.reason).toEqual(REASON);
  same("pause", answered, seen.answer);
}

/** `resume`, answered by a real supervisor. */
async function stepResume(client: Client, proxy: Recording) {
  await ready(client, world.print_id, "paused");

  const answered = await client.resume(world.print_id, REASON);

  const seen = proxy.last();
  expect(seen.method).toBe("POST");
  expect(seen.target).toBe(`/v1/prints/${world.print_id}/actions/resume`);
  expect(seen.status).toBe(200);
  const sent = JSON.parse(seen.body);
  expect(sent.actor).toBe("operator");
  expect(sent.reason).toEqual(REASON);
  same("resume", answered, seen.answer);
}

test("every method is answered by a real supervisor", async () => {
  await using proxy = new Recording(world.server);
  const client = new Client({ server: proxy.url, actor: "operator" });

  await stepStatus(client, proxy);
  await stepContext(client, proxy);
  await stepImage(client, proxy);
  await stepManifestSet(client, proxy);
  await stepManifestGet(client, proxy);
  await stepHistory(client, proxy);
  await stepCancel(client, proxy);
  await stepStartPrint(client, proxy);
  await stepSetFeedrateFactor(client, proxy);
  await stepSetFlowrateFactor(client, proxy);
  await stepSetFanPercent(client, proxy);
  await stepSetToolTargetC(client, proxy);
  await stepSetBedTargetC(client, proxy);
  await stepAcknowledgeFailure(client, proxy);
  await stepPause(client, proxy);
  await stepResume(client, proxy);

  expect(proxy.calls()).toBeGreaterThanOrEqual(16);
}, 900_000);

/** `cancel`, refused by a real supervisor's own policy. */
async function refusedCancel(client: Client, proxy: Recording) {
  const refused = await client.cancel(world.print_id, REASON).catch((raised: unknown) => raised);

  expect(refused).toBeInstanceOf(Rejected);
  expect((refused as Rejected).reason).toHaveProperty("actor_may_not_request");
  const seen = proxy.last();
  expect(seen.status).toBe(409);
  same("cancel", (refused as Rejected).answer, seen.answer);
}

/** `start_print`, refused by a real supervisor's own policy. */
async function refusedStartPrint(client: Client, proxy: Recording) {
  const refused = await client
    .startPrint(world.print_id, world.file_name, manifest(world), REASON)
    .catch((raised: unknown) => raised);

  expect(refused).toBeInstanceOf(Rejected);
  expect((refused as Rejected).reason).toHaveProperty("actor_may_not_request");
  const seen = proxy.last();
  expect(seen.status).toBe(409);
  same("start_print", (refused as Rejected).answer, seen.answer);
}

/** `set_feedrate_factor`, refused by a real supervisor's own policy. */
async function refusedSetFeedrateFactor(client: Client, proxy: Recording) {
  const refused = await client
    .setFeedrateFactor(world.print_id, 1.1, REASON, 60)
    .catch((raised: unknown) => raised);

  expect(refused).toBeInstanceOf(Rejected);
  expect((refused as Rejected).reason).toHaveProperty("actor_may_not_request");
  const seen = proxy.last();
  expect(seen.status).toBe(409);
  same("set_feedrate_factor", (refused as Rejected).answer, seen.answer);
}

/** `set_flowrate_factor`, refused by a real supervisor's own policy. */
async function refusedSetFlowrateFactor(client: Client, proxy: Recording) {
  const refused = await client
    .setFlowrateFactor(world.print_id, 1.0, REASON, 60)
    .catch((raised: unknown) => raised);

  expect(refused).toBeInstanceOf(Rejected);
  expect((refused as Rejected).reason).toHaveProperty("actor_may_not_request");
  const seen = proxy.last();
  expect(seen.status).toBe(409);
  same("set_flowrate_factor", (refused as Rejected).answer, seen.answer);
}

/** `set_fan_percent`, refused by a real supervisor's own policy. */
async function refusedSetFanPercent(client: Client, proxy: Recording) {
  const refused = await client
    .setFanPercent(world.print_id, 50.0, REASON, 60)
    .catch((raised: unknown) => raised);

  expect(refused).toBeInstanceOf(Rejected);
  expect((refused as Rejected).reason).toHaveProperty("actor_may_not_request");
  const seen = proxy.last();
  expect(seen.status).toBe(409);
  same("set_fan_percent", (refused as Rejected).answer, seen.answer);
}

/** `set_tool_target_c`, refused by a real supervisor's own policy. */
async function refusedSetToolTargetC(client: Client, proxy: Recording) {
  const refused = await client
    .setToolTargetC(world.print_id, REASON, 210.0, 0, 60)
    .catch((raised: unknown) => raised);

  expect(refused).toBeInstanceOf(Rejected);
  expect((refused as Rejected).reason).toHaveProperty("actor_may_not_request");
  const seen = proxy.last();
  expect(seen.status).toBe(409);
  same("set_tool_target_c", (refused as Rejected).answer, seen.answer);
}

/** `set_bed_target_c`, refused by a real supervisor's own policy. */
async function refusedSetBedTargetC(client: Client, proxy: Recording) {
  const refused = await client
    .setBedTargetC(world.print_id, REASON, 60.0, 60)
    .catch((raised: unknown) => raised);

  expect(refused).toBeInstanceOf(Rejected);
  expect((refused as Rejected).reason).toHaveProperty("actor_may_not_request");
  const seen = proxy.last();
  expect(seen.status).toBe(409);
  same("set_bed_target_c", (refused as Rejected).answer, seen.answer);
}

/** `acknowledge_failure`, refused by a real supervisor's own policy. */
async function refusedAcknowledgeFailure(client: Client, proxy: Recording) {
  const refused = await client
    .acknowledgeFailure(world.print_id, "continue", world.event_id, REASON)
    .catch((raised: unknown) => raised);

  expect(refused).toBeInstanceOf(Rejected);
  expect((refused as Rejected).reason).toHaveProperty("actor_may_not_request");
  const seen = proxy.last();
  expect(seen.status).toBe(409);
  same("acknowledge_failure", (refused as Rejected).answer, seen.answer);
}

/** `pause`, refused by a real supervisor's own policy. */
async function refusedPause(client: Client, proxy: Recording) {
  const refused = await client.pause(world.print_id, REASON).catch((raised: unknown) => raised);

  expect(refused).toBeInstanceOf(Rejected);
  expect((refused as Rejected).reason).toHaveProperty("actor_may_not_request");
  const seen = proxy.last();
  expect(seen.status).toBe(409);
  same("pause", (refused as Rejected).answer, seen.answer);
}

/** `resume`, refused by a real supervisor's own policy. */
async function refusedResume(client: Client, proxy: Recording) {
  const refused = await client.resume(world.print_id, REASON).catch((raised: unknown) => raised);

  expect(refused).toBeInstanceOf(Rejected);
  expect((refused as Rejected).reason).toHaveProperty("actor_may_not_request");
  const seen = proxy.last();
  expect(seen.status).toBe(409);
  same("resume", (refused as Rejected).answer, seen.answer);
}

/**
 * Every action, refused by a real supervisor's own policy, as a typed rejection.
 *
 * One client acting as an actor class the envelope grants nothing. The policy
 * takes that decision before it looks at the state, the interval or the bounds,
 * so every action is refused from wherever the machine happens to be.
 */
test("every action is refused as a typed rejection by a real supervisor", async () => {
  await using proxy = new Recording(world.server);
  const client = new Client({
    server: proxy.url,
    actor: { agent: { session_name: "an actor this envelope grants nothing" } },
  });

  await refusedCancel(client, proxy);
  await refusedStartPrint(client, proxy);
  await refusedSetFeedrateFactor(client, proxy);
  await refusedSetFlowrateFactor(client, proxy);
  await refusedSetFanPercent(client, proxy);
  await refusedSetToolTargetC(client, proxy);
  await refusedSetBedTargetC(client, proxy);
  await refusedAcknowledgeFailure(client, proxy);
  await refusedPause(client, proxy);
  await refusedResume(client, proxy);
}, 900_000);
