[package]
name = "printobserver"
description = "The printobserver command-line program."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
printobserver-server = { path = "../printobserver-server", version = "0.1.0" }
tokio = { version = "1", features = ["rt-multi-thread"] }

[dev-dependencies]
tempfile = "3"

[lints]
workspace = true
